### DISCUSSION TITLE
How to pickup staticwebapp.config.json in my react build?

### DISCUSSION THREAD

**Discussion by jay-cascade** [Azure/static-web-apps#1175] [Q&A] [answered]
I am working on a SWA, but can't seem to get my 'staticwebapp.config.json' to work! According to the docs this should be located in the same location as 'app_location', which I currently have set to my 'frontend' folder. What am I missing here?

I have the following directory structure:

Static-Web-Project
--.github/workflows
----{workflow}.yml
--api <-- Azure Functions
--frontend <-- Create React App
----build
----src
----staticwebapp.config.json
    
My workflow file is as follows:
 
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_MUD_0DD3F6F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "frontend" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "frontend" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_MUD_0DD3F6F03 }}
          action: "close"
``` 

My 'staticwebapp.config.json' file content:

```
{
  "navigationFallback": {
    "rewrite": "/index.html"
  }
}
``` 

When I commit to the main branch of my repo, the actions run, but nothing seems to be happening with my config. I need to redirect all requests to index.html.

Any help would be greatly appreciated, this issue is beginning to make me miserable and holding up proceedings!

Thanks.
