### DISCUSSION TITLE
Add ssh key to AzureStaticWebApp@0

### DISCUSSION THREAD

**Discussion by ValGeorgiev** [Azure/static-web-apps#1221] [Q&A]
Hey all

I am trying to deploy Next.js static app to azure. Our app is using a package that is a private repository. On other projects I just install ssh key like this 
```

- task: InstallSSHKey@0
    inputs:
      knownHostsEntry: '$(KNOWN_HOST)'
      sshPublicKey: '$(PUBLIC_KEY)'
      sshKeySecureFile: 'id_rsa'
```
and everything works, but with AzureStaticWebApp@0 it looks like everything is executed in docker and the ssh key is lost if it's predefined before. How I can install the ssh key correctly so AzureStaticWebApp can pick it up?

My ssh key env variables are correct, I tried to run a yarn install script after the InstallSSHKey task and it worked, but it's not working on AzureStaticWebApp

Any help is much appreciated!
