### DISCUSSION TITLE
Nuxt3 static

### DISCUSSION THREAD

**Discussion by SveinnB** [Azure/static-web-apps#1250] [Q&A] [answered]
Is it possible to deploy Nuxt3 as static with `yarn generate` to Azure Static Web Apps?

I have the following yml

```
- name: Build And Deploy
  id: build-and-deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    action: "upload"
    app_location: "/portal" # App source code path
    output_location: "dist" # Built app content directory - optional
    app_build_command: "yarn generate"
    skip_api_build: true
```

I get the following error
`Failed to find a default file in the app artifacts folder (dist). Valid default files: index.html,Index.html.`

Nuxt3 generates `200.html` but no `index.html` and I think this is not configurable in nuxt.
Is there any way to get Azure to support 200.html as default file?

I can deploy nuxt3 with `yarn build` (server, SRR).
But I want to deploy my app as static with `yarn generate`
