### DISCUSSION TITLE
Improved support for Next.js (Preview) for Static Web Apps

### DISCUSSION THREAD

**Discussion by thomasgauvin** [Azure/static-web-apps#1428] [Announcements]
Hi folks!

We’ve rolled out improvements to our Next.js support on Azure Static Web Apps, specifically as it regards support for newer Next.js versions, and new server-side Next.js features. [Here’s the blog post for the details on the announcement](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/improved-next-js-support-preview-for-azure-static-web-apps/ba-p/4078617).

## Here’s the TLDR:

* Support for Next.js 14 (& 13), React Server Components, App Directory, Server Actions: These server-focused features of Next.js are now fully supported on Azure Static Web Apps. We know many of you have started using these features to build full-stack components/server-side components that access to databases or APIs. This is now supported on Azure Static Web Apps, with the server-side functionality hosted on Static Web Apps’ managed backend functions. 
* Increased size limits: While we were previously constrained to 100mb deployments, Next.js deployments on Azure Static Web Apps now support up to 250mb deployments. Standalone or static outputs are still the recommended workaround if your app sizes are expected to go beyond this.
* Partial support for `staticwebapp.config.json`: You can now handle header configurations, redirects, and routes permissions with the `staticwebapp.config.json` file. Certain configurations also need to be configured within the `next.config.json` configuration file in order for the Next.js server to expect certain behaviors. Some features are unsupported, such as the navigation fallback, which is configured on your behalf for the Next.js site.
* Access to Static Web Apps built-in authentication: You can now access the users’ client principal from the headers of the request within your Next.js API routes, React Server Components or Server Actions.

This improved support for Next.js current and future versions is enabled by the fact that Next.js backend functions are now hosted on dedicated App Service plans, with no change to current Static Web Apps plans. Next.js static assets continue to hosted on Static Web Apps’ globally distributed content host. 

## We continue to gather feedback, here's how to chime in:

We continue to gather feedback on our support for Next.js, and are actively tracking these issues which are currently affecting some Next.js sites. Please contribute to these threads if you are affected by these issues. 

Static Web Apps related issues:
* Build timeout when trying to deploy Next.js · Issue #1427 · Azure/static-web-apps (github.com)
* https://github.com/Azure/static-web-apps/issues/1417
* Static Web Apps does not yet support Node 20, please use 18.17.1: https://github.com/Azure/static-web-apps/issues/1354. 

Next.js related issues:
* Next.js version 13.4.13 has issues with app directory https://github.com/vercel/next.js/issues/53740, we recommend bumping to 13.5.6 or above

If you have general questions, feedback or issues which are not tracked above, please share them in this thread.

### Enabling standalone

Deployment sizes are now 250mb, but you may still want to use standalone to deploy apps of larger size or decrease deploy times. To do so, you must do the following.

Enable standalone in `next.config.json`:
```
const nextConfig = {
    output: 'standalone',
};
```

Static Web Apps requires that your standalone output is left in the default location (`.next/standalone`).

### Specifying Node version

Some recent versions of Next.js require versions of Node.js above the default, to specify the Node.js version in your Next.js site, add the following within your `package.json`:

``` 
{
  "engines": {
    "node": "18.17.1"
  }
}
```

Previous announcements regarding Next.js: https://github.com/Azure/static-web-apps/discussions/1066, https://github.com/Azure/static-web-apps/discussions/921

Happy shipping! 🚀

**Comment by gffelisberto** [comment]
this is great news! thank you :)

**Comment by JeroenvdBurg** [comment]
Congrats on the improved support for Next.js on Static Web Apps. 🎉  This new release fixes a lot of our concerns/issues.  Next 14 is now working nicely including ISR. 

Especially the dedicated compute for the azure functions results in much better performance in the SSR.  In the region of the static webapp (West Europe) the performance is steady between 200 and 300 ms. With some outliers (not sure where those come from). Also no more coldstarts of the function after the first time hit.

You can clearly see that in other regions the latency is a lot higher, up to 2,5 sec avg in West-US. 
So for multi-region sites the new distributed functionality would be really welcome https://github.com/Azure/static-web-apps/discussions/1429 (however not supported for next.js at the moment) 

![image](https://github.com/Azure/static-web-apps/assets/30255073/d41fc9aa-3db3-48cd-8889-a1ec2f2fd949)

Furthermore (Local) development and deployment using the SWA CLI would be really usefull. We also use the SWA CLI in our devops pipeline instead of the Static Web Deploy task. 

Overall a great achievement of the team, keep up the good work! Looking forward to GA .

**Comment by socketsguru** [comment]
Should we still be using **Azure/static-web-apps-deploy@latest** for GitHub actions deployment?

If I set output = standalone as you suggest above then what values should I use here??

```
- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@latest
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_STONE_02251B610 }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/"
    api_location: ""
    output_location: "out"
    skip_app_build: false
```

**Comment by angelitaooo** [comment]
@thomasgauvin @Reshmi-Sriram Can you point us to an example of how to configure the azure-pipelines.yml for deploying a server-side Next.js app using Azure DevOps, please?

This is what I have so far, and in the CD process, I'm getting an error, but in Azure DevOps I can see the artifacts downloaded correctly 
but the next step, this - task: AzureStaticWebApp@0 failed. 
![image](https://github.com/user-attachments/assets/b5b2428f-4461-45cb-8ab7-5186a756e167)


```.yml
    jobs:
      - deployment: DeployWebapp
        displayName: Deploying to Development
        environment: develop
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Artifacts
                  inputs:
                    artifact: webapp
                    path: $(Build.SourcesDirectory)/webapp

                - task: AzureStaticWebApp@0
                  displayName: Deploy to Azure Static WebApp
                  inputs:
                    app_location: "/webapp"
                    output_location: ""
                    app_build_command: 'echo No build required' # Skip the Oryx build by using a no-op command
                  env:
                    azure_static_web_apps_api_token: $(deployment_token)
                    ....

```

**Comment by abbasalwash** [comment]
Is there any information on when support for Next.js (Preview) for Static Web Apps will move out of preview and into production? In our work, we need this functionality, as we do not deploy preview features to production. It’s fantastic that this functionality is supported! Alternatively, is there a roadmap that I could refer to?

**Reply by sijday** [reply]
+1

**Reply by lucasahlgrenToxic** [reply]
+1

**Comment by matt-gribben** [comment]
Does anybody know if it's possible to give the App Service that runs the server side functions access to a private vnet? I'd like to be able to give it access to an api that isn't public.

**Comment by ozkary** [comment]
Does anyone have a clear understanding of all these build errors, deployment failures and missing functionality when trying to use SWA?

- Unable to detect index.htm page because the file is at _next/static/server/app not in _next folder 
- Unable to deploy Azure functions when there is not even an api in the project, yet the build attempts to copy to an /api target location
- When the app builds, images do not load
- When the app builds, some static resources do not render because the _next/static path does not resolve
- next.config rewrite routes do not work. 

There are several props to use like api_location, output_location, skip_api_build, artifact_location etc, but the oryx engine is so smart that overrides does settings and fails the build.

I am using node 18, nextjs 14, github actions.

I read that hybrid apps work well with SWA, but I have only been able to deploy full static builds.

I love SWA, but it feels that we are spending too much time troubleshooting deployments for nextjs hybrid apps.

Thanks everyone.

**Reply by gvffelisberto** [reply]
Hello there @ozkary hope you are doing great. 

I would advice you to tweak your AZURE YML file instead letting oryx engine doing the whole process. If you are going for a full static web app the example bellow will work just fine: ( just make sure to replace with your own placeholders from Azure **[REPLACE_THIS_WITH_YOUR_OWN_VALUE]**) as well your target branch. 

Also a few important details when going with full static web app. Configuration in Next.js must be set to output: export and you can not have Next.js optmizing images, so images unoptimized set to true is also necessary....

Hope it helps :)

**next.config.ts**
```
import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  output: "export",
  images: {
    unoptimized: true,
  },
}

export default nextConfig
```


**azure-static-web-apps-[your-own-name].yml**

```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - development
trigger:
  branches:
    include:
      - development

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
      clean: true
    variables:
      - group: [REPLACE_THIS_WITH_YOUR_OWN_VALUE]-variable-group
      - name: NODE_VERSION
        value: "24.x"
    steps:
      - checkout: self
        submodules: true

      - task: NodeTool@0
        inputs:
          versionSpec: ">=24.x"
        displayName: "Install Node.js"

      - script: mkdir -p $(HOME)/.npm
        displayName: "Ensure npm cache folder exists"

      - task: Cache@2
        displayName: "Cache node_modules"
        inputs:
          key: "node_modules | $(Agent.OS) | package-lock.json"
          restoreKeys: |
            node_modules | $(Agent.OS)
          path: $(Build.SourcesDirectory)/node_modules

      - task: Cache@2
        displayName: "Cache .next/cache"
        inputs:
          key: "next | $(Agent.OS) | package-lock.json | v2"
          restoreKeys: |
            next | $(Agent.OS)
          path: "$(System.DefaultWorkingDirectory)/.next/cache"

      - task: Cache@2
        displayName: "Cache npm packages"
        inputs:
          key: "npm | $(Agent.OS) | package-lock.json"
          restoreKeys: |
            npm | $(Agent.OS)
          path: $(HOME)/.npm

      - script: |
          npm ci
        displayName: "Install dependencies"

      - script: |
          npm run build
        displayName: "Build project"

      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_[REPLACE_THIS_WITH_YOUR_OWN_VALUE])
          app_location: "/out" # Root of your app
          output_location: "out" # Where Next.js outputs static files
          skip_app_build: true # Prevent Oryx from running its own build
          is_static_web_app: true
```

Everything available under: Build configuration for Azure Static Web Apps - just select either github-actions or azure-pipelines :-)
