### DISCUSSION TITLE
Issue with deployment_environment

### DISCUSSION THREAD

**Discussion by sonomirco** [Azure/static-web-apps#1552] [Q&A]
I followed these link.
https://learn.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=github-actions

https://github.com/Azure/static-web-apps/discussions/787

This is the action
```
name: Deploy documentation for development

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - develop
      - "dev/**"
      - "feat/**"
    paths:
      - "web/**"
      - "media/**"

jobs:
  deploy_dev_doc:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://mango-desert-0545fe40f-development.eastus2.5.azurestaticapps.net
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: 🚀 Build and deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./web"
          api_location: ""
          output_location: "build"
          deployment_environment: "development"
```
**Expected behavior**
I should have this URL `https://mango-desert-0545fe40f-development.eastus2.5.azurestaticapps.net` generated in the Azure Static Web App, but I have this one `https://mango-desert-0545fe40f-78.eastus2.5.azurestaticapps.net/.auth/login/aad/callback` which it takes the PR's ID.
