### ISSUE TITLE
Default behavior for PR builds from forks fails 

### ISSUE THREAD

**Issue by clairernovotny** [Azure/static-web-apps#1]
A very common scenario is people outside the repo contributing PR's. The current default Actions template fails the PR since the secrets aren't available. 

At the very least, it should still build but then pass the PR without doing any deploy. 

This should be fixed soon or people who try it out may quickly get frustrated and remove it since all their PR's fail.

**Comment by dariagrigoriu** [comment]
We are planning to consider build and pass the PR without deployment as future behavior. Pre-production environments are limited and auto-deployment in this scenario may not be what the app owner intends in all cases.

**Comment by clairernovotny** [comment]
What if we do want to auto deploy those?

**Comment by orta** [comment]
Hi folks, pretty advanced GitHub Actions user here. Now that we can have microsoft repos use SWA, I got it running for TypeScript. I have it set up to deploy for on an open source repo for external PRs, but I need to find a way to get the URL back into my PR.

Here's what I originally did:

1. I set up the repo in [azure portal](https://github.com/microsoft/TypeScript-Website/commit/0fb5bac1266433c27580fe4c4379bc05ede93f83)
2. I refactored that new workflow into my normal [CI workflow](https://github.com/microsoft/TypeScript-Website/pull/930) 

This hit the 'public repos' don't get secrets issue. Which is fine, because [`workflow_run`](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) exists.

Here's how it works:

Now, my CI builds an artifact on CI instead of deploying. That artifact is passed to a `workflow_run` action which then uploads it (because it has access to the secrets)

- [CI.yml](https://github.com/microsoft/TypeScript-Website/blob/v2/.github/workflows/CI.yml)
- [CI-post.yml](https://github.com/microsoft/TypeScript-Website/blob/v2/.github/workflows/CI-post.yml)

This allows an OSS repo to get contribution PRs which trigger the upload. Doing it this way doesn't get the message back in the comment thread however, but it [does upload](https://github.com/microsoft/TypeScript-Website/runs/1000542020?check_suite_focus=true#step:7:8)

So my request is that the [GitHub Action sets an output of the URL](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs), then I can have all sorts of ways of grabbing the URL and presenting it to users. ( I built [danger-js](https://danger.systems/js/) for this use-case a few years ago. )

If someone reaches out to me on MS teams, to let me know where code lives - I can help ship that code get that to work. Otherwise I'll look around and see if there are APIs I can use to find the URL like `https://nice-meadow-0c9756810.azurestaticapps.net`

**Comment by clairernovotny** [comment]
@orta that's awesome!

**Comment by miwebst** [comment]
@orta this is super cool! Having the url as an output is something a lot of folks have asked for especially for performing tests after deployment. The challenge for us is that we run inside a Docker based Github Action. Do you know of anyway to set the output for the action when using Docker based actions?

**Comment by orta** [comment]
I do, the way it works is that GH listens to specially crafted stdout messages from your action to determine outputs.

I'll assume bash (for my familiarity), but realistically it can be anything:

```sh
echo “::set-output name=<output name>::<value>”
```

e.g.

```sh
echo “::set-output name=static_web_app_deploy_url::https://nice-meadow-0c9756810.azurestaticapps.net”
```

Would let me pick that up in another workflow step, there's some [docs here](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#testing-out-your-action-in-a-workflow) with sample [code here](https://github.com/actions/hello-world-docker-action/blob/main/entrypoint.sh#L5)

**Comment by miwebst** [comment]
Small update, we did get a working prototype of this! Thanks for the help. I will followup once we've finished testing and released it.

**Comment by miwebst** [comment]
This is now in production, you can access the build and deploy output like so:

`${{ steps.builddeploy.outputs.static_web_app_url }}`

**Comment by orta** [comment]
Thanks!

**Comment by orta** [comment]
👋🏻 - I've been working on a sample repo which shows the OSS PR process. Here's _how_ it works so far, and then after, why it's not working _yet_.

Repo: https://github.com/orta/pr-builds-static-web-apps
Workflow Files: One for [CI](https://github.com/orta/pr-builds-static-web-apps/blob/master/.github/workflows/CI.yml) then a [Post-CI](https://github.com/orta/pr-builds-static-web-apps/blob/master/.github/workflows/CI-post.yml) yml 

_( I'd open ^ in a new window to run along-side this comment, they're well commented )_

#### The Problem

A cross-fork PR does not get the access token to push to azure. The token is a secret, and secrets aren't shared to fork PRs, which is a reasonable security measure by GitHub on GH Actions.

Other static site providers like next/gatsby/etc will build the PR builds themselves, and don't have this problem. Because SWA build happens on GH Actions, then the security model of GH Actions affects PR builds.

#### The Solution

Use the new [`workflow_run`](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) process in GitHub Actions. Basically the CI run has limited access, but you can pass an artifact from that build to a workflow which happens after CI.

So, we pass the built version of the site and some PR metadata to a `workflow_run` which uploads to SWA. Then I use [danger](https://danger.systems/js) to send a message to the PR.

#### The Process

- The CI generates all the `*.html` files
- The CI adds the PR JSON to the same folder as the html files
- The CI uploads the html files as an archived zip
- After the CI is finished, the Post-CI workflow starts
- The Post-CI workflow downloads the zip
- The Post-CI workflow uploads the SWA
- The Post-CI workflow triggers a danger run passing the URL from the SWA in

You can see a working PR here: https://github.com/orta/pr-builds-static-web-apps/pull/5

#### What Doesn't Work
 
It only uploads to the 'master' environment, I've tried using a custom branch and pushing that but I think the dockerfile makes assumptions that it is being ran in a PR workflow and I'd need some args which let me define the environment

![Screen Shot 2020-09-21 at 4 57 45 PM](https://user-images.githubusercontent.com/49038/93820527-4e8edc00-fc2b-11ea-8645-50b58d682281.png)

### Potential Solutions

1. Allow some kind of anonymous upload feature to SWA, then you don't have to do all of the above faff. If someone wants to chat about what that could look like, feel free to ping me on MS Teams.

2. Add some more args to `uses: Azure/static-web-apps-deploy`. I could imagine `environment` as a string.

  ```yml
      # Uploads the static build
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        id: deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_MOSS_0DAC87810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "built"
          app_artifact_location: "public"

          environment: "pr_${{ steps.pr_info.outputs.number }}"
  ```
  or the PR meta could be manually added instead:

```yml
      # Uploads the static build
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        id: deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_MOSS_0DAC87810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "built"
          app_artifact_location: "public"

          repo: ${{ steps.pr_info.outputs.number }}
          pull_number: ${{ steps.pr_info.outputs.number }}
  ```

This would let this technique work, but _dang_ the whole thing a bit unfriendly and requires quite a lot of knowledge about how GH Actions works for something which I think someone would expect to kinda work out of the box.

3. Support building on Azure, which is kinda a roundabout way of re-running GH actions I guess. I'm not a general fan of the idea, but I don't have to build it, though that is what the competition is doing,
