### ISSUE TITLE
Azure SWA: Deployment Failure Reason: Failure during content distribution

### ISSUE THREAD

**Issue by brettbaisley** [Azure/static-web-apps#1001]
**Describe the bug**

I was attempting to deploy a minor update to my Azure SWA site, via GitHub Actions, about 8 times since yesterday. Every time the GitHub action runs, it fails with the below error. I tried several times, even reverted all changes back to the last working state. I can't seem to fix this. I found very little online about this error. I found one bug report a year ago that suggested it was an issue on Azure side where it failed to publish globally, but it doesn't say what was done to resolve. 

> ---End of Oryx build logs---
> Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 16
> Finished building function app with Oryx
> Zipping Api Artifacts
> Done Zipping Api Artifacts
> Zipping App Artifacts
> Done Zipping App Artifacts
> Uploading build artifacts.
> Finished Upload. Polling on deployment.
> Status: InProgress. Time: 0.1859918(s)
> Status: Failed. Time: 15.3682705(s)
> Deployment Failed :(
> **Deployment Failure Reason: Failure during content distribution.**
> 
> For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
> If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
> Exiting

**To Reproduce**
Deploy any change, or even rerun any of the failed GitHub Actions, it will fail for this same error.

If possible, please provide the following information if relevant (do not include sensitive content):
**- GitHub Actions or Azure Pipelines workflow YAML file**
```
- name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_POND_07687C10F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          skip_app_build: true # Not using a framework, so no build required
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_POND_07687C10F }}
          action: "close"
```

**- staticwebapp.config.json file**
```
{
    "platform": {
        "apiRuntime": "node:16"
    }
}
```

**Expected behavior**
Deployment to Azure SWA to work successfully.

**Additional context**
I have another project also on Azure SWA that works fine. Seems to be isolate to only this one, for some reason. Not sure why.
