### ISSUE TITLE
App Directory Location Could not detect this directory

### ISSUE THREAD

**Issue by varndellwagglebee** [Azure/static-web-apps#1011]
We have a mono repo and I'm only trying to deploy a project under the repo.  I'm having issues with the project that is located under a sub directory

**To Reproduce**
1.  Create a repository with a sub directory that contains your react app
2.  Create a github action to deploy to azure static-web-app

**Repository structure**
Organization: Stillpoint-software 
repo: wagglebee.ui 
repo sub folder: stillpoint-website - This is where the src folder resides.

**Our yml file**
```
# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Deploy web app to Azure Static Web Apps

on:
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "./packages/stillpoint-website/src" # App source code path relative to repository root
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app   
  NODE_VERSION: '16.x'               
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  DEFAULT-REPOSITORY: '${{github.repository}}/packages/stillpoint-website'
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Set Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version:  ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'packages/stillpoint-website'
        
      - name: Run Yarn install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command
          dir: 'packages/stillpoint-website'
      
      - name: Test the app
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: test # will run `yarn test` command
          dir: 'packages/stillpoint-website'      
    
      - name: Build production bundle
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: build:prod  # will run `yarn build:prod`  command
          dir: 'packages/stillpoint-website'
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: 'packages/stillpoint-website/build'    

  deploy:
    runs-on: ubuntu-latest
    needs: build   
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
        
      - name: Set Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version:  ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'packages/stillpoint-website'
        
      - name: Run Yarn install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command
          dir: 'packages/stillpoint-website'
          
      - name: Build production bundle
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: build:prod  # will run `yarn build:prod`  command
          dir: 'packages/stillpoint-website'
          
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          output_location: "build"  # Built app content directory, relative to app_location - optional
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

```
![azure1](https://user-images.githubusercontent.com/117473104/206752299-073bd895-40db-49ae-93c5-24ae0a9e15fe.png)
