### ISSUE TITLE
Build and Deploy failing lately: Upload Timed Out.

### ISSUE THREAD

**Issue by jpalo** [Azure/static-web-apps#1018]
Trying to build and deploy from Github, but it is failing (4th attempt so far, still failing). This is oldish issue, that was present approximately a year ago, and was partially solved, meaning that the issue only occurred intermittently. 

Now it failed on last week's Monday once, but retry helped, but today I can no longer get the action through. There hasn't been any changes in the deployment file, but obviously the files to be deployed have changed - but number and size of files hasn't increased.

```
Run Azure/static-web-apps-deploy@v1
/usr/bin/docker run --name d9439a706bfc4fa3beb509ba9523d885_d0cb81 --label 290506 --workdir /github/workspace --rm -e "AZURE_STORAGE_CONNECTION_STRING" -e "INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN" -e "INPUT_REPO_TOKEN" -e "INPUT_ACTION" -e "INPUT_APP_LOCATION" -e "INPUT_API_LOCATION" -e "INPUT_OUTPUT_LOCATION" -e "INPUT_API_BUILD_COMMAND" -e "INPUT_APP_ARTIFACT_LOCATION" -e "INPUT_APP_BUILD_COMMAND" -e "INPUT_ROUTES_LOCATION" -e "INPUT_SKIP_APP_BUILD" -e "INPUT_CONFIG_FILE_LOCATION" -e "INPUT_SKIP_API_BUILD" -e "INPUT_PRODUCTION_BRANCH" -e "INPUT_DEPLOYMENT_ENVIRONMENT" -e "INPUT_IS_STATIC_EXPORT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kouluruoka/kouluruoka":"/github/workspace" 290506:d9439a706bfc4fa3beb509ba9523d885
DeploymentId: ed779de8-946c-4f03-87f6-dc14fb392aab

App Directory Location: '/' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221[10](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:11)3.1, Commit: a2c65dde152b749fea395f4d1242ea9350942258, ReleaseTagName: 2022[11](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:12)03.1

Build Operation ID: |K1OMvqA0vPs=.f22bd7be_
Repository Commit : 33d8cfab4f588b[12](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:13)6479340e17150dddfc80b3e5

Detecting platforms...
Detected following platforms:
  nodejs: 14.20.1
Detected the following frameworks: Gatsby


Source directory     : /github/workspace
Destination directory: /bin/staticsites/ed779de8-946c-4f03-87f6-dc14fb392aab-swa-oryx/app

Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v14.20.1

Using Npm version:
6.14.17

Running 'npm install --unsafe-perm'...

  │                                                                    │
  ╰────────────────────────────────────────────────────────────────────╯
info Done building in 82.710693274 sec
Preparing output...

Copying files to destination directory '/bin/staticsites/ed779de8-946c-4f03-87f6-dc14fb392aab-swa-oryx/app'...
Done in 7 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.
Copying .ostype to manifest output directory.

Done in 504 sec(s).


---End of Oryx build logs---
Finished building app with Oryx
No Api directory specified. Azure Functions will not be created.
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1092214(s)
Status: InProgress. Time: 15.2090345(s)
Status: InProgress. Time: 30.5122041(s)
Status: InProgress. Time: 45.615527(s)
Status: InProgress. Time: 60.7163502(s)
Status: InProgress. Time: 75.9527117(s)
Status: InProgress. Time: 91.091292(s)
Status: InProgress. Time: 106.196067(s)
Status: InProgress. Time: 121.2974939(s)
Status: InProgress. Time: [13](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:14)6.6211291(s)
Status: InProgress. Time: [15](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:16)1.7225248(s)
Status: InProgress. Time: [16](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:17)6.8684654(s)
Status: InProgress. Time: [18](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:19)2.1252135(s)
Status: InProgress. Time: [19](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:20)7.2443781(s)
Status: InProgress. Time: [21](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:22)2.3524741(s)
Status: InProgress. Time: [22](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:23)7.458[28](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:29)[37](https://github.com/jpalo/kouluruoka/actions/runs/3727752755/jobs/6326532908#step:4:38)(s)
Upload Timed Out. Unsure if deployment was successful or not.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

If possible, please provide the following information if relevant (do not include sensitive content):
- GitHub Actions or Azure Pipelines workflow YAML file
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'schedule' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SEA_009CF3103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_SEA_009CF3103 }}
          action: "close"
```

- staticwebapp.config.json file
```
{
    "routes": [
        {
            "route": "/*.html",
            "headers": {
                "cache-control": "public, max-age=0, must-revalidate"
            }
        },
        {
            "route": "/sw.js",
            "headers": {
                "cache-control": "public, max-age=0, must-revalidate"
            }
        },
        {
            "route": "/static/*",
            "headers": {
                "cache-control": "public, max-age=31536000, immutable"
            }
        },
        {
            "route": "/*.css",
            "headers": {
                "cache-control": "public, max-age=31536000, immutable"
            }
        },
        {
            "route": "/*.js",
            "headers": {
                "cache-control": "public, max-age=31536000, immutable"
            }
        },
        {
            "route": "/*.map",
            "headers": {
                "cache-control": "public, max-age=31536000, immutable"
            }
        },
        {
            "route": "/*",
            "headers": {
                "cache-control": "public, max-age=0, must-revalidate"
            }
        }
    ],
    "responseOverrides": {
        "404": {
            "rewrite": "/404.html"
        }
    }
}
```

**Expected behavior**
Build&deploy would succeed.
