### ISSUE TITLE
Azure/static-web-apps-deploy is very slow?

### ISSUE THREAD

**Issue by onionhammer** [Azure/static-web-apps#1025]
This is somewhat of an inconvenience, but it reliably takes 40 seconds for github actions to download the ~2 gigabyte static web apps deploy action docker image, let alone run it.

It would be great if a slimmer static file upload option were made available for those who have simpler processes (like `npm run build`, upload `dist`).

**Comment by thomasgauvin** [comment]
Thanks for the feedback @onionhammer , this is something the Oryx team is currently working on, so we're looking forward to seeing that change as well. Here's an issue tracking it in the Oryx repo: https://github.com/microsoft/Oryx/issues/1159

**Comment by onionhammer** [comment]
Hmm. Last public movement on that is a year ago

**Comment by thomasgauvin** [comment]
We're aware that the oryx image being large increases the download time, and are working with Oryx to resolve this. you also mention that you don't need oryx to run `npm run build`, you should be able to prevent those & just upload your built static assets by passing `skip_app_build` or `skip_app_build` depending on your needs

**Comment by onionhammer** [comment]
@thomasgauven does that save the minute and 40 seconds of downloading the oryx image? If not that doesnt help

**Comment by thomasgauvin** [comment]
@onionhammer skipping the app build is a param of the SWA + oryx image, so it does not reduce the time that it takes to download those https://github.com/Azure/static-web-apps/issues/1067#issuecomment-1423023871

Right now, we're focusing on working with Oryx to reduce the size of the image that gets downloaded (by doing language downloads dynamically instead), which should reduce download times. After that, we'll assess providing a build-less/Oryx-less deployment option or other options to continue to reduce build & deploy times

**Comment by thomasgauvin** [comment]
We're looking into providing a deploy-only image for folks who want to configure their pipelines, the Oryx-based build+deploy image is intended to suit every possible project that gets created with SWA without additional configuration

**Comment by simkuns** [comment]
It is possible to cut down deployment time at least in half by using @azure/static-web-apps-cli instead of AzureStaticWebApp@0 task.

<img width="320" alt="Screenshot 2023-11-06 at 21 46 23" src="https://github.com/Azure/static-web-apps/assets/6117989/e96a6dfe-5aee-42fd-890e-e22e34599af9">

---

It can be achieved by creating a dummy repository for @azure/static-web-apps-cli e.g. `azure-static-web-apps-cli`

<img width="360" alt="Screenshot 2023-11-06 at 21 50 24" src="https://github.com/Azure/static-web-apps/assets/6117989/72ca4df1-12a1-47b4-9256-351a5a76dc55">

package.json in dummy repo
```json
{
  "private": true,
  "dependencies": {
    "@azure/static-web-apps-cli": "^1.1.4"
  }
}
```
---

deployment.yml
```yml
# ...
resources:
  repositories:
  - repository: AzureStaticWebAppsCliRepo
    type: git
    name: azure-static-web-apps-cli/azure-static-web-apps-cli
    ref: master
# ...
jobs:
  - job: deploy
    steps:
      - checkout: AzureStaticWebAppsCliRepo
      - task: Cache@2
        displayName: Cache Yarn
        inputs:
          key: '"azure-static-web-apps-cli" | "yarn_v1" | "$(Agent.OS)" | "node_modules" | yarn.lock'
          path: node_modules
          cacheHitVar: YARN_CACHE_RESTORED
      - script: yarn install --frozen-lockfile
        displayName: yarn install --frozen-lockfile
        condition: ne(variables.YARN_CACHE_RESTORED, 'true')
      # ... (Download build artifacts steps)
      - script: |
          SWA_CLI_DEPLOYMENT_TOKEN=$(SWA_DEPLOYMENT_TOKEN) \
          $(System.DefaultWorkingDirectory)/node_modules/.bin/swa deploy \
          -w . \
          -a .output/public \
          -i .output/server \
          --api-language=node \
          --api-version=18 \
          --env=production
        displayName: Deploy AzureStaticWebApp

```
