### ISSUE TITLE
DevOps tasks fails with "deployment_token provided was invalid."

### ISSUE THREAD

**Issue by Eonasdan** [Azure/static-web-apps#1037]
I'm attempting to deploy a static web app via a DevOps pipeline. I want to get the api token from a Azure CLI task after a bicep ARM step. However, I keep getting this error:

> deployment_token provided was invalid.
> An unknown exception has occurred

<details>
  <summary>Pipeline YAML</summary>

```yaml
name: $(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: ubuntu-latest
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - 'site/*'
variables:
- name: appName
  value: 'myswa'
- name: apiToken
  value: ''

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: Con
    subscriptionId: 'sub-id'
    resourceGroupName: 'rg-name'
    location: 'East US 2'
    csmFile: 'azure-deployments/static.bicep'
    overrideParameters: '-siteName $(appName) -location "East US 2"'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Con'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $token = (az staticwebapp secrets list -n $(appName) --query "properties.apiKey")
      Write-Host "##vso[task.setvariable variable=apiToken]$token"
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: '
  inputs:
    workingDirectory: 'site'
    app_location: ''
    skip_app_build: true
    skip_api_build: true
    is_static_export: false
    verbose: false
    azure_static_web_apps_api_token: $(apiToken)
```
</details>

I have verified that the variable does get updated with a correct token. I  just tried this by putting the token directly in the task and that seemed to work.

**Comment by knaopel** [comment]
I have the same issue. I have created the Static Web App, created two variable groups, one for QA and one for prod. I have put the respective tokens in the variable groups.

Here is the yaml
```
name: $(Build.SourceBranchName)_$(date:yyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
        - master
        - test
parameters:
  - name: manualDeploymentEnvironment
    displayName: Manual Deployment Environment
    type: string
    default: 'n/a'
    values: [ 'n/a', 'test', 'prod']

variables:
  # check source branch and set proper environment
  - ${{ if eq(variables['Build.SourceBranceName'], 'test') }}:
    - name: isTest
      value: true
  - ${{ if eq(variables['Build.SourceBranceName'], 'master') }}:
    - name: isProd
      value: true
  # if the source branch is not in ['test', 'master'], check the manual deployment environment parameter and set proper environment
  - ${{ if and(notIn(variables['Build.SourceBranceName'], 'test', 'master'), eq(parameters.manualDeploymentEnvironment, 'test')) }}:
    - name: isTest
      value: true
  - ${{ if and(notIn(variables['Build.SourceBranceName'], 'test', 'master'), eq(parameters.manualDeploymentEnvironment, 'prod')) }}:
    - name: isProd
      value: true
  
jobs:
- job: build_and_deploy
  displayName: Build and Deploy job
  condition: or(eq(variables['Build.Reason'], 'Manual'), or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
    - ${{ if eq(variables.isTest, 'true') }}:
      - group: timecard-tracker-static-web-qa
    - ${{ if eq(variables.isProd, 'true') }}:
      - group: timecard-tracker-static-web-prod
  steps:
    - task: NodeTool@0
      displayName: 'Install Node'
      inputs:
          versionSpec: '16.19.0'
    - script: yarn install
      displayName: Install Dependencies
    - script: |
        yarn expo export:web
        ls web-build
      displayName: Expo Export

    - task: AzureStaticWebApp@0
      displayName: Deploy to Azure Static Web App
      inputs:
        azure_static_web_apps_api_token: '$(Static-Web-App-Token)'
        app_location: './web-build'
        output_location: './web-build'
```
