### ISSUE TITLE
Mkdocs build in Azure Static web app failed 

### ISSUE THREAD

**Issue by espadrillesbanyoles-martidou** [Azure/static-web-apps#1063]
Hi, 
I have just installed mkdocs in Mac, forked **Mkdocs-material** from GitHub and I am able to publish locally (http://127.0.0.1:8000/). I am commiting to **Azure DevOps** repository. I created a new **Azure static web app** to publish content stored in this repository from Azure DevOps. This action creates a YAML file for pipeline execution (Azure Static Web Apps CI/CD), so everytime I commit to this repository, an azure pipeline updates the static web app. But this pipeline gets an error when trying to build this app:

```
---End of Oryx build logs---
The app build failed to produce artifact folder: 'site'. Please ensure this property is configured correctly in your deployment configuration file.
```

My .yml file looks like:

```
- task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_STONE_0A8EBA403)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "site" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

**Comment by sarsharma** [comment]
Hi @espadrillesbanyoles-martidou, Static Web Apps makes use of [Oryx](https://github.com/microsoft/Oryx/blob/main/README.md) to build the apps and currently Oryx does not support building MkDocs apps (https://github.com/microsoft/Oryx/issues/1124, https://github.com/microsoft/Oryx/issues/1027)

You can still deploy Mkdocs app if you build the app yourself in a previous step and just pass the built static content folder(`site` folder in case of Mkdocs) in the `app_location` in the above .`yml` while setting the `output_location` as an empty string. For this, you also need to set the `skip_app_build` flag, which will prevent Oryx from trying to build your app. 
Reference: https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=azure-devops#skip-building-front-end-app

Example of edited job to pre-build mkdocs app:

```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Mkdocs
        run: |
          pip install mkdocs
          pip install -r requirements.txt
          mkdocs build
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_DESERT_0A5491A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "site" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true
```

**Comment by espadrillesbanyoles-martidou** [comment]
Hi Sarthak Sharma, many thanks. That works amazing!

De: Sarthak Sharma ***@***.***>
Fecha: lunes, 20 de febrero de 2023, 8:08
Para: Azure/static-web-apps ***@***.***>
CC: Martí Dou ***@***.***>, Mention ***@***.***>
Asunto: Re: [Azure/static-web-apps] Mkdocs build in Azure Static web app failed (Issue #1063)

Hi @espadrillesbanyoles-martidou<https://github.com/espadrillesbanyoles-martidou>, Static Web Apps makes use of Oryx<https://github.com/microsoft/Oryx/blob/main/README.md> to build the apps and currently Oryx does not support building MkDocs apps (microsoft/Oryx#1124<https://github.com/microsoft/Oryx/issues/1124>, microsoft/Oryx#1027<https://github.com/microsoft/Oryx/issues/1027>)

You can still deploy Mkdocs app if you build the app yourself in a previous step and just pass the built static content folder(site folder in case of Mkdocs) in the app_location in the above .yml while setting the output_location as an empty string. For this, you also need to set the skip_app_build flag, which will prevent Oryx from trying to build your app.
Reference: https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=azure-devops#skip-building-front-end-app

Example of edited job to pre-build mkdocs app:

jobs:

  build_and_deploy_job:

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    runs-on: ubuntu-latest

    name: Build and Deploy Job

    steps:

      - uses: ***@***.***

        with:

          submodules: true

      - name: Build Mkdocs

        run: |

          pip install mkdocs

          pip install -r requirements.txt

          mkdocs build

      - name: Deploy

        id: builddeploy

        uses: ***@***.***

        with:

          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_DESERT_0A5491A10 }}

          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)

          action: "upload"

          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######

          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

          app_location: "site" # App source code path

          api_location: "" # Api source code path - optional

          output_location: "" # Built app content directory - optional

          skip_app_build: true

**Comment by villeodell** [comment]
Oryx can build it if you tell it how by setting `POST_BUILD_COMMAND` as an environment variable.

Example:
```yml
with:
  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  repo_token: ${{ secrets.GITHUB_TOKEN }}
  action: 'upload'
  app_location: 'src'
  api_location: 'api'
  output_location: 'site'
env: # Add environment variables here
  POST_BUILD_COMMAND: "mkdocs build"
```
Be sure that `output_location` is set correctly.

References:
https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#environment-variables
https://github.com/microsoft/Oryx/blob/main/doc/configuration.md#oryx-configuration
