### ISSUE TITLE
Azure DevOps AzureStaticWebApp@0 task not deploying function

### ISSUE THREAD

**Issue by furier** [Azure/static-web-apps#1068]
Building Nuxt 3.1 with **nitro preset** `azure` works fine locally, after building with `yarn build` aka `nuxt build` the following command is outputted: `npx @azure/static-web-apps-cli start .output/public --api-location .output/server` and it works fine.

However when deploying with Azure DevOps with task `AzureStaticWebApp@0` this warning is outputted.
```
[WARNING] Api Directory Location: '.output/server' could not be found. Azure Functions will not be created.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
```

But as one can clearly see in this screenshot the build clearly output files to the path `.output/server`.

![image](https://user-images.githubusercontent.com/776919/217811342-29c0fc84-5336-40a8-b416-bf4ffd32304e.png)

Here is the `yml` build file

```yml
name: AMV.Portal

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "src/AMV.Portal.yml"
      - "src/AMV.Portal/*"

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: AMV.Portal
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_BEACH_0B93C2303)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/src/AMV.Portal" # App source code path
      api_location: ".output/server" # Api source code path - optional
      output_location: ".output/public" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

and this is the `nuxt.config.ts` file, setting the azure preset for nitro.
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  nitro: {
    preset: 'azure'
  }
})
```

`staticwebapp.config.json` as generated by the build command
```json
{
  "platform": {
    "apiRuntime": "node:16"
  },
  "routes": [
    {
      "route": "/index.html",
      "redirect": "/"
    },
    {
      "route": "/",
      "rewrite": "/api/server"
    }
  ],
  "navigationFallback": {
    "rewrite": "/api/server"
  }
}
```

![image](https://user-images.githubusercontent.com/776919/217814170-59538fc4-1d1d-4470-b5c3-c3187fbfd491.png)

**Expected behavior**
As I have the file under `server/api/hello.ts` defined and the build outputs an azure function, I expect the deployment to create an azure function to host the nuxt api.

```ts
export default defineEventHandler(() => 'World!')
```

**Documentation sources**
- https://nitro.unjs.io/deploy/providers/azure
- https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs

I have been burning 10 hours on this issue now and the internett does not seem to have an answer for this, so I am here hoping you can help.
