### ISSUE TITLE
Cannot deploy to the function app because Function language info isn't provided.

### ISSUE THREAD

**Issue by lancerael-undo** [Azure/static-web-apps#1071]
I am deploying an app from a mono repo built using pnpm, which does not work with this task, so I am prebuilding it and trying to deploy from the built folder. The task finds the folder but does not deploy, giving the error  `Cannot deploy to the function app because Function language info isn't provided.`

I cannot find any solution to this. I have added the platform to the config, and the folder is found. 

`staticwebapp.config.json`  (also tried Node 16)

```
{
  "routes": [
    {
      "route": "/api/ims",
      "allowedRoles": ["authenticated"]
    }
  ],
  "platform": {
    "apiRuntime": "node:18"
  }
}
```

`yml`

```
- name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/src/apps/ims/build'
          api_location: '/src/apps/ims/api/build' 
          output_location: ''
          skip_app_build: true
          skip_api_build: true
```

Result

```
Api Directory Location: '/src/apps/ims/api/build' was found.
Skipping step to build /github/workspace/src/apps/ims/api/build with Oryx
Cannot deploy to the function app because Function language info isn't provided.
```
