### ISSUE TITLE
[Github Actions] Set pull request environment name

### ISSUE THREAD

**Issue by chatelain-io** [Azure/static-web-apps#1074]
A new preview environment is created per pull request which create a new subdomain with the pull request number. My static web app is configured with custom authentication using Azure Active Directory. In the app registration, you must specify the redirect uri.
The redirect uri do not support wildcard at the subdomain level so we need to automate the creation of the redirecturi for that specific pull request in a pipeline. Currently you can set the production branch (production_branch) name and the deployment environment (deployment_environment) for feature branches but you cannot change the pull request environment name.

It would be a nice feature to add an attribute to be able to configure the pull request environment name.

```yaml
- name: Deploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    ...
    production_branch: "main"
    deployment_environment: "dev"
    pr_environment: "pr"
   ....
```

**Comment by MrMossevig** [comment]
In theory youu could do this by:
`deployment_environment: ${{ github.event_name == 'pull_request' && 'pr' || 'dev' }}` but there is currently a bug that is not naming the PR-environments correctly.

**Comment by c-baumgartner** [comment]
I am bumping this issue because this really makes life hard to work without PRs because as @chatelain-io mentioned, wildcard is not supported here.

Of course we could come up with a complex process to automate the adding and removing of redirect_uris to the app registration, but this is so much more complicated than honoring the `deployment_environment` input correctly or adding a dedicated option as requested by the author of this issue.

So please take this on your roadmap for the action to have more control over the environment names - even if this results in overwriting an environment with different PRs

**Comment by c-baumgartner** [comment]
I could not rest without solving my situation to an extend that I can provide temporary links to my users for reviewing changes with working authentication. I also want to avoid deploying to the same environment from different pull request and overwriting any previous deployments while in review

I hope you like the solution or at least it will help you to improve the process by using it or using parts of it.

A big shoutout goes to Tommi`s [post](https://stackoverflow.com/questions/76388274/updating-web-redirect-uri-of-azure-ad-app-registration) on stackoverflow.com. It really helped me to start with the bash script.

I assume you are using Entra ID for your custom authentication for the static web app and that everything is working.

## Automation service principal

1. You need to create a new app registration and a corresponding service principal in your Entra ID.  Let's call this app `redirect-uri-automation-spn`. This app/spn is used to automate adding/removing redirect_uris from your authentication applications manifest file.
2. Add Graph API permission: `Application.ReadWrite.OwnedBy` as an application permission. This needs to be consented by a Global Admin.
3. Take a note for the `ClientId` and `TenantId` - you need this later.
4. You also need to write down the `ClientId` for the already existing authentication app 

## Owner permission

The newly created sercie principal needs `owner` permission on the authentication app registration. This is needed to update the app manifest with the Azure CLI. To add the permission you have to look up the `ObjectID` for the Service Principal that was created with the `redirect-uri-automation-spn` app registration

I did not find a way to add a SPN as Owner to an app registration so you have to use for example Azure CLI:

```bash
az ad app owner add --id <auth-app-client-id> --owner-object-id <redirect-uri-automation-spn-object-id>
```

## Federated credentials

For the authentication within the GitHub Action we are going to use federated credentials. Go to the `redirect-uri-automation-spn` app registration and create a new federated credential. 

- **Name**:  GitHubAction 
- **Scenario**: GitHub Actions deploying Azure resources
- **Entity Type**: Pull Request
- **Organization**: Your GitHub org/username
- **Repository**: The repo name

**It is very important to set the entity type to `pull request`**

## GitHub Setup

Add four GitHub Actions variables to your repository:

    - **AZURE_CLIENT_ID** - The ClientId of the newly created app registration
    - **AZURE_TENANT_ID** - The TenantId
    - **TARGET_CLIENT_ID** - The ClientId used by your authentication app
    - **SWA_PREVIEW_ENV_BASE_URI** - This is the URI the Static App is creating for the temp environments. See description below

## SWA_PREVIEW_ENV_BASE_URI

The URL that is generated to access your temporary environment follows a pattern. For every PR in GitHub the pull request number is added to the URL. The `SWA_PREVIEW_ENV_BASE_URI` GitHub Actions variable need to contain your URL in the format:

https://<some-name>-<012345678>**-%%**.<location>.<slot>.azurestaticapps.net

The part **-%%** is crucial because we use this as a place holder and replace it later in the pipeline (I will also explain why)

## GitHub Action

For the GitHub Action you can use the template MSFT is providing for the Pull Request workflow. You just need to add the following steps after the Azure/static-web-app-deploy steps

### build_and_deploy_job

>[!IMPORTANT]
>Make sure to replace the step ID for `steps.buiddeploy.outputs.static_web_app_url` with your ID

```yaml
  - name: Azure login
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: azure/login@v2
    with:
      client-id: ${{ vars.AZURE_CLIENT_ID }}
      tenant-id: ${{ vars.AZURE_TENANT_ID }}
      allow-no-subscriptions: true
  - name: Update redirect URI
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    id: updateuri
    run: |
      uri="${{ steps.builddeploy.outputs.static_web_app_url }}/.auth/login/aad/callback"
      client_id="${{ vars.TARGET_CLIENT_ID }}"

      # Get string array of existing redirect URIs
      existing_redirect_uris=$(az ad app show --id $client_id --query "[web.redirectUris]" --output tsv)
      echo $existing_redirect_uris

      # Check if the new URI is already in the list
      if [[ $existing_redirect_uris == *$uri* ]]; then
        echo "The URI $new_uri is already in the list"
      else
        echo "Adding the URI $new_uri to the list"
        az ad app update --id $client_id --web-redirect-uris $existing_redirect_uris $uri      
      fi
```

### close_pull_request_job

```yaml
  - name: Azure login
    uses: azure/login@v2
    with:
      client-id: ${{ vars.AZURE_CLIENT_ID }}
      tenant-id: ${{ vars.AZURE_TENANT_ID }}
      allow-no-subscriptions: true          
  - name: Remove redirect URI
    id: removeuri
    env:
      PR_NUMBER: ${{ github.event.number }}
    run: |
      # We do not get the URI in case for action CLOSE from the closepullrequest step.
      # So we are using the PR_NUMBER and build the URI by ourselves.
      uri=$(echo "${{ vars.SWA_PREVIEW_ENV_BASE_URI }}/.auth/login/aad/callback" | sed "s|%%|$PR_NUMBER|g")
      client_id="${{ vars.TARGET_CLIENT_ID }}"
      echo $uri

      remaining_redirect_uris=$(az ad app show --id $client_id --query "[web.redirectUris]" --output tsv | sed "s|$uri||g")
      echo $remaining_redirect_uris
      az ad app update --id $client_id --web-redirect-uris $remaining_redirect_uris
```

The removal of the redirect uri is a little bit different than the creation where we can rely on a previous step output because the static-web-app-deploy action will not output `static_web_app_url` if the `action` is set to `close`. This is why I am using `github.event.number` and replacing the two **%%** with that number. 

## Final thoughts

This process is quite complex. But if you can live with the security of having a SPN modifying another app registration via pipeline and you are not afraid of implementing this kind of process you will be very happy.

I have tested this process very intense and for me it came out great. Again hope this helps to overcome some of the default behavior.
