### ISSUE TITLE
Invalid environment name

### ISSUE THREAD

**Issue by jgarplind** [Azure/static-web-apps#1119]
Since today, this error message has surfaced:

> The environment name provided exceeds the character limit of 16 or has invalid character(s). Valid characters are 0-9, a-z, and A-Z. Please provide a valid name for your environment like 682

12 days ago, using an identical YAML, this was not the case.

**To Reproduce**
1. Run this:

- GitHub Actions or Azure Pipelines workflow YAML file
```
name: Validate Pull Request

on:
  pull_request:
    branches: main

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm install
      - run: pnpm run formatcheck
      - run: pnpm run stylecheck
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run test

  build-and-deploy-preview:
    if: contains(github.event.pull_request.labels.*.name, 'pr-environment')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm install
      - run: pnpm run build

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "build" # App source code path
          output_location: "" # Built app content directory - optional
          deployment_environment: preview
          skip_app_build: true
```
- staticwebapp.config.json file
```
{
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["*.{svg,png,jpg,gif}", "*.{css,scss}", "*.js"]
  }
}
```
- source repository if it's public
N/A (private)

**Expected behavior**
Successful deployment of _preview_ environment.

**Screenshots**
Not working, as of today: 
![image](https://user-images.githubusercontent.com/10069144/226651408-c46ed7ab-1799-485d-a8e0-442280de9244.png)

Same branch, working, as of 18 days ago:
![image](https://user-images.githubusercontent.com/10069144/226652445-64546f8f-e6d4-4f91-b5fb-f84829839e8f.png)

**Device info (if applicable):**
 - N/A (whatever the Github hosted agent runs)

**Additional context**
I've tried pinning the action version to a commit from a known good time, but it seems to have no effect, leading me to think that the problem is further upstream.
