### ISSUE TITLE
Unable to view config settings of static web app

### ISSUE THREAD

**Issue by ilantom** [Azure/static-web-apps#1121]
**Describe the bug**

I have deployed a static web app with some config settings:

```
resource staticWebApp 'Microsoft.Web/staticSites@2022-03-01' = {
  name: '${solutionAbbreviation}-ui-${environmentAbbreviation}'
  location: location
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    allowConfigFileUpdates: true
    branch: branch
    buildProperties: {
      appLocation: 'UI/web-app'
      skipGithubActionWorkflowGeneration: true
    }
    enterpriseGradeCdnStatus: 'Disabled'
    provider: 'DevOps'
    repositoryUrl: repositoryUrl
    stagingEnvironmentPolicy: 'Disabled'
  }
}

resource staticWebAppAppSettings 'Microsoft.Web/staticSites/config@2022-03-01' = {
  parent: staticWebApp
  kind: 'config'
  name: 'appsettings'
  properties: {
    REACT_APP_AAD_UI_APP_CLIENT_ID: 'xxx'
    REACT_APP_AAD_API_APP_CLIENT_ID: 'xxx'
    REACT_APP_AAD_APP_TENANT_ID: 'xxx'
    REACT_APP_AAD_APP_SERVICE_BASE_URI: 'https://xxx-webapi.azurewebsites.net'
  }
}
```

YAML:

```
- task: AzureStaticWebApp@0
    name: DeployStaticWebApp
    displayName: Deploy Static Web App
    inputs:
      app_location: 'web-app'
      cwd: '${{ parameters.root }}/webapp_package'
      azure_static_web_apps_api_token: $(deployment_token)
```

I'm unable to view config settings of the app after deployment:

![image](https://user-images.githubusercontent.com/6519992/226714422-1e05794e-515b-4a3c-beb6-ee66255b113f.png)

I don't see 'Contributor' role for this static web app resource. What role or what least permission is required to access config settings of static web app?
