### ISSUE TITLE
Cannot deploy from BitBucket to Azure Static Web App

### ISSUE THREAD

**Issue by mikeysteele** [Azure/static-web-apps#1145]
I'm trying to deploy the sample Angular App from Bitbucket using the following steps:
https://learn.microsoft.com/en-us/azure/static-web-apps/bitbucket?tabs=angular

I've created the Static App on Azure, cloned the [repo](https://github.com/staticwebdev/angular-basic) into bitbucket, created the pipeline, and got the deployment token from Azure and added it as a variable.

When I try and run the pipeline, I get the following error

 ```
DeploymentId: 17e1faf3-f071-41dc-9f35-d9d465c1a8a2
App Directory Location: '/opt/atlassian/pipelines/agent/build' was found.
Looking for event info
Could not get event info. Proceeding
Failed to contact content server, stopping...
An unknown exception has occurred
For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```
Here is the bitbucket-pipeline.yml
```
pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/dist/angular-basic'
                API_TOKEN: $deployment_token​
```
