### ISSUE TITLE
Build project without deploying

### ISSUE THREAD

**Issue by bh3605** [Azure/static-web-apps#1152]
**Is your feature request related to a problem? Please describe.**
The underlying build process automatically detects which version of nodejs to install. It would be amazing if you guys created a new task that only had this step so I could use the build artifact in a post processing step.

**Describe the solution you'd like**
Be able to build my angular projects without having to specify the nodejs version.

**Describe alternatives you've considered**
Specify the nodejs version

**Additional context**
This picture shows oryx detecting the correct frameworks and figures out which nodejs version to install. It would be a huge benefit to be able to utilize this process so I no longer have to specify the nodejs version in other pipelines that aren't an azure static web app.
![image](https://user-images.githubusercontent.com/3073436/235762934-a393fd12-7ef2-47d1-956c-58b6dd655773.png)

**Comment by mishapos** [comment]
Hi, Static Web Apps uses [microsoft/oryx](https://github.com/microsoft/Oryx/blob/main/README.md#supported-platforms) under the hood to automate the detection and building of projects. You can use this as well to generate a build artifact to be used later in your pipeline. Here is an example snippet you can add to your GitHub workflow:

```
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/oryx/build:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/repo
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Build With Oryx
        run: |
          ls /repo
          oryx build /repo/app --output /repo/output
          ls /repo/output
```

This snippet tells GitHub to use the `mcr.microsoft.com/oryx/build:latest` image, mount the repo folder location into the docker container, checkout the repo, and then call the oryx CLI within the container to automatically detect the platform and build a runnable artifact. 

You can read more about how to use Oryx here: https://github.com/microsoft/Oryx/blob/main/README.md#supported-platforms

Hope this helps!

**Comment by bh3605** [comment]
The code below is Azure Devops equivalent.
```
jobs:
- job: container_test_job
  pool:
    vmImage: ubuntu-latest
  container:
    image: mcr.microsoft.com/oryx/build:latest
    env:
      NODE_ENV: development
    ports:
    - 80
  steps:
  - checkout: self
  - task: CmdLine@2
    inputs:
      script: |
        oryx build $(Pipeline.Workspace)/s --output $(Build.ArtifactStagingDirectory)
```
incorporated as a stage job
```
pool:
  vmImage: ubuntu-latest

resources:
  containers: 
  - container: oryx
    image: 'mcr.microsoft.com/oryx/build:latest'
    env:
      NODE_ENV: development
    ports:
    - 80

stages:
  - stage: Build
    jobs:
    - job: container_test_job
      container: oryx
      steps:
      - checkout: self
      - task: CmdLine@2
        inputs:
          script: |
            oryx build $(Pipeline.Workspace)/s --output $(Build.ArtifactStagingDirectory)
            ls $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        displayName: Publish Build Artifact
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
          ArtifactName: 'drop'
          publishLocation: 'Container'
```
