### ISSUE TITLE
Unable to deploy when using public NPM package on the Github registry

### ISSUE THREAD

**Issue by FinOCE** [Azure/static-web-apps#1189]
**Describe the bug**

My Next.js SWA uses a package that I have published on the Github registry: https://github.com/Semifinals/discussions. I am only using it for the typings.

When I try to run my deployment workflow, I run the following by merging into the `production` branch:

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@semifinals"

      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.mysecrettokenkey }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
```

The first `npm install` that has the `NODE_AUTH_TOKEN` included it works perfectly, but when it tries to run the `Build And Deploy` part it results in the following:

```
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@semifinals/discussions/1.0.2/8f2bbd8d7460db050c9e01b67aed1714565fe465 - authentication token not provided
```

I have tried adding the `NODE_AUTH_TOKEN` to `env` on this part as well but still no luck.

**To Reproduce**

1. Clone my project: https://github.com/Semifinals/website
2. Add Actions environment variable for your SWA
3. Make a push to the `production` branch to trigger the workflow (or just change to a push on main)

**Expected behavior**

The package should be able to be installed by Oryx and then build & deploy the SWA.

**Screenshots**

N/A

**Additional context**

I don't believe there is any difference in them, but I also have a different private repository that is using https://github.com/Semifinals/token which as far as I can tell is made in basically the exact same way as the discussions package. This one DOES successfully build and deploy. It is a React Native app that I have deploying the web build, but the workflow file is practically the exact same:

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@semifinals"

      - run: npm install --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.mysecrettokenkey }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/web-build" # this is here because it's a react native project, not Nextjs
```
