### ISSUE TITLE
The Oryx version used does not detect hugo apps correctly.

### ISSUE THREAD

**Issue by malte610** [Azure/static-web-apps#1219]
**Describe the bug**

The Oryx version 0.2.20230501.1 detects hugo apps with version >0.110.0 not corretly. Either it can not detect hugo at all or if you use the old configuration file name it detects hugo version 0.096.0. 

**To Reproduce**
1. Build and Deploy a hugo app with version >0.110.0 

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SAND_05D4CC603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          HUGO_VERSION: "0.113.0" #this didn't change the behaviour

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SAND_05D4CC603 }}
          action: "close"
```

**Expected behavior**
That it detects and builds the app with the correct version.

**Additional context**

The issue seems to be solved on newer Oryx version: 

https://github.com/microsoft/Oryx/pull/2009 from Oryx Version 20230609.1 on.
