### ISSUE TITLE
dependabot should never create a preview URL

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps#122]
If you have a repo which has dependabot enabled, it sometimes creates PRs.

The first PR will create the Preview URL. But for a SWA this is not desirable. It would be more valuable to be able to use it for my own PR. Otherwise, if I have 10 dependabot PRs, I have to hunt through which one caused the preview URL and close it. Closing it may not be desirable either.

I recommend we find a way to ignore the dependabot PRs.

**Comment by nogic1008** [comment]
As a workaround, My app limited SWA workflow as below.
```yaml
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed' && !contains(github.actor, '[bot]'))
```
[workflow](https://github.com/ddradar/ddradar/blob/master/.github/workflows/azure-static-web-apps-lemon-water-096a66800.yml)
