### ISSUE TITLE
Unable to deply Nuxt 3 site with Universal Rendering

### ISSUE THREAD

**Issue by SSKLCP** [Azure/static-web-apps#1223]
**Describe the bug**

Following this guide to deploy a Nuxt 3 site to a SWA, however trying to use Azure DevOps pipelines rather than Github Actions.

Guide:
https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs
Repo code:
https://github.com/staticwebdev/nuxt-3-starter
Pipeline:
```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-thankful-moss-0b71eae03-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MOSS_0B71EAE03)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: ".output/server" # Api source code path - optional
      output_location: ".output/public" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

After configuring the pipeline and running it I get the error:
```
Failed to find a default file in the app artifacts folder (.output/public). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your deployment configuration file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

![image](https://github.com/Azure/static-web-apps/assets/62546866/1aa88306-5b84-43ea-82bd-ec44a309d8d9)

Should be reproducible following the exact steps of the article, just pointing to Azure DevOps rather than Github. 

Is there a setting that needs to be changed for this to work on a ADO build? Surely it should work the same on either platform?

Let me know if there's a better place to log this issue - I wasn't quite sure where it could go.

**Comment by antoinebidault** [comment]
I'm experimenting the same issue here. With approximately the same configuration:
```yml
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

jobs:
  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-icy-pond-0910a4803-variable-group
    steps:
      - checkout: self
        submodules: true
      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_POND_0910A4803)
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: './' # App source code path
          api_location: './.output/server' # Api source code path - optional
          output_location: './.output/public' # Built app content directory - optional
###### End of Repository/Build Configurations ######

```
I'm having exactly the same error message.
If I disable the SSR on the whole nuxtjs app, then it generates an index.html to the output/public path and it works without the server side API working. But that's not what I've managed.
I've tried on a Github repository and it works perfectly. So it seems to come from the Azure Static App deployment task.

**Comment by InverterOfControl** [comment]
I had the same issue. After digging in the nitro documentation https://nitro.unjs.io/deploy/providers/azure I saw that there is a specific deployment-setting for deploying to azure so after i changed my nuxt.config.(js|ts)
```
export default defineNuxtConfig({
  nitro: {
    preset: "azure"
  },...
```
the deployment worked! 
Hope this helps.

**Comment by thomasgauvin** [comment]
Hey folks, tried to repro and I'm not encountering the errors you mention (see my sample repo, created from the starter that was indicated as failing): https://github.com/thomasgauvin/test-nuxt-3/actions/runs/5593653197/jobs/10227551221 Perhaps there's been a fix on the Nitro side of things that was causing this issue?

@InverterOfControl provides the correct workaround. Nitro uses presets in order to determine how to compile the Nuxt app for the deployment platform. We've worked with the Nitro team in order to ensure zero-config deployments with Static Web Apps, such that Nitro detects when Oryx is building the app for Static Web Apps, and that builds correctly for Static Web Apps. The manual configuration mentioned by @InverterOfControl will always work, and can be used to specify in case of another issue like this

**Comment by antoinebidault** [comment]
Thank you @InverterOfControl 
It works for me !

**Comment by thomasgauvin** [comment]
I'm going to be renaming this issue, as it applies specifically to Azure DevOps, so we can better track it

**Comment by DamianGlowala** [comment]
I am trying to deploy an already built Nuxt 3 app with the following structure:
```
- staticwebapp.config.json
- .output
  - public
  - server
  - nitro.json
```

... and the following configuration:
```
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: ...'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)\deployment'
    app_location: /
    output_location: .output/public
    api_location: .output/server
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
```

What am I missing (structure and/or configuration wise) to make this work? Currently I am receiving the following output:
```
2024-03-05T15:18:50.0430590Z Verbose logging enabled
2024-03-05T15:18:50.0877240Z Try to validate location at: '/working_dir'.
2024-03-05T15:18:50.0890626Z Build timeout not specified, defaulting to 15 minutes
2024-03-05T15:18:50.0891672Z App Directory Location: '/' was found.
2024-03-05T15:18:50.0892501Z Try to validate location at: '/working_dir/swa***db***connections'.
2024-03-05T15:18:50.0899711Z Looking for event info
2024-03-05T15:18:50.0910244Z Could not get event info. Proceeding
2024-03-05T15:18:50.5557834Z Skipping step to build /working_dir with Oryx
2024-03-05T15:18:50.5573940Z Found staticwebapp.config.json file: 'staticwebapp.config.json'
2024-03-05T15:18:50.5583800Z Didn't find Oryx manifest file under location: /9899dff2***df6f***4d68***93ad***0091e9bd66af***swa***oryx/app***manifest/oryx***manifest.toml
2024-03-05T15:18:50.5659154Z ##[error]Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
2024-03-05T15:18:50.5660430Z ##[error]If your application contains purely static content, please verify that the variable 'app_location' in your deployment configuration file points to the root of your application.
2024-03-05T15:18:50.5663108Z ##[error]If your application requires build steps, please validate that a default file exists in the build output directory.
2024-03-05T15:18:50.5709009Z ##[error]
```
