### ISSUE TITLE
Unable to deploy nextjs app located in monorepo with yarn workspaces

### ISSUE THREAD

**Issue by georgibakken** [Azure/static-web-apps#1226]
**Describe the bug**
I have a monorepo setup with yarn workspaces, based on this [monorepo starter](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito) with nextjs, tamagui and expo.

I want to deploy the nextjs app as a [hybrid app](https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs#hybrid-nextjs-applications-preview) using Azure Static Web App. 

From Oryx I get the following error:
<img width="965" alt="image" src="https://github.com/Azure/static-web-apps/assets/16558100/ba3a3c99-c2c7-440f-8b0d-8682e7920b45">

In the starter repo, they write this for Vercel deployment:
> Deploying to Vercel
> - Root: ./apps/next 
> - Install command to be yarn set version berry && yarn install
> - Build command: leave default setting
> - Output dir: leave default setting

I have tried similar setup in the GitHub workflow file

```
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_DUNE_0C5557303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: 'apps/web' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          TAMAGUI_TAGET: 'web'
          PRE_BUILD_COMMAND: 'yarn set version berry && yarn install'
```
**Note:** In my monorepo, the nextjs app is under `apps/web` and not `apps/next` as the monorepo starter.

**To Reproduce**
1. Create the [starter](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito)
2. Setup [Deploy to Azure Static Web App](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid)
3. Configure the workflow 

**Expected behavior**
From what I can see and understand, Oryx doesn't know about the .lock file from the root. I try to go to the root and run `yarn build` as the [build command](https://github.com/tamagui/tamagui/blob/master/starters/next-expo-solito/apps/next/package.json#L7) in the starter repo does. 

I also tried to sneak in `yarn install` in the build script, which gave this:
<img width="1375" alt="image" src="https://github.com/Azure/static-web-apps/assets/16558100/34385ba2-e4c8-4aba-b325-9275c46e22c6">

I have seen some other issues [regarding yarn workspaces](https://github.com/Azure/static-web-apps/issues/542), but that seems to be related to the `api`. Am I configuring the deployment correctly?
