### ISSUE TITLE
Staticwebapp.config.json never found

### ISSUE THREAD

**Issue by lhohn** [Azure/static-web-apps#1229]
**Describe the bug**
Adding a staticwebapp.config.json always results in not found error. I added a staticwebapp.config.json into the assets folder
<img width="157" alt="image" src="https://github.com/Azure/static-web-apps/assets/29137854/f61922b9-a9cb-4b0d-a172-f31467a094c0">
But the build alsways failes with a error saying that the staticwebapp.config.json could not be found
My Actionfile looks like this:
```yaml
 steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secret }}
          repo_token: ${{ secret  }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: "npm run build-prod"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/myApp" # Built app content directory - optional
          config_file_location: "/asstets"
          ###### End of Repository/Build Configurations ###### 
```

And the assets folder is added in the angular.json:
```json
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
```
Already tried other config_file_location like "./dist/myApp", "./dist/myApp/assets", "/asstets", "./assets"
<img width="353" alt="image" src="https://github.com/Azure/static-web-apps/assets/29137854/841a28ab-c522-4322-b321-e54f57040987">
Building the angular app locally results into these artifacts:
<img width="189" alt="image" src="https://github.com/Azure/static-web-apps/assets/29137854/d0518d87-306f-4bcd-9a5c-4fa2951d28a8">

staticwebapp.config.json:
```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["*.{css,scss,js,png,gif,ico,jpg,svg}"]
  }
}
```

**Expected behavior**
Successful build with `config_file_location: "/assets"`
