### ISSUE TITLE
How to pass custom environment variables to SWA Build

### ISSUE THREAD

**Issue by pcanas** [Azure/static-web-apps#1243]
I would like to pass a custom environment variable to be by my React-based PWA. So far, this is how the app looks:

![Captura de pantalla 2023-08-10 a las 8 39 42](https://github.com/Azure/static-web-apps/assets/32467089/ac9bae47-df71-4a72-b49f-bf7defcb338b)

I followed [this tutorial](https://www.azurestaticwebapps.dev/blog/configuring-swa) and try to add `CUSTOM_ENV` and `PPP` in 2 different ways:
* `CUSTOM_ENV` was added as an environment variable from the Azure Portal:
<img width="789" alt="Captura de pantalla 2023-08-10 a las 8 41 47" src="https://github.com/Azure/static-web-apps/assets/32467089/22c8cf71-5aa6-4309-b02b-eb9cee49ee78">

* `PPP` was added from my Github Action:

```
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_SMOKE_0B4D0EC03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
        env: # Add environment variables here
          PPP: ppp
```

None of the methods work, as you can see from the following screenshot, `process.env` does not contain neither variable:

<img width="1269" alt="Captura de pantalla 2023-08-10 a las 8 46 02" src="https://github.com/Azure/static-web-apps/assets/32467089/b45f11a5-0fda-4cd8-899e-4685768f576d">

Am I missing anything? How can I pass custom environment variables?
