### ISSUE TITLE
Bitbucket pipeline failed on 'npm install --unsafe-perm'

### ISSUE THREAD

**Issue by franapel** [Azure/static-web-apps#1257]
I'm trying to deploy a SWA with Nextjs and Bitbucket repository, but an error appears when is running 'npm install --unsafe-perm' in the pipeline.
![image](https://github.com/Azure/static-web-apps/assets/86159135/405ee0da-bde4-4fb5-95c2-b87726ce4f3b)

We use pnpm to build and run the project so I think that may be the problem.

This is the YAML file that I'm using:
```
image: atlassian/default-image:3

pipelines:
  default:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/.next'
                API_TOKEN: $deployment_token
                VERBOSE: 'true'
```

Ideally I want to set the commands to build the application. Is there any way?
