### ISSUE TITLE
Error: Request is missing the pull request id.

### ISSUE THREAD

**Issue by jessebs** [Azure/static-web-apps#1258]
**Describe the bug**
I'm using the automatically generated SWA Gihub actions on pull request closing and am getting the following error:

```
The content server has rejected the request with: BadRequest
Reason: Request is missing the pull request id.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

My workflow file looks like:

```
name: Close Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  close_pull_request_job:
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.MY_TOKEN }}
          action: "close"
```

The staging deployment is successfully deleted from Azure even though I receive the error.
