### ISSUE TITLE
Static Web App deployment fails - No matching static site was found or the api key was invalid

### ISSUE THREAD

**Issue by dgard1981** [Azure/static-web-apps#126]
I have created a Static Web App from the portal, but when I create a PR to run the action I see an error -

```
The content server has rejected the request with: BadRequest
Reason: No matching static site was found or the api key was invalid.
```

I have deleted the Static Web App and recreated it, and the issue remains.

The Static Web App was created against the 'master' branch, and I have copied the action to a feature branch that I am working on. From the 'Environments' tab it says "Staging environments are automatically created when a pull request is generated", so I was expecting a Stating environment to be created.

Here is the GitHub action that was created. I have slightly altered the `on.push` and `on.pull_request` properties to reflect my desired triggers.

In my case the static website is truly static, so the optional `api_location` and `app_artifact_location` properties have been commented out.

Please note that commits to 'master' do result in a successful deployment to the production environment - it only seems to be the staging environments that have issues.

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'assets/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**'
      - '!master'
    paths:
      - 'assets/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_SMOKE_061101503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/assets" # App source code path
          ### api_location: "api" # Api source code path - optional
          ### app_artifact_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_SMOKE_061101503 }}
          action: "close"
```
