### ISSUE TITLE
Azure DevOps Pipeline (with Next.js)  Fails With 2Errors: "The process '/usr/bin/bash' failed with exit code1" AND "The content server has rejected the request with: BadRequest Reason: The size of the function content was too large. The limit for this Static Web App is 104857600 bytes."

### ISSUE THREAD

**Issue by aktsmm** [Azure/static-web-apps#1277]
**Describe the bug**

**To Reproduce**
1. Check in a code change.
2. Push to DevOps repo
3. Kick off build pipeline

**Error Message**
#### Issue１．
```
The content server has rejected the request with: BadRequest
Reason: The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.
```
#### Issue２．
```
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
```

**Azure Pipelines YAML File**
```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

# deploy Static Web Apps
  - task: AzureStaticWebApp@0
    inputs:
        azure_static_web_apps_api_token: $(deployment_token)
        app_location: ''
        api_location: 'api'
        output_location: '.next'
        api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
    env:
        AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
        AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
        AZURE_OPENAI_DEPLOYMENT_ID: $(AZURE_OPENAI_DEPLOYMENT_ID)
        CUSTOM_BUILD_COMMAND: 'chown -R "$(whoami)" $SOURCE_DIR && npm install --unsafe-perm && npm run build && npm run build:azure && apt-get install -y  apt-utils'
```

**my private test repository**
https://dev.azure.com/handson-aktsmm/_git/aktsmm-aoai-hands-on
(if you request me, I will accept you )

**Screenshots**
![2023-09-15_01h09_00](https://github.com/Azure/static-web-apps/assets/71251920/2de726b1-7d04-41e1-9610-f5006df9d294)

**Additional context**
I have seen many similar GitHub issues , but I could not fix this in my test lab.

For example : 
https://github.com/Azure/static-web-apps/issues/776
https://github.com/Azure/static-web-apps/issues/909#issuecomment-1320077142
https://github.com/Azure/static-web-apps/issues/214

**ref**
I tried this inspiring this blog
Sorry for Japanese blog　：　https://zenn.dev/yusu29/articles/azure_openai_handson

It may be bug?

**Comment by Joelith** [comment]
I (and many others it seems) have a similar issue. After a lot of debugging I think it's because the static web apps build action seems to upload the node_modules as part of the build process. I have a project with hundreds of megabytes of node_modules so I was running into limits. 

Resolution:
- Add a step to install your node modules and then to build your package. Eg: (depending on your build process)
```
  - name: Install
    run: yarn install --cwd ${GITHUB_WORKSPACE}/apps/portal 
    env:
      GIT_TOKEN: ${{secrets.GIT_TOKEN}}
      BIT_TOKEN: ${{secrets.BIT_TOKEN}}
  - name: Build
    run: yarn --cwd ${GITHUB_WORKSPACE}/apps/portal run build 
    env:
      GIT_TOKEN: ${{secrets.GIT_TOKEN}}
      BIT_TOKEN: ${{secrets.BIT_TOKEN}}
```
- Then add another step to clean up your node modules
```
  - name: rm node
    run: rm -rfv $GITHUB_WORKSPACE/apps/portal/node_modules
```
- And then finally tell the Build and Deploy step not to build the app anymore (as you did it above). To do this add `skip_app_build: true` to the final step

Doing this allowed me to finally upload my application. I think this is a bug in the build step on Azure's behalf, as it shouldn't be including the node_modules into the package or as part of the file size calculation

**Comment by aktsmm** [comment]
joelith -san 
THnak you bery much, I retried one more with inspiring your comment.
My environment is not github but azure devops :)
So I modified the code you gave , finally it well done !!Success!!

ref:) This is the modified code in Azure Devops

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndDeploy
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  # install node module and buid
  - script: |
      echo "Installing dependencies"
      yarn install --cwd $(Agent.BuildDirectory)/s/YourProjectName/apps/portal
    displayName: 'Install'
    env:
      GIT_TOKEN: $(BIT_TOKEN)
      BIT_TOKEN: $(GIT_TOKEN)

  - script: |
      echo "Building"
      yarn --cwd $(Agent.BuildDirectory)/s/YourProjectName/apps/portal run build
    displayName: 'Build'
    env:
      GIT_TOKEN: $(BIT_TOKEN)
      BIT_TOKEN: $(GIT_TOKEN)

  # deploy Azure Static Web Apps
  - task: AzureStaticWebApp@0
    inputs:
        azure_static_web_apps_api_token: $(deployment_token)
        app_location: '/'
        api_location: ''
        output_location: '.next'
        api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
        skip_app_build: true
    env:
        AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
        AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
        AZURE_OPENAI_DEPLOYMENT_ID: $(AZURE_OPENAI_DEPLOYMENT_ID)
        CUSTOM_BUILD_COMMAND: "chown -R \"$(whoami)\" $SOURCE_DIR && npm install --unsafe-perm && npm run build && npm run build:azure && apt-get install -y apt-utils"

  # remove node_modules

  - script: |
      echo "Removing node_modules directory"
      rm -rfv $(Agent.BuildDirectory)/s/YourProjectName/apps/portal/node_modules
    displayName: 'Remove node_modules'

```
