### ISSUE TITLE
static-web-apps-deploy uses Docker with root

### ISSUE THREAD

**Issue by mohamedmansour** [Azure/static-web-apps#1285]
This is the weirdest thing that is happening, when using static-web-apps-deploy the `api` folder in self-hosted github runner, is always `root`, this happens when I don't skip the build for static-web-apps-deploy. 

My monitoring the syscalls in the Github Action, 

```
time->Wed Sep 20 22:12:57 2023
type=PROCTITLE msg=audit(1695273177.138:52877): proctitle=6D6B646972002D70002E6F7279785F70726F645F6E6F64655F6D6F64756C6573
type=PATH msg=audit(1695273177.138:52877): item=1 name=".oryx_prod_node_modules" inode=23231831 dev=fd:01 mode=040755 ouid=0 ogid=0 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1695273177.138:52877): item=0 name="/github/workspace/api" inode=23231945 dev=fd:01 mode=040755 ouid=1000 ogid=1000 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1695273177.138:52877): cwd="/github/workspace/api"
type=SYSCALL msg=audit(1695273177.138:52877): arch=c000003e syscall=83 success=yes exit=0 a0=7fff41c1f8f5 a1=1ff a2=0 a3=fffffffffffffd8c items=2 ppid=1619239 pid=1619685 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mkdir" exe="/bin/mkdir" subj=docker-default key="api-watch"
```

The uuid and guid is 0 which is root,  and `ls -al` the solution:
```
drwxr-xr-x 12 mmansour mmansour   4096 Sep 20 22:12 .
drwxr-xr-x  3 mmansour mmansour   4096 Sep 20 21:32 ..
drwxr-xr-x  7 root     root       4096 Sep 20 22:12 api
drwxr-xr-x  4 mmansour mmansour   4096 Sep 20 22:12 dist
-rw-r--r--  1 mmansour mmansour     45 Sep 20 22:12 .env-DEFAULT
-rw-r--r--  1 mmansour mmansour    684 Sep 20 22:12 .eslintrc.json
drwxr-xr-x  8 mmansour mmansour   4096 Sep 20 22:13 .git
drwxr-xr-x  3 mmansour mmansour   4096 Sep 20 22:12 .github
-rw-r--r--  1 mmansour mmansour     39 Sep 20 22:12 .gitignore
drwxr-xr-x  5 mmansour mmansour   4096 Sep 20 22:12 infra
drwxr-xr-x 12 mmansour mmansour   4096 Sep 20 22:12 node_modules
-rw-r--r--  1 mmansour mmansour   2498 Sep 20 22:12 package.json
-rw-r--r--  1 mmansour mmansour 215312 Sep 20 22:12 pnpm-lock.yaml
-rw-r--r--  1 mmansour mmansour     86 Sep 20 22:12 .prettierrc
drwxr-xr-x  2 mmansour mmansour   4096 Sep 20 22:12 public
-rw-r--r--  1 mmansour mmansour   1714 Sep 20 22:12 README.md
drwxr-xr-x  2 mmansour mmansour   4096 Sep 20 22:12 screenshots
drwxr-xr-x  7 mmansour mmansour   4096 Sep 20 22:12 src
-rw-r--r--  1 mmansour mmansour    468 Sep 20 22:12 tsconfig.json
drwxr-xr-x  2 mmansour mmansour   4096 Sep 20 22:12 .vscode
```

It is chowning all the `/api` folder to be owned by root:
```
----
time->Wed Sep 20 22:12:57 2023
type=PROCTITLE msg=audit(1695273177.138:52877): proctitle=6D6B646972002D70002E6F7279785F70726F645F6E6F64655F6D6F64756C6573
type=PATH msg=audit(1695273177.138:52877): item=1 name=".oryx_prod_node_modules" inode=23231831 dev=fd:01 mode=040755 ouid=0 ogid=0 rdev=00:00 nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(1695273177.138:52877): item=0 name="/github/workspace/api" inode=23231945 dev=fd:01 mode=040755 ouid=1000 ogid=1000 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1695273177.138:52877): cwd="/github/workspace/api"
type=SYSCALL msg=audit(1695273177.138:52877): arch=c000003e syscall=83 success=yes exit=0 a0=7fff41c1f8f5 a1=1ff a2=0 a3=fffffffffffffd8c items=2 ppid=1619239 pid=1619685 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mkdir" exe="/bin/mkdir" subj=docker-default key="api-watch"
----
```
How can we tell that Github Action to run as a certain user and not root? (my alias is mmansour in msft if we can talk there too)

**Comment by mohamedmansour** [comment]
I tried doing this https://docs.docker.com/engine/security/userns-remap/, so that when `root` writes back to the volume that was mounted in docker run, it will use my local username `mmansour`, but the logs spit out.

```

Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v16.20.2

Using Npm version:
8.19.4
mkdir: cannot create directory ‘.oryx_prod_node_modules’: Permission denied


---End of Oryx build logs---
Oryx has failed to build the solution.

```

**Comment by mohamedmansour** [comment]
I found the documentation:
https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user

```
Docker actions must be run by the default Docker user (root). Do not use the USER instruction in your Dockerfile, because you won't be able to access the GITHUB_WORKSPACE directory. For more information, see "[Variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables)" and [USER reference](https://docs.docker.com/engine/reference/builder/#user) in the Docker documentation.
```
I need to run the action as root so, not as a different user.

**Comment by mohamedmansour** [comment]
Unfortunately we cannot run self hosted github actions as root, it doesn't allow you. So this is a blocker for self hosted builds, that we cannot run `static-web-apps-deploy` action since it requires it to be root since it uses docker and overwrites the user files and cannot clean it up since it lost its access.

**Comment by thomasgauvin** [comment]
Oryx will always use the root user to build the project. If this is a blocker for your configuration, you could consider configuring your own build and using the staticappsclient image to deploy only

**Comment by mohamedmansour** [comment]
> Oryx will always use the root user to build the project. If this is a blocker for your configuration, you could consider configuring your own build and using the staticappsclient image to deploy only

Isn't that a problem though? Why would oryx rewrite itself to the same system volume? Github Action Runners cannot run in `root` and once oryx runs it corrupts the entire `_work` directory.

**Comment by mohamedmansour** [comment]
Hey @thomasgauvin the core issue is `oryx` where it reuses the same volume that was mounted in the docker image causing this overwrite of files on disk, Is there anyone that can help?  Or am I forced to create an unmanaged NodeJS API?

**Comment by thomasgauvin** [comment]
Hi @mohamedmansour, I'll check in with our engineering team about the issue you're describing. If you cannot use Oryx due to root user restrictions, you can use the StaticSitesClient only to deploy and avoid building with Oryx by using the skip_app_build and skip_api_build configuration parameters as described in our docs: https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions

The example you shared above does something similar, but by using the SWA CLI (the SWA CLI uses the StaticSitesClient under the hood). It should work, and will not use Oryx to build the project. You will have to build the project separately.

**Comment by Luiz-Monad** [comment]
I had the same problem with this configuration on *Azure Devops*
```yaml
trigger:
  branches:
    include:
      - master

variables:
  - group: config

steps:

  - task: AzureStaticWebApp@0
    displayName: 'Build Static Web Site'
    inputs:
      azure_static_web_apps_api_token: '$(deployment_token)'
      verbose: true
      workingDirectory: '$(Build.SourcesDirectory)'
      app_location: '.'
      api_location: './build/server'
      output_location: './build/static'
      app_build_command: ''
      api_build_command: ''
      skip_app_build: false
      skip_api_build: true
    env:
      PRE_BUILD_COMMAND: npm install -g pnpm
      CUSTOM_BUILD_COMMAND: pnpm install && pnpm build && echo

  - task: Bash@3
    displayName: 'Clean untracked files'
    condition: always()
    inputs:
      targetType: 'inline'
      script: |
        sudo chown AzDevOps:AzDevOps -R "$(Build.SourcesDirectory)"
        sudo git clean -ffdx
        sudo docker container prune -f
```

I had to basically delete myself the files left as a root, otherwise the agent can't be reused. That's bad because it is not an expected behavior.
