### ISSUE TITLE
The content server has rejected the request with: InternalServerError

### ISSUE THREAD

**Issue by Psym0n** [Azure/static-web-apps#1293]
All our SWA deployments have been failing since 20:02 GMT+2
We had our last successful deploy at 18:21 GMT+2 
We initially thought it was a temporary hiccup from the deployment service in Azure (I've experienced it before), but it has persisted through ~ 10 attempts now.

The first two failed deployment ended with the following error message:
(deployment id `693bfcef-cf00-4432-a2c5-57913935cdfc` & `7ed4e98b-e479-4922-ada9-e0a7c981daaa`)
```
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.0434742(s)
Status: InProgress. Time: 19.1154267(s)
Status: InProgress. Time: 38.1819201(s)
Status: InProgress. Time: 63.2775741(s)
Status: InProgress. Time: 78.3364773(s)
Status: InProgress. Time: 103.4328175(s)
Status: InProgress. Time: 118.4710217(s)
An unknown exception has occurred
```

All subsequent deployments failed with the following error:
(example of deployment ids:  `2d7f94ad-81cc-4fb0-8643-06251f00a8b4`, `f2e99a98-f7a4-4368-9148-82fb11f9b4e9`, `23c60ca2-ffab-4beb-9bb7-77ac653b050`)
```
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Copying 'staticwebapp.config.json' to build output
No Api directory specified. Azure Functions will not be created.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: InternalServerError
Reason: An unexpected error has occurred. Please try again later.
```

We are deploying through Azure DevOps Pipelines. We haven't made any changes to the SWA deployment in quite some time.
We deploy Bring Your Own Functions as a seperate step and then deploy our SWA frontend. We have done this for more than a year now.

The SWA Frontend is deployed using the following yaml task:
```
- task: AzureStaticWebApp@0
    name: DeployStaticWebApp
    displayName: 'Deploy Frontend'
    inputs:
      app_location: '<build-folder-here>'
      api_location: ''
      skip_app_build: true
      config_file_location: '<folder-here>'
      azure_static_web_apps_api_token: ${{ parameters.deploymentToken }}
```

Let me know if more information is required.
