### ISSUE TITLE
Files missing in envirionment if also present in other environment deployed later.

### ISSUE THREAD

**Issue by jonasgrunert** [Azure/static-web-apps#1302]
**Describe the bug**

We have two environments in our Azure Static Web `dev` and `prod` (which is the default environemnt). Both are linked to a respective slot on a Functions App we brought along. Deployment and linking worked perfectly. The problem arises if we  deploy the changes using our Github CI/CD Pipeline to only "dev". Afterwards files present in `dev` and `prod` are not available anymore on `prod`. This leads to severe problems as we rely on static assets for most of our UI.

**To Reproduce**
1. Create a static Web App and create a slot
2. Deploy once to both environments
3. Afterwards change a file and deploy only to dev
4. The files on prod which are also on dev should be missing

# The reproducible example does not lead to the same outcome
### Github Action Workflow
```yaml
name: Deploy Node.js project to Azure Static Web App

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Azure Web App to Dev
        uses: Azure/static-web-apps-deploy@v1
        id: deploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "." # App source code path relative to repository root
          skip_app_build: true
          deployment_environment: dev

      - name: Deploy Azure Web App to Prod
        uses: Azure/static-web-apps-deploy@v1
        id: deployprod
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "." # App source code path relative to repository root
          skip_app_build: true
        if: ${{ startsWith(github.ref_name, 'v') }}
```
### Static Web App Config
```json
{ "trailingSlash": "auto" }
```
### Reproducible Repo
[repo](https://github.com/jonasgrunert/azure-web-app-missing-file-repro)
### Links to deployment
[Dev](https://purple-river-0ac87c803-dev.westeurope.4.azurestaticapps.net/missing.html)
[Prod](https://purple-river-0ac87c803.4.azurestaticapps.net/missing.html)

**Expected behavior**
I would expect a deplyoment to dev to not affect the prod deployment.

**Additional context**
While I included a repsoitory for reproduction the main problem lies in another repo with a build setup and additional functions in the backend involved.
