### ISSUE TITLE
deployment_token provided was invalid in bitbucket

### ISSUE THREAD

**Issue by madilkha** [Azure/static-web-apps#1309]
Hello, I want to deploy to azure static web app using bitbucket pipeline. I am getting:

**

> Verbose logging enabled
> deployment_token provided was invalid.
> An unknown exception has occurred
> Failed to record upload telemtry.

**

The pipeline I am using is:
```
pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/build'
                API_TOKEN: $deployment_token
```

This error is reporting since two days. I varified the token many times and reset as well but no success.

Thanks
