### ISSUE TITLE
DeploymentId: ea90bd67-9731-4979-b3d8-6301df8ee761 deployment_token provided was invalid.

### ISSUE THREAD

**Issue by njokdan** [Azure/static-web-apps#1325]
I have created a new project and a new static web app on azure following the below link tutorial (tried both Vanilla and React) and I have the below issue.
https://learn.microsoft.com/en-us/azure/static-web-apps/gitlab?tabs=vanilla-javascript

Here are the logs:

Using docker image sha256:50ce98efe7fa10fb56a726a6101cbc55c606f0940175fabc8474e0420bab62d6 for registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy with digest [registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy@sha256:0eaf1aadc1d2067801287ed82241f053991c634299c03c9a7c6242d2418f0a26](mailto:registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy@sha256:0eaf1aadc1d2067801287ed82241f053991c634299c03c9a7c6242d2418f0a26) ...
DeploymentId: ea90bd67-9731-4979-b3d8-6301df8ee761
deployment_token provided was invalid.
An unknown exception has occurred
For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

Regards,

**Comment by berry807** [comment]
I have the same issue and there are already 3 similar issues open but still no update on this. I have 2 environments (test and production). Production works as it always has, but now I have added test with a new deployment token and this one does not work.

- [https://github.com/Azure/static-web-apps/issues/1314](https://github.com/Azure/static-web-apps/issues/1314)
- [https://github.com/Azure/static-web-apps/issues/1309](https://github.com/Azure/static-web-apps/issues/1309)
- [https://github.com/Azure/static-web-apps/issues/1306](https://github.com/Azure/static-web-apps/issues/1306)

**Comment by oespn** [comment]
I'm experiencing the same issue.    
Comparing the YAML side-by-side from another project that has been working for over 6 months and I can't see any reason why this new one would be failing....   Tried re-generating the token.  Tried overriding the token in various places.   No go!

For anyone playing along: I also tried directly entering into the Yaml (it's a private Repo and I can always invalidate the token).   This also fails. So it seems like there is an incompatibility between the token from azure and bitbucket.   

I do most of my work in bitbucket & azure so this issue is going to start being a real problem soon unless it's resolved.  
Keep us posted!

**Comment by JuanDaniel** [comment]
Hi everyone, 

I have the same bug, I made a _**bitbucket-pipelines.yml**_ to deploy a React app to Azure static web apps from Bitbucket and it fail when try to get a variable API_TOKEN from **_$deployment_token_** added previously.

I made several test even paste directly the value and it not work. 

![pipelines error](https://github.com/Azure/static-web-apps/assets/2273084/c371e767-e049-4c2f-a893-493a74e3a2f2)

I reported this issue to Bitbucket support and they responsed:

> This pipe supported by Microsoft team, and seems like they stopped to maintain it:

> This sample is provided "as is" and is not supported. Likewise, no commitments are made as to its longevity or maintenance. To discuss this sample with other users, please visit the Azure DevOps Services section of the Microsoft Developer Community: https://developercommunity.visualstudio.com/spaces/21/index.html.

I contacted to Microsoft Developer Community support but have had no response so far.

Here my pipelines:
```
image: node:18

pipelines:
  default:
   - step:
       name: Build
       caches:
         - node
       script:
         - npm install
         - npm run lint
         - npm run build
   - step:
     name: Deploy to baamer.treegram.fr
     deployment: develop
     script:
       - pipe: microsoft/azure-static-web-apps-deploy:main
         variables:
           APP_LOCATION: '$BITBUCKET_CLONE_DIR'
           OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/dist'
           SKIP_APP_BUILD: 'true'
           API_TOKEN: $deployment_token
```

**Comment by bomanden** [comment]
> oespn

Experincing the same as @oespn , old project working fine - new one same sittings what ever I tried I get the invalid deployment_token , even if I name the variable $API_TOKEN. 
Hopefully someone will be able to crack this soon....

**Comment by cjk7989** [comment]
Hi all, the image staticwebapps.azurecr.io/bitbucket-deploy:stable (imported by [microsoft / azure-static-web-apps-deploy / pipe.yml — Bitbucket](https://bitbucket.org/microsoft/azure-static-web-apps-deploy/src/main/pipe.yml)) used to deploy swa was out-of-date. A new image has been pushed and verified. Could you try to deployment again?

The same issue on Gitlab will also be fixed later.

**Comment by thomasgauvin** [comment]
Thanks for the confirmation @berry807. Given the fix has rolled out and we've gotten confirmation that this fixes the issue, I'll be closing this issue. All, feel free to reopen/open a separate issue if a different issue pops up!

**Comment by JuanDaniel** [comment]
Hi @thomasgauvin I confirm to that the issue is solved, but in my case when I try to execute my pipeline over Bitbucket I have now this new issue:

![image](https://github.com/Azure/static-web-apps/assets/2273084/1854226d-ecb1-40df-91f3-e56369127793)

Here my pipelines:

```
image: node:18

pipelines:
    default:
        - step:
              name: Build
              caches:
                  - node
              script:
                  - npm install
                  - npm run lint
                  - npm run build
        - step:
              name: Deploy to baamer.treegram.fr
              deployment: develop
              script:
                  - pipe: microsoft/azure-static-web-apps-deploy:main
                    variables:
                        APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                        OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/dist'
                        API_TOKEN: $deployment_token
```

Thanks in advance
