### ISSUE TITLE
SWA build ignoring app_build_command

### ISSUE THREAD

**Issue by stan-spotts** [Azure/static-web-apps#1344]
I have a react app from a contractor and need to run "npm install --legacy-peer-deps"  and tried adding it directly to the workflow yaml file:

```
   with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_BAY_0CC971C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          app_build_command: "npm install --legacy-peer-deps"
          ###### End of Repository/Build Configurations ######
```

I tried adding it to package.json as a script:

```
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "azurebuild": "npm install --legacy-peer-deps"
```

and referencing that:

`app_build_command: "npm run azurebuild"`

and used various iterations of single quotes, double quotes, and both.

Yet in the run results for the build and deploy job, it just keeps calling npm install

```
Running 'npm install'...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-phone-input-mui@2.9.4
npm ERR! Found: react@18.2.0
```

I saw this issue was reported and resolved in the past, so was this broken again, or is there some trick I'm not using?
