### ISSUE TITLE
Support node > 18

### ISSUE THREAD

**Issue by jlous** [Azure/static-web-apps#1354]
In my nextjs project, if I try to mandate the current node version, I get errors that only versions up to 18 are supported. 

Node 18 is entering maintenance mode as we speak (december 2023), and end-of-life in just 5 months.
Nextjs major release are every year, and routinely bump the node requirement past any dead versions.

So this is a ticking bomb. 
Please add support for node 20 and 21

**Comment by rebeccapeltz** [comment]
Same problem.  Here are logs https://github.com/rebeccapeltz/demo-azure-nextjs-client-server-static/actions

**Comment by michaelmccrae** [comment]
I am encountering the same problem when I try to deploy NextJS on static web apps: _You are using Node.js 16.20.2. For Next.js, Node.js version >= v18.17.0 is required._

**Comment by rafanoronha** [comment]
👍

**Comment by thomasgauvin** [comment]
Thanks all for the feedback on this, we'll be looking into this!

**Comment by thomasgauvin** [comment]
Hi folks, to be clear, this is referring to the runtime Node version being the limitation, not the build time Node version, correct?

**Comment by rebeccapeltz** [comment]
Here's the log from a failed build : https://github.com/rebeccapeltz/demo-azure-nextjs-client-server-static/actions/runs/7188649410/job/19578699538#step:4:1

**Comment by rafanoronha** [comment]
Hey @thomasgauvin,

Great news!

On my side, I'm pretty sure this is a runtime limitation indeed.

Looking forward to upgrade two apps into Node 20 🎉

**Comment by rafanoronha** [comment]
Thanks for the update @thomasgauvin 🙏

**Comment by jugalo1713** [comment]
thanks @thomasgauvin  going to the specific node version in package.json solved my issue:

```
"engines": {
    "node": "18.17.1"
  }
```

**Comment by thomasgauvin** [comment]
Thanks folks for the confirmation, let's keep this issue open until Node 20 rolls out!

**Comment by rebeccapeltz** [comment]
Thanks - it's working for me too.  Much appreciated.

**Comment by yannbolliger** [comment]
Do you have an ETA for node 20 support?

**Comment by komayama** [comment]
I followed this next.js documentation. By default, Build tools use Node.js 16 and similar error message.

https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid
![image](https://github.com/Azure/static-web-apps/assets/24888431/7ffafb75-568b-4d85-bb6c-9d6db97bb42c)

**Comment by thomasgauvin** [comment]
@yannbolliger We don't have a timeline to share at this moment, but it's a work item slotted for our next semester

**Comment by CyberProgs** [comment]
for me this one worked 

```
"engines": {
    "node": "18.19.1"
}
```

**Comment by KasperAndersson** [comment]
@thomasgauvin  Do you have a public issue tracker,  where the support for Node 20 can be followed - or any eta for the support to land?

**Comment by marcodali** [comment]
Just add this code block in the **azure-static-web-apps-your-id.yml** file after _actions/checkout@v3_ but before _Build And Deploy_. Final preview:
```
env:
  NODE_VERSION: '20.x'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@latest
```
