### ISSUE TITLE
SWA is only deploying to a staging environment, even after merging PR

### ISSUE THREAD

**Issue by nad-au** [Azure/static-web-apps#1358]
I have a SWA with a custom domain. When I visit the custom domain URL I get `Your Azure Static Web App is live and waiting for your content` and when I view the SWA in the portal, it tells me the status is `waiting for deployment` and also shows `Prepare for production (2/3 completed)`.

In my Actions pipeline the only difference to the ootb template is that I'm building my nuxt3 app myself and so I set `skip_app_build: true` and `skip_api_build`.

When I raise a PR I see the bot message with the staging env url. And the link works and shows my nuxt site. When I merge the PR, the close job runs which uses `action: close` and secondly, the build job runs again. After the build job is completed I get a notification email again that my staging env is ready.

So what am I missing? How do I switch staging into production?

**Comment by nad-au** [comment]
Here's my pipeline

```yaml
name: "Deploy node-votes-2 App"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - "apps/node-votes-2/apps/node-votes-app/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_SUBSCRIPTION: zzz
  APP_RESOURCE_GROUP: zzz
  STATIC_WEB_APP_NAME: zzz

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy App
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.SP_ITOPS_MCS }}

      - name: Get SWA deployment key
        id: get_deployment_key
        uses: azure/CLI@v1
        with:
          azcliversion: 2.54.0
          inlineScript: |
            APIKEY=$(az staticwebapp secrets list --name ${{ env.STATIC_WEB_APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --subscription ${{ env.AZURE_SUBSCRIPTION }} | jq '.properties.apiKey' -r)
            echo "::add-mask::$APIKEY"
            echo "apikey=$APIKEY" >> $GITHUB_OUTPUT

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install yarn
        run: npm install -g yarn

      - name: Build
        working-directory: ./apps/node-votes-2/apps/node-votes-app
        run: |
          yarn install --frozen-lockfile
          yarn build
          cp staticwebapp.config.json .output/public/staticwebapp.config.json

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_deployment_key.outputs.apikey }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: ./apps/node-votes-2/apps/node-votes-app/.output/public
          skip_api_build: true
          api_location: ./apps/node-votes-2/apps/node-votes-app/.output/server
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.SP_ITOPS_MCS }}

      - name: Get SWA deployment key
        id: get_deployment_key
        uses: azure/CLI@v1
        with:
          azcliversion: 2.54.0
          inlineScript: |
            APIKEY=$(az staticwebapp secrets list --name ${{ env.STATIC_WEB_APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --subscription ${{ env.AZURE_SUBSCRIPTION }} | jq '.properties.apiKey' -r)
            echo "::add-mask::$APIKEY"
            echo "apikey=$APIKEY" >> $GITHUB_OUTPUT

      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_deployment_key.outputs.apikey }}
          action: "close"
          app_location: ""
```

**Comment by nad-au** [comment]
FWIW I got it working by swapping out the `Azure/static-web-apps-deploy action` with the SWA CLI.

Add SWA CLI dev dependency: `yarn add @azure/static-web-apps-cli --dev`

Update `package.json`

```json
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "swa": "swa"
  },
```

Then in my pipeline I can deploy to production with:

```bash
yarn swa deploy ./apps/node-votes-2/apps/node-votes-app/.output/public \
  --api-location ./apps/node-votes-2/apps/node-votes-app/.output/server \
  --deployment-token ${{ steps.get_deployment_key.outputs.apikey }} \
  --env production
```

**Comment by nad-au** [comment]
Updated & simplified pipeline using SWA CLI. Note that PR > staging is not required as this is for POC and in any case, we use different subscriptions for dev / stage / prod so temporary environments is not needed.

```yaml
name: "Deploy node-votes-2 App"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_SUBSCRIPTION: zzz
  APP_RESOURCE_GROUP: zzz
  STATIC_WEB_APP_NAME: zzz
  NODE_VERSION: 18

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy App
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.SP_ITOPS_MCS }}

      - name: Get SWA deployment key
        id: get_deployment_key
        uses: azure/CLI@v1
        with:
          azcliversion: 2.54.0
          inlineScript: |
            APIKEY=$(az staticwebapp secrets list --name ${{ env.STATIC_WEB_APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --subscription ${{ env.AZURE_SUBSCRIPTION }} | jq '.properties.apiKey' -r)
            echo "::add-mask::$APIKEY"
            echo "apikey=$APIKEY" >> $GITHUB_OUTPUT

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install yarn
        run: npm install -g yarn

      - name: Build
        working-directory: ./apps/node-votes-2/apps/node-votes-app
        run: |
          yarn install --frozen-lockfile
          yarn build
          cp staticwebapp.config.json .output/public/staticwebapp.config.json

      - name: Deploy
        working-directory: ./apps/node-votes-2/apps/node-votes-app
        run: |
          yarn swa deploy .output/public \
            --api-location .output/server \
            --api-version ${{ env.NODE_VERSION }} \
            --deployment-token ${{ steps.get_deployment_key.outputs.apikey }} \
            --env production
```
