### ISSUE TITLE
Next.js app which only has simple `pages/index.tsx` deploys with no error, but returns 502 error

### ISSUE THREAD

**Issue by jihoobyeon** [Azure/static-web-apps#1360]
**Describe the bug**

I made a simple Next.js App, which uses Yarn 4.0.2
It neither has `pages/api` folder nor `getServerSideProps()` now. I am planning to add those, but not now. Now it has only one React component in `pages/index.tsx` which show some lines of simple text.
I didn't forgot to add `output: 'standalone'` in `next.config.js`.

Then I depolyed it to [my Azure SWA](https://jolly-flower-0b2849210.4.azurestaticapps.net/) via Azure Pipelines.
After some tries, it did deploy successfully. But when I access to my app by web browser, it shows this:
![image](https://github.com/Azure/static-web-apps/assets/77971249/c7254847-e9a7-436b-9f4d-cfd71dec9186)

And when I open console by pressing `F12`, it shows `Failed to load resource: the server responded with a status of 502 ()`.

**To Reproduce**
1. Make a simple Next.js app which uses Yarn ver 2. or later (aka Yarn berry)
2. Deploy it to SWA by Azure Pipelines
3. Access it via any web browser

This is my Azure Pipelines workflow YAML file:
```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-jolly-flower-0b2849210-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FLOWER_0B2849210)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      skip_api_build: true
      output_location: "" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

**Expected behavior**
Just show my text website.

**Screenshots**
Added above

**Device info (if applicable):**
 - OS: Every
 - Browser: Every
 - Version: Every

**Additional context**
None
