### ISSUE TITLE
Unable to overide PR environment with named environment 

### ISSUE THREAD

**Issue by TheoMcCabe** [Azure/static-web-apps#1378]
The workflow i want for deploying my static apps is this 

- creating, pushing, or reopening a pr deploys to a static environment called 'staging'. 

I need it as a static environment so i can add the redirect URL to my auth provider and add the app url to the CORS on my API etc.  I have no use or need for PR numbered environments.

Its not clear to me how i achieve the above. If i run the github action 'like so in a pr 
```
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FOREST_0E0A91310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/"
          api_location: "" 
          output_location: "dist"
          deployment_environment: "staging"
  ```       

PR changes do not deploy to the staging environment - they continue to depoly to a pr environment. It only seems to deploy to staging when the action 'close' is called. However this is only called when the PR is closed. 

The behaviour i want and would expect is hard to achieve. I would expect a named deployment_environment setting to override the PR environments from being triggered at all.

**Comment by MrMossevig** [comment]
We have the the same problem. I would call this a bug, not an enhancement as the behaviour directly contradicts the official Microsoft documentation: https://learn.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=github-actions

**Comment by rickvdbosch** [comment]
Is there more information about the current status of this issue? 

It seems like there is no solution yet: the below pipeline deploys all Pull Requests to a preview environment based on their PR-number, not to one called 'preview'.

```
name: Preview based on PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          deployment_environment: "preview"
          azure_static_web_apps_api_token: ${{ secrets.MY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
```
