### ISSUE TITLE
Allow override or customization of the GitHub PR Pull Request Comments

### ISSUE THREAD

**Issue by James-Firth** [Azure/static-web-apps#1402]
**Is your feature request related to a problem? Please describe.**

It's frustrating when you have multiple deploys per PR (for example storybook and a React app) to remember which environment is which. "Chocolate Rain" and "Funky Monkey" don't exactly imply one or the other :)

**Describe the solution you'd like**

I would like to be able to provide a custom string in the comment that is posted to the PR. As simple as a custom comment section would be great.
As complicated as a full-blown template string would be great, but not required.

**Describe alternatives you've considered**

I've considered writing my own script to push comments to the PR or attempting to modify them after the fact. Both of them require more customization and maintenance, and the reason we use SWAs is because of how easy they are to use.

**Additional context**
N/A

**Comment by nitelite** [comment]
I solved this for our build scripts using permissions in Github Actions.

By removing the write permissions from PR in the workflow job that runs the static-web-app action, you can stop it from posting the comment without any other trouble. Only read permissions like this, see `permissions`:

```
   [...]
   build_and_deploy_job:
      name: Build and Deploy Job
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
      runs-on: ubuntu-latest
      permissions:
         contents: read
         pull-requests: read
      steps:
         - name: Deploy
           uses: Azure/static-web-apps-deploy@v1
           [...]
```

This avoid the built-in comment being posted. I then added the follow task with a depedency on the build task, so it runs after build. This needs write permissions to PRs to be able to post comment. This is the task I added:

```
   [...]
   add_staging_comment:
      if: inputs.HAS_STAGING && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
      needs: build_and_deploy_job
      runs-on: ubuntu-latest
      permissions:
         pull-requests: write
      name: Add Staging URL to PR comments
      steps:
         - uses: mshick/add-pr-comment@v2
           if: always()
           with:
              message-id: "uniqueMessageIdForEnv"
              message: "Your staging environment has been set up at https://unique-url-for-staticwebapp-${{ github.event.number }}.adjustasneeded.azurewebsites.net
              message-failure: Staging environment not updated, because build failed.
   [...]
```

It has several advantages:
- Allows you to customize the message posted.
- Only posts one comment, so you are not spamming your comment if you do a lot of commits after making PR.
- If a comment for that job already exists, and job runs again, it will update the existing comment based on the message-id param.
- If you have multiple SWA environments building from one PR, you can give them different message IDs so you get one comment with URL each.
- If it has previously posted a working URL and the build fails, it will update the existing comment with a message that build failed so you know it's not current with code in PR.
