### ISSUE TITLE
Unable to deploy pre-built JS function using azure/static-web-apps-deploy and github actions

### ISSUE THREAD

**Issue by ghorsey** [Azure/static-web-apps#1426]
**Describe the bug**

I have successfully deployed a static web app using the Azure/static-web-apps-deploy.  The code deployment process succeeds correctly, says the API was found and the artifact was uploaded but the function is not active.

I logged the directory contents in the build:
```
Run ls -lah /home/runner/work/n-notes/n-notes/nnotes-client/dist/apps/n-notes-func
total 28K
drwxr-xr-x 2 runner docker 4.0K Mar  7 01:26 .
drwxr-xr-x 4 runner docker 4.0K Mar  7 01:26 ..
-rw-r--r-- 1 runner docker  289 Mar  7 01:26 host.json
-rw-r--r-- 1 runner docker  568 Mar  7 01:26 index.js
-rw-r--r-- 1 runner docker  172 Mar  7 01:26 local.settings.json
-rw-r--r-- 1 runner docker 2.0K Mar  7 01:26 package-lock.json
-rw-r--r-- 1 runner docker  [15](https://github.com/***/n-notes/actions/runs/8181425269/job/22371179279#step:10:16)4 Mar  7 01:26 package.json
```
And the results of the azure/static-web-apps-deploy that shows the success of the deployment and the configuration for the function from my `staticwebapp.config.json`:
```log
Verbose logging enabled
Try to validate location at: '/github/workspace/github/workspace/nnotes-client/dist/apps/n-notes'.
Build timeout not specified, defaulting to 15 minutes
App Directory Location: '/github/workspace/nnotes-client/dist/apps/n-notes' was found.
Try to validate location at: '/github/workspace/swa-db-connections'.
Looking for event info
Event info parsed from GitHub event json.
Skipping step to build /github/workspace/nnotes-client/dist/apps/n-notes with Oryx
Found staticwebapp.config.json file: 'nnotes-client/dist/apps/n-notes/staticwebapp.config.json'
Didn't find Oryx manifest file under location: /bin/staticsites/65286476-b1fc-4bfb-8efc-77c58fa0f1bf-swa-oryx/app-manifest/oryx-manifest.toml
Determined default file to be: index.html
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Calculating the size of app artifacts: 269678 B
Try to validate location at: '/github/workspace/github/workspace/nnotes-client/dist/apps/n-notes-func'.
Api Directory Location: '/github/workspace/nnotes-client/dist/apps/n-notes-func' was found.
Skipping step to build /github/workspace/nnotes-client/dist/apps/n-notes-func with Oryx
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 18
Zipping Api Artifacts
Api Zip will be created from directory: /github/workspace/nnotes-client/dist/apps/n-notes-func
Api Content Hash: 4894e7bb38a16776d8b8749b6379e931
Done Zipping Api Artifacts
Zipping App Artifacts
App Zip will be created from directory: /github/workspace/nnotes-client/dist/apps/n-notes
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.0970312(s)
Status: InProgress. Time: 15.1840[23](https://github.com/***/n-notes/actions/runs/8181425269/job/22371179279#step:11:24)(s)
Status: Succeeded. Time: 30.[27](https://github.com/***/n-notes/actions/runs/8181425269/job/22371179279#step:11:28)76[49](https://github.com/***/n-notes/actions/runs/8181425269/job/22371179279#step:11:50)9(s)
Deployment Complete :)
Visit your site at: https://***.4.azurestaticapps.net/
Thanks for using Azure Static Web Apps!
Exiting
```
Notice that the logs says:
* `Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 18`
* `Api Zip will be created from directory: /github/workspace/nnotes-client/dist/apps/n-notes-func`

Here are the contents of index.js
```js
"use strict";

// apps/n-notes-func/src/hello/hello.function.ts
var import_functions = require("@azure/functions");
async function hello(request, context) {
  context.log(`Http function processed request for url "${request.url}"`);
  const name = request.query.get("name") || await request.text() || "hello";
  return { body: `Hello, ${name}!` };
}
function registerHelloFunction() {
  import_functions.app.http("hello", {
    methods: ["GET", "POST"],
    authLevel: "anonymous",
    handler: hello
  });
}

// apps/n-notes-func/src/index.ts
registerHelloFunction();
```
and package.json
```json
{
  "name": "n-notes-func",
  "version": "0.0.1",
  "dependencies": {
    "@azure/functions": "4.3.0"
  },
  "main": "./index.js",
  "type": "commonjs"
}
```

my github action
```yaml
name: nNotes PWA

env:
  NODE_VERSION: "18"
  VERBOSE: 'true'
  APP_LOCATION: "${{ github.workspace }}/nnotes-client/dist/apps/n-notes" # location of your client code
  API_LOCATION: "${{ github.workspace }}/nnotes-client/dist/apps/n-notes-func" # location of your api source code - optional
  OUTPUT_LOCATION: "" # location of client code build output

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nnotes-pwa.yml
      - nnotes-client/**

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - .github/workflows/nnotes-pwa.yml
      - nnotes-client/apps/**
      - nnotes-client/libs/**

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  dev:
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nnotes-client
    permissions:
      contents: read
      actions: read
    name: Build and deploy to the dev environments
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: 'npm'
          cache-dependency-path: ./nnotes-client/package-lock.json

      - name: Install CI Dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Derive appropriate SHAs for base and head fo `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Ensure tracking main branch for the `nx affected` command.
        # This line is needed for nx affected to work when CI is running on a PR
        run: git branch -u origin/main

      - name: Run Lint, Test and Build
        run: npx nx run-many -t lint,test,build --parallel=3 --projects=n-notes,n-notes-e2e,n-notes-func

      - name: Run E2E tests
        run: npx nx affected -t e2e
      
      - name: Show function directory
        run: |
          ls -lah ${{ env.API_LOCATION }}

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.NNOTES_PWA_DEPLOY_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_api_build: true
          skip_app_build: true
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          # output_location: ${{ env.OUTPUT_LOCATION }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nnotes-client
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.NNOTES_PWA_DEPLOY_KEY }}
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          action: "close"
```
staticwebapp.config.json
```json

```

**To Reproduce**
1. create nx repository for angular: `npx create-nx-workspace@latest angular-monorepo --preset=angular-monorepo`
2. add the azure function plugin: `npm install -D @ziacik/azure-func`, `nx generate @ziacik/azure-func:application --name=my-func-app --directory=packages/my-func-app --projectNameAndRootFormat=as-provided`, and `nx generate @ziacik/azure-func:function --name=hello-world --project=my-func-app`
3. Create a github action to pre-build both the angular app and the azure typescript function.  disable the build process with `skip_api_build`, `skip_app_build` and set the `app_location` and `api_location` to the build folder.
4. Watch the build succeed

**Expected behavior**

**Screenshots**

**Device info (if applicable):**

**Additional context**
