### ISSUE TITLE
Deployment from Bitbucket results in a timeout during the npm install step for a Nuxt3 project.

### ISSUE THREAD

**Issue by teru-nakajima** [Azure/static-web-apps#1434]
hello

**Describe the bug**

Deployment from Bitbucket results in a timeout during the npm install step for a Nuxt3 project.

**To Reproduce**
1. deploy from Bitbucket
2. timeout on npm install

![image](https://github.com/Azure/static-web-apps/assets/113019917/945156b5-eb43-4b18-9822-c098db6f4cba)

```
script:
  - chown -R 165536:165536 $BITBUCKET_CLONE_DIR
  - pipe: microsoft/azure-static-web-apps-deploy:main
    variables:
      APP_LOCATION: "$BITBUCKET_CLONE_DIR/"
      API_LOCATION: ""
      APP_BUILD_COMMAND: "npm run generate"
      OUTPUT_LOCATION: "$BITBUCKET_CLONE_DIR/.output/public"
      API_TOKEN: $deployment_token
```

**Additional context**

Deployments were successful until March 14th, 2024. When successful, deployments typically take between 3 and 4 minutes. Currently, after the npm install step, 16 minutes elapse, resulting in a timeout.
