### ISSUE TITLE
Deployment Failure Reason: Failed to deploy the Azure Functions.

### ISSUE THREAD

**Issue by Vhab** [Azure/static-web-apps#1445]
Since a couple of hours ago, we're getting `Deployment Failure Reason: Failed to deploy the Azure Functions.` on all our deploy attempts.
Including on re-running old pipelines on old commits that previously deployed successfully, will now 100% return that error.

This is a hybrid Next.JS app being deploying using Azure Pipeline's `AzureStaticWebApp@0`, which uses Oryx.

Throughout the week we have however regularly seen `Failure Reason: Web app warm up timed out. Please try again later.`, but a retry of the pipeline often just succeeded after.

We have tried deleting the environment, but it didn't help.

The last deploy to succeed was at 12:09 PM GMT, the first to fail at 12:37 PM.

```
---End of Oryx build logs---
Web App Runtime Information. OS: linux, node version: 18
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.0432745(s)
Status: Failed. Time: 18.771164(s)
Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Functions.
```

**Comment by mmcossu** [comment]
same problem here, with Next.js hybrid ...

i noticed that while the pipeline stopped deploying, the existing app could finally be connected to Application Insight (i could not, before today, since i don't use azure functions as a BE  for this portal)
Might it be tha some update has been silently deployed, causing this issue?

**Comment by mmcossu** [comment]
it seems somehow the issue was resolved during this 15H period...
i was now able to deploy once again on multiple resources...
Azure Status reports no incident during the last 48h... this is weird...

**Comment by filipewellpack** [comment]
I have the same problème, the service work fine on 29/03/2024 and don't work now.
my YML file : 
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure_static_web_app
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure_static_web_app

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: ttps://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: ".output/server" # Api source code path - optional
          output_location: ".output/public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          APP_URL: "https://example.com"
          API_URL: "https://api.example.com"
          APP_NAME: "example"
          LOCAL_STORAGE_KEY: "test"
          DEFAULT_LOCAL: "fr"
          # DEFAULT_TIMEZONE: "Europe/Paris"
          PUBLIC_SENTRY_DSN: ""
          SENTRY_AUTH_TOKEN: ""
          PUSHER_APP_ENABLED: true
          # PUSHER_APP_ID: "id"
          PUSHER_APP_KEY: "key"
          # PUSHER_APP_SECRET: "secret"
          PUSHER_APP_CLUSTER: "eu"
          PUSHER_APP_LOG: true
          TZ: "Europe/Paris"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

```
