### ISSUE TITLE
Blazor wasm with Microsoft.Typescript.MSBuild fails to deploy

### ISSUE THREAD

**Issue by lukas-kyeso** [Azure/static-web-apps#1459]
Blazor wasm with Microsoft.Typescript.MSBuild fails to deploy 

Using this package:
`    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.4.4">
`

And I install node like this but it makes no difference to the error logs
<img width="1014" alt="Screenshot 2024-04-26 at 9 48 53 PM" src="https://github.com/Azure/static-web-apps/assets/3828018/06a3aaac-f035-440a-929a-7f71c59c4923">

It seems node is installed, but MSBuild can't find it...

The errors:
` Shared -> /github/workspace/Shared/bin/Release/net8/Shared.dll
/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003: The specified task executable "node" could not be run. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'node' with working directory '/github/workspace/Client'. No such file or directory [/github/workspace/Client/Client.csproj]`

`/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/github/workspace/Client/Client.csproj]
/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/github/workspace/Client/Client.csproj]
/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/github/workspace/Client/Client.csproj]`

`/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003:    at TypeScript.Tasks.VsTsc.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/github/workspace/Client/Client.csproj]`

`/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.0-beta/tools/Microsoft.TypeScript.targets(320,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/github/workspace/Client/Client.csproj] | 1 | Please build your app locally before publishing. | https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-linux`

Much appreciated

**Comment by oneolddev** [comment]
Having the same issue using the following references:
``` xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.7" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.5.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```
Also getting `/github/home/.nuget/packages/microsoft.typescript.msbuild/5.5.3/tools/Microsoft.TypeScript.targets(566,5): error MSB6003: The specified task executable "node" could not be run. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'node' with working directory`

**Comment by oneolddev** [comment]
This issue was previously reported #261. 

The [solution provided](https://github.com/Azure/static-web-apps/issues/261#issuecomment-867591087) there is no longer applicable.

**Comment by oneolddev** [comment]
The root cause of my issue is that Oryx does not handle this configuration. The solution for me was to change the GitHub Action to make it a custom build but still use Oryx to deploy. I used the following as a starting point:

``` yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust as needed

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Adjust as needed

      - name: 📦 Install Node dependencies
        run: |
          cd ClientApp # or wherever your TypeScript lives
          npm install

      - name: 🛠️ Compile TypeScript
        run: |
          cd ClientApp
          npm run build # or tsc

      - name: 🏗️ Build Blazor WASM
        run: dotnet build --configuration Release

      - name: 🚀 Publish Blazor WASM
        run: dotnet publish -c Release -o build_output

      - name: 📤 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (e.g., PR comments)
          action: "upload"
          app_location: "build_output/wwwroot" # This is where Blazor WASM outputs static files
          api_location: "" # Leave empty unless you have an Azure Functions backend
          output_location: "" # Not needed for Blazor WASM
```

### Additional details

The TypeScript was used to for JSInterop. I opted to use [Microsoft.TypeScript.MSBuild](https://learn.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-nuget?view=vs-2022) and placed all my TypeScript options in the porject file. This allowed me to skip _Setup Node.js_, _Install Node dependencies_, and _Compile TypeScript_ steps above.

### References

- [Using a custom build pipeline with Azure Static Web Apps](https://www.meziantou.net/using-a-custom-build-pipeline-with-azure-static-web-apps.htm)
