### ISSUE TITLE
Help me configure this horrible YML build pipeline for a static web app

### ISSUE THREAD

**Issue by 1TheMuffinMan** [Azure/static-web-apps#1463]
YML pipelines are ridiculous. How did we go from GUI with helpful drop down lists and directory pickers to basically notepad where you have zero intellisense and need to run the pipeline several hundred times to figure out you formatted the commands incorrectly?

Anyways.

I'm using an Azure Static Web app and it created a build pipeline for me.
The app is a React app using Webpack and it generates a `dist` folder at the root.

Here's the `AzureStaticWebApp@0` task

```
  - task: AzureStaticWebApp@0
    inputs:
      app_location: ''
      output_location: 'dist'
      skip_api_build: true
      azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_XYZ123)'
```

I've tried every possible combination of values in `app_location` and `output_location`, but get the following error:
`Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location.`

**Comment by mbenniston** [comment]
Had the same error, removing an APP_LOCATION environment variable I had set fixed this

**Comment by sebastianblesgen** [comment]
I use this (release pipeline)
```
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: '
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/$(build-artifacts-name)'
    app_location: /
    output_location: dist
    skip_app_build: false
    skip_api_build: true
    is_static_export: false
    verbose: false
    azure_static_web_apps_api_token: '$(APIToken)'
    deployment_environment: preview
```
