### ISSUE TITLE
GitHub Action: Close PR errors with deployment_token was not provided.

### ISSUE THREAD

**Issue by Official-James** [Azure/static-web-apps#1489]
**Describe the bug**

Using the [azure/static-web-apps-deploy](https://github.com/Azure/static-web-apps-deploy) GitHub Action, on closed PR action the following error appears: 

```
deployment_token was not provided.
The deployment_token is required for deploying content. If you'd like to continue the run without deployment, add the configuration skip_deploy_on_missing_secrets set to true in your workflow file
An unknown exception has occurred
```
This is preventing cleanup of the preview environments in the Static Web App.

**To Reproduce**
1. Add the following as a job in GitHub Actions:
```yml
  close_pull_request_job:
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
            app_location: '.'
            azure_static_web_apps_api_token: ${{ secrets.staticWebAppToken }}
            action: "close"
```
2. Close PR to trigger
3. The above error appears

**Expected behavior**
PR to trigger on close and clean-up the preview environment

**Comment by PipeItToDevNull** [comment]
https://github.com/Azure/static-web-apps/issues/1342

This is the same issue, but I don't understand the fix

**Comment by PipeItToDevNull** [comment]
I obtained a token by going to the SWA and choosing "Manage deployment token" on the "Overview" page.

This token is then created as a Dependabot specific secret WITH THE SAME NAME as the normal token per https://github.com/Azure/static-web-apps/issues/788

**Comment by mikeholczer** [comment]
I don't think this is truly a duplicate because this issue exists in the action as created by the wizard for creating a SWA, where as the linked issues I believe relate to actions people manually created.

**Comment by georgibakken** [comment]
I tried taking the token from Azure Portal, adding it as a Dependabot secret with the name `AZURE_STATIC_WEB_APPS_API_TOKEN` and setting it in the `Close Pull Request Job` 

```yaml
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
```

with no success, I get the same error `deployment_token was not provided.`

I have a manually created pipeline
