### ISSUE TITLE
React app deploy fails with unsupported language error

### ISSUE THREAD

**Issue by jhamman** [Azure/static-web-apps#151]
I have recently created a static web app with the following command: 

```shell
az staticwebapp create \
    -n {NAME} \
    -g {PROJECT} \
    -s {REPO} \
    -l WestUS2 \
    -b master \
    --app-artifact-location ".next" \
    --token {TOKEN} \
    --verbose
```

This command succeeded and resulted in a new GitHub Action being added to my project repository. The deploy action is, however, failing with the following error message: 

```
...
Copying files to destination directory '/bin/staticsites/ss-oryx/api'...
Done in 3 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 42 sec(s).


---End of Oryx build logs---
The function language ',nodejspython' is unsupported or invalid. The following languages are valid: node, dotnet, python.
```

<Details>
<ul>
<li> next.js / react project
<li> workflow file:
<ul/>

```yaml

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_SAND_091D5411E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '.' # App source code path
          api_location: '.' # Api source code path - optional
          app_artifact_location: '.next' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
``` 
</Details>

**Comment by miwebst** [comment]
This is strange and we will look into this. One quick question for you is are you using Azure Functions? This code is failing because it believes you have an Azure Function and can't detect the language. If you set the api_location to a non-existent folder, then we will assume that means you have no Function and we will skip this check.

**Comment by jhamman** [comment]
> One quick question for you is are you using Azure Functions?

I am not. I will try setting the `api_location` key to see if that helps.

**Comment by miwebst** [comment]
Hey @jhamman, I am trying to reproduce this error so we can work on a fix. Do you mind sharing a little bit about the structure of your app? My guess is that our detection logic is picking up on something that is should not be.

**Comment by jhamman** [comment]
Sorry for the late reply here. Setting `api_location` to a non-existent directory did fix the error for me. 

The project I'm working on (https://github.com/carbonplan/maps) is currently private but here is an example of a similar build system: https://github.com/carbonplan/research. The only difference I can see between these projects is that the maps project has some python scripts in it. So perhaps Oryx is picking up Python as a dependency from there?

**Comment by lucashfreitas** [comment]
Same problem here. I am running a mono repository and the workflow it's not flexible regarding the API output folder. We did a workaround to manually build/copy all api folders but now azure is not able to identify that we're using nodejs as language even though the api base folder has a package.json. Would be nice if we had an option to manually specify that as I am not sure why the workflow can't guess it.

**Comment by p0onage** [comment]
The same issue for me, I deployed my initial Azure Function written in c# just fine, this error occurred when I started adding NuGet packages.  

File structure below 

> ├── .github
│   └── workflows
│       └── azure-static-web-apps-<DEFAULT_HOSTNAME>.yml
│
├── api
│   ├── myapp.cs
│   ├── api.csproj
│   ├── host.json
│   ├── local.settings.json
│   ├── node_modules ->
│   ├── bin ->
│   ├── obj ->
│   └── package.json
│
└── (folders and files from your static web app)

**Comment by anthonychu** [comment]
looks like the package.json is affecting detection of the function app language. It's rare to see that in a function app. Is it meant to be there?

**Comment by p0onage** [comment]
@anthonychu I believe so, how else do you add NuGet packages? Is it different from SWA? I usually use visual studio and the in-built package manager. But here is a reference to other developers [adding the package.json](https://stackoverflow.com/questions/36411536/how-can-i-use-nuget-packages-in-my-azure-functions) to the project

**Comment by rishabkumar7** [comment]
I ran into a similar issue with a Docusaurus project (react), setup the GitHub Action for Azure Static Web App as following
``` yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_PEBBLE_02FAB060F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          app_build_command: "npm run build"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_PEBBLE_02FAB060F }}
          action: "close"
```
And this is the repository structure
![image](https://user-images.githubusercontent.com/45825464/211115590-42d93340-08b3-4484-95bc-5d80d598bb29.png)

But the GitHub Action fails with the following error
```
App Directory Location: '/' was found.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: npm run build
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20221103.1, Commit: a2c65dde[15](https://github.com/learntocloud/learn-to-cloud/actions/runs/3859202183/jobs/6578512352#step:4:16)2b749fea395f4d1242ea9350942258, ReleaseTagName: 20221103.1

Build Operation ID: |Dhps9g4eQUQ=.8db[17](https://github.com/learntocloud/learn-to-cloud/actions/runs/3859202183/jobs/6578512352#step:4:18)[19](https://github.com/learntocloud/learn-to-cloud/actions/runs/3859202183/jobs/6578512352#step:4:20)1_
Repository Commit : bc[24](https://github.com/learntocloud/learn-to-cloud/actions/runs/3859202183/jobs/6578512352#step:4:25)30092c3d0de[26](https://github.com/learntocloud/learn-to-cloud/actions/runs/3859202183/jobs/6578512352#step:4:27)5b6abb50095a2a6494da5e8

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
[WARNING] Api Directory Location: 'api' could not be found. Azure Functions will not be created.
Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

I have tried removing the `api_location`, still same error and also have tried with no `app_build_command`, same issue persists.
