### ISSUE TITLE
Problem With Deploy Static Web App

### ISSUE THREAD

**Issue by FarrudaGod** [Azure/static-web-apps#1533]
**Describe the bug**

I encountered an unknown exception during the deployment of an Azure Static Web App using Azure Pipelines. The deployment process downloads the `mcr.microsoft.com/appsvc/staticappsclient:stable` image and attempts to deploy the app, but it fails with an unknown exception.

**To Reproduce**
1. Run the Azure Pipeline configured to deploy an Azure Static Web App.
2. The pipeline executes successfully until it reaches the deployment step.
3. The process fails with an unknown exception and exits with code 1.

**Expected behavior**
The Azure Static Web App should deploy successfully without any exceptions, completing the deployment process.

**Device info (if applicable):**
- OS: Linux (Azure Pipelines)
- Browser: N/A
- Version: N/A

**Additional context**
- The pipeline has been working previously but started encountering this issue after minor adjustments to the deployment step. 
- No sensitive data can be shared, but I'm including the error message for reference:

Digest: sha256:07![2024-08-22_10-55](https://github.com/user-attachments/assets/0f0739b3-b958-4eb6-a044-ed1ba822d5ac)
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient
DeploymentId: 2f5abc4a-1f8b-4440-acce-70ed9962f582

An unknown exception has occurred

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

##[error]Error: The process '/usr/bin/bash' failed with exit code 1
-

Any insights or suggestions on how to resolve this issue would be greatly appreciated. Thank you!

**Comment by sebastianblesgen** [comment]
app_location is probably / and you need an output_location I guess. Here is what I have (using devops release pipeline)
```
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: '
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/$(build-artifacts-name)'
    app_location: /
    output_location: dist
    skip_app_build: false
    skip_api_build: true
    is_static_export: false
    verbose: false
    azure_static_web_apps_api_token: '$(APIToken)'
```
