### ISSUE TITLE
Unable to move from a Free to Standard plan - Pipeline configuration unclear

### ISSUE THREAD

**Issue by daaimah123** [Azure/static-web-apps#1556]
## **Describe the bug**
We were getting a github azure workflow error stating an update in storage would be needed. Our application is deployed to azure on our main branch, but because of the build errors it is not building properly (which were related to storage with recommendation to update to standard - we did this). We upgraded from free to standard plan, but now our preview links are rendering blank. We are unsure if there is additional configuration needed that was not specified in the change in plan tiers. 

We have found [referenced](https://learn.microsoft.com/en-us/answers/questions/431121/unable-to-move-from-a-free-to-standard-plan-unless) this command from a couple years back: 

```
az staticwebapp disconnect -n <your-app-name> -g <resource-group-name>
az staticwebapp update -n <your-app-name> --sku Standard
```

**_Should we be running these commands to resolve the issue, or is there a different solution?_**

## **Expected behavior**
Clicking into our workflow preview link with updated changes that recognize the account has switched over to the standard plan

### Screenshot: Error in GH workflow build
<img width="1256" alt="Screenshot 2024-10-07 at 2 59 24 PM" src="https://github.com/user-attachments/assets/f0b1b2a6-e273-4887-8ea5-abffe44167cb">

### Screenshot: Main branch with broken build
<img width="1267" alt="deploy build fail" src="https://github.com/user-attachments/assets/26b614dc-ffb5-48ce-bfe6-9714b13d66d2">

### .github/workflow/....yml file
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_GLACIER_0000000 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist' # Built app content directory - optional
          app_build_command: 'npm run build'
          api_build_command: 'rm -rf ./node_modules/ && rm -rf --cache'
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_GLACIER_0000000 }}
          action: 'close'
```

## **Device info: MacbookPro 16in 2021 / MacbookPro 16in 2022**
 - OS: ventura 13.0
 - Browser: Chrome
 - Version: 126.0.6478.127 (Official Build) (arm64)
