### ISSUE TITLE
Deploying the API suceds but no API is presented in Azure?

### ISSUE THREAD

**Issue by MrHinsh** [Azure/static-web-apps#1570]
I'm having a problem with the API deployment and I don't see any error messages. It looks like its deploying the API, but in the APIs tab does not show any active APIs.

![Image](https://github.com/user-attachments/assets/435c5e2a-489c-4bf6-afa5-4c33e0d33832)

**Why might this be the case? What else can I look at to debug?**

---

staticwebapp.config.json: https://github.com/nkdAgility/NKDAgility.com/blob/54-update-courses-data/staticwebapp.config.json
```
{
  "platform": {
    "apiRuntime": "dotnet-isolated:8.0"
  }
}

```

Build: https://github.com/nkdAgility/NKDAgility.com/blob/54-update-courses-data/.github/workflows/main.yaml
```
- name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        id: azureDeploy
        env:
          VERBOSE: true
        with:
          repo_token: ${{ steps.app-token.outputs.token }}
          action: "upload"
          app_location: ./_site
          api_location: ./_api
          skip_app_build: true
          skip_api_build: true
          output_location: ""
          deployment_environment: ${{ (needs.Setup.outputs.nkdAgility_AzureSitesEnvironment) }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
```

Log: https://github.com/nkdAgility/NKDAgility.com/actions/runs/11594635655/job/32281460532
```
Verbose logging enabled
Try to validate location at: '/github/workspace/./_site'.
Build timeout not specified, defaulting to 15 minutes
App Directory Location: './_site' was found.
Try to validate location at: '/github/workspace/swa-db-connections'.
Looking for event info
Event info parsed from GitHub event json.
Skipping step to build /github/workspace/./_site with Oryx
Found staticwebapp.config.json file: '_site/staticwebapp.config.json'
Didn't find Oryx manifest file under location: /bin/staticsites/e47c04cd-260e-4fbf-86ed-29ba95663724-swa-oryx/app-manifest/oryx-manifest.toml
Determined default file to be: index.html
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Calculating the size of app artifacts: 409548339 B
Try to validate location at: '/github/workspace/./_api'.
Api Directory Location: './_api' was found.
Skipping step to build /github/workspace/./_api with Oryx
Function Runtime Information. OS: windows, Functions Runtime: ~4, dotnetisolated version: 8.0
Found functions.metadata file
Zipping Api Artifacts
Api Zip will be created from directory: /github/workspace/./_api
Api Content Hash: 4ea5b8d7[19](https://github.com/nkdAgility/NKDAgility.com/actions/runs/11594635655/job/32281460532#step:7:20)77aadda19207122664a342
Done Zipping Api Artifacts
Zipping App Artifacts
App Zip will be created from directory: /github/workspace/./_site
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1541086(s)
Status: InProgress. Time: 15.3149439(s)
Status: Succeeded. Time: 30.4664566(s)
Deployment Complete :)
Visit your site at: https://yellow-pond-042d[21](https://github.com/nkdAgility/NKDAgility.com/actions/runs/11594635655/job/32281460532#step:7:22)b03-68.westeurope.5.azurestaticapps.net
Thanks for using Azure Static Web Apps!
Exiting
```
