### ISSUE TITLE
.NET 9 is missing in docker image

### ISSUE THREAD

**Issue by KSemenenko** [Azure/static-web-apps#1583]
**Describe the bug**
Azure devops build issue:

```
Digest: sha256:41473a2ebc45daa6e63c82a7f32a5680b0fe34dac49ab85dd6369c764b191308
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
benv: dotnet version '9.x' not found.
benv: Could not find any versions on disk.
```

**To Reproduce**
I use Azure Static web Site for Blazor WebAssembly app.
I update my app to .NET 9
My azure devops pipeline looks like this. 
```
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web App'
  inputs:
    app_location: 'App.WebClient/'
    output_location: 'wwwroot'
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
```

How can I fix this issee? seems we have old container with .NET8

Status: Downloaded newer image for **mcr.microsoft.com/appsvc/staticappsclient:stable**
benv: dotnet version '**9.x**' not found.
