### ISSUE TITLE
Problem with private git submodules

### ISSUE THREAD

**Issue by antst** [Azure/static-web-apps#159]
I have a git submodule in my repo which hosts the site.
Both of them, repo and submodule are part of the same organization.
I tried to configure submodule with both, absolute and relative URL, but in both cases I end up with the same story 

```
Cloning into '/home/runner/work/path/to/subrepo/dir'...
2020-09-24T11:53:47.5107596Z remote: Repository not found.
2020-09-24T11:53:47.5115065Z ##[error]fatal: repository 'https://github.com/Organization/subrepo.git/' not found
2020-09-24T11:53:47.5162344Z ##[error]fatal: clone of 'https://github.com/Organization/subrepo.git' into submodule path '/home/runner/work/path/to/subrepo/dir' failed
2020-09-24T11:53:47.5169094Z Failed to clone 'subrepo/dir'. Retry scheduled
```

Is there any reasonable way to get it running?

**Comment by miwebst** [comment]
Do you mind pasting the whole Action log? Is this failing in the checkout action?

**Comment by antst** [comment]
This is full log.

[full_log.txt](https://github.com/Azure/static-web-apps/files/5278198/full_log.txt)

**Comment by miwebst** [comment]
Yes this looks to be an issue with the checkout action. You can find the docs here: https://github.com/actions/checkout 

There is a comment about using a PAT if you are accessing a different private repository, but it sounds like it may be part of your repository already? You may want to file an issue there if that is the case.

**Comment by itpropro** [comment]
You have to specify a PAT (from secrets) to be used in your action:
```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.YOUR_PAT }}
...
```
