### ISSUE TITLE
Unable to deploy static app

### ISSUE THREAD

**Issue by karthikeyanpkks** [Azure/static-web-apps#1591]
The content server has rejected the request with: BadRequest
Reason: No matching Static Web App was found or the api key was invalid.

i have updated the latest deployment token even though the above error on github action 

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/2c2ec5db-0573-4b26-97e9-60f6b8b327b3)

**Comment by DaleL-SilannaIT** [comment]
I had the same issue.

## Solution
You need to find this secret in your GitHub repo and set the value to your deployment token from your Static Web App.

### How to get your deployment token

1. Navigate to your Static Web App in Azure
2. Select the `Overview` tab
3. In the top ribbon, select the `Manage deployment token tab` and copy your token.
<img width="754" alt="Image" src="https://github.com/user-attachments/assets/6b369966-62b1-4dcb-851f-b909b077d427" />

### How to set a secret value in GitHub Actions
1. Navigate to your GitHub Repo on GitHub's website and log in with an owner account
2. Select `Settings` in the ribbon at the top of the screen
<img width="601" alt="Image" src="https://github.com/user-attachments/assets/00a1967c-1626-4e23-87b8-2d9e0a59da2e" />
3. Under the `Secrets and variables` dropdown, select **Actions**
<img width="251" alt="Image" src="https://github.com/user-attachments/assets/d646bbf3-412c-4e74-86f4-c464fd86904a" />
4. You can then add/edit the names and values of secrets that are exposed to GitHub Actions at runtime.
<img width="628" alt="Image" src="https://github.com/user-attachments/assets/ecadd915-2b4a-48de-9083-fd5f32cd71fc" />

### How to use a secret in GitHub Actions
1. In your `.github/workflows/azure-static-web-apps-XXXX.yml` file you need to specify the secret name and environment variable under the `Build and Deploy Job` as well as the `Close Pull Request Job`
```yml
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_XXX}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

## Deploy
Now make a commit to your repo and GitHub actions should deploy it to your Static Web App via the deployment token.
