### ISSUE TITLE
Can not change the app location folder configuration when deploying using Angular 19.

### ISSUE THREAD

**Issue by QuinntyneBrown** [Azure/static-web-apps#1598]
Can not change the app location folder configuration when deploying using Angular 19.

Azure is expecting the contents to be is dist/name-of-app and the contents are in dist/browser/name-of-app

**Comment by ashitanojoe** [comment]
I ran into this same problem. Changing the `output_location` in the yaml file to include the `browser` folder resolved the issue for me.

File: `.github/workflows/{path-to-your-build-config}.yml`

```
name: Azure Static Web Apps CI/CD

## omitted

jobs:
  build_and_deploy_job:
    ## omitted
    steps:
      ## omitted
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          ## omitted
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          ## change this setting
          output_location: "dist/name-of-app/browser" # Built app content directory - optional
  
```
