### ISSUE TITLE
Unable to reliably unlink managed API

### ISSUE THREAD

**Issue by eas-jens** [Azure/static-web-apps#1600]
**Describe the bug**

While working with a static web application that has been successfully deployed with the standard managed API backend, I am unable to reliably unlink the managed API to link my own function backend. I have followed the instructions located at https://learn.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own and left the API location set to "" but it does not unlink. If I try many deployments in a row, sometimes it will unlink but it does not happen as it is mentioned in the article.

Config example:

```
      - name: Deploy static web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          app_location:  ${{ env.APP_LOCATION }}
          api_location: ""
          output_location: ${{ env.APP_ARTIFACT_LOCATION }}
          production_branch: "dev"
          ###### End of Repository/Build Configurations ######
```
