### ISSUE TITLE
[Bug] Staging environment is not reliably closed when multiple PRs are closed at the same time

### ISSUE THREAD

**Issue by mwaddell** [Azure/static-web-apps#162]
When multiple pull requests are closed at the same time, SWA frequently fails to close the current staging environment to free up that slot.

This became a much bigger problem when we started using dependabot on all of our projects and we are limited to only a single staging environment.  If we have a handful of dependabot PR requests and we do a push to main which fixes them all, dependabot will go and close out all of the PRs that are now no longer applicable.  However, if one of those PRs had successfully deployed to the staging environment on SWA, it commonly fails to be deleted.  The only recourse is to go into the azure portal and manually delete that environment.  It does not happen every single time, but commonly enough that it became quite bothersome.

We have now started using the suggestion in issue #122 to stop dependabot PRs from being deployed to a staging environment. at all and this has resolved the issue for us  However, this does hint at a potentially larger problem which could occur anytime multiple PRs are closed at roughly the same time.

In the GHA logs, the PR which did not get deleted appears to have been first updated by dependabot (thus triggering a new build), then very shortly after closed (thus triggering the close event).  In the GHA log, it looks like the deployment event fails after upload (it states: "Finished Upload.. Polling on deployment." then polls, then states that the deployment failed because the build was cancelled).  Then, when the "close" job occurs, it declares that "The content server has rejected the request with: BadRequest Reason: No matching static site environment was found.".  This prevents the staging environment from being deleted even though it clearly shows up in portal.azure and is still usable.

Is it possible that the post-deployment action which publishes the URL as a comment also sets up something which is then used later during tear-down?  If the build is cancelled during the "polling on deployment" and then the PR is immediately closed, that seems to trigger the problem (relatively) reliably.

**Comment by miwebst** [comment]
Hey @mwaddell thanks for reporting this! I'll create a backlog item for us to investigate this.

**Comment by mwaddell** [comment]
@miwebst - I was just able to trigger this again even without dependabot enabled.  If you have a PR that is outdated but can be automatically merged, click "Update Branch" within the PR and then as soon as the "Merge" button becomes enabled again, click it.  This closes the PR but the original deployment hasn't completed yet.  

In the logs, it shows that the "Build and Deploy" job started after the "Close Pull Request" job, but that the "Close Pull Request" job finished first.  Both jobs succeed, but in the Azure portal, the environment was torn down but then a few minutes later brought back up.  Then, because the PR request is already closed, there's no way to get rid of that environment without doing it manually.

**Comment by mwaddell** [comment]
I have all the logs if you would like them - just let me know where I can safely submit them for your review.

**Comment by olakusibe** [comment]
I experienced same issue, the close pull request job action failed after successfully merging the staging branch with the main one.

**Comment by david-ps** [comment]
This problem occurs regularly for us. Any update on the fix ETA?

**Comment by James-Firth** [comment]
This also happens to us quite often

I've also 👍 to show my support and mostly commenting here for anyone in the future curious if it's still an issue.

**Comment by pilotkid** [comment]
I have the same issue in Nov 2021

**Comment by mhmo91** [comment]
raising another hand here that this is quite annoying!

**Comment by pilotkid** [comment]
The fix for me was adding in the following code to the my workflow yaml file. Works every single time now, for the last several months. 

```yaml 

 finish_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Finish Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_blah_blah }}
          action: "close"

```

**Comment by miwebst** [comment]
@mhmo91 can you clarify the scenario you are seeing this in? Is it the same scenario where you have a GitHub Action running because of an update to a PR and you close that PR concurrently?

**Comment by mhmo91** [comment]
@miwebst just noticed that the azure build is failing on pull requests due to environments exceeding max of 10. all the pull requests are closed yet the environment is still there taking up the space.

**Comment by miwebst** [comment]
Can you check the Azure Portal and try to remove those environments there?

**Comment by mhmo91** [comment]
@miwebst  that's what i did now, i'll let u know if the issue persisted, thanks, much appreciated your prompt response :)

**Comment by mhmo91** [comment]
> The fix for me was adding in the following code to the my workflow yaml file. Works every single time now, for the last several months.
> 
> ```yaml
>  finish_pull_request_job:
>     if: github.event_name == 'pull_request' && github.event.action == 'closed'
>     runs-on: ubuntu-latest
>     name: Close Pull Request Job
>     steps:
>       - name: Finish Pull Request
>         id: closepullrequest
>         uses: Azure/static-web-apps-deploy@v1
>         with:
>           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_blah_blah }}
>           action: "close"
> ```

This were  a default configuration that are created by the Azure static deployment plugin, and yet the issue happened, we moved to Azure cdn about a month ago!

**Comment by mwaddell** [comment]
@mhmo91 The issue is that the `finish_pull_request_job` completes before the `build_and_deploy_job` completes.  If you look in your PR, you'll see something like this:

![image](https://user-images.githubusercontent.com/750244/149177711-c51d8fc8-f534-4557-8e7e-f09572c305d6.png)

I tried adding a "cleanup" job to that same workflow which would execute after the `build_and_deploy_job` finishes and trigger the `finish_pull_request_job` if the PR had been closed.  However, since the entire workflow executes in the same context, the PR is still "open" from the perspective of that executing workflow.

The only solution I can think of is to create a separate workflow which is triggered when the `Azure Static Web Apps CI/CD` workflow completes and which would then check (in a separate context) whether the PR had been closed.  However, the [workflow_run](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run) event doesn't support pull_requests yet.

What I would like to do is add a second workflow with the following:

```yaml
name: Azure Static Web Apps Cleanup

on:
  workflow_run:
    workflows: ["Azure Static Web Apps CI/CD"]
    types: [completed]

jobs:
  close_pull_request_job:
    if: github.event.pull_request.state == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Finish Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_blah_blah }}
          action: "close"
```

However, the above will NOT work because `workflow_run` events are only ever triggered on your default branch.

**Comment by mwaddell** [comment]
For now, I'm using the [concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency) option as follows:

```yaml
name: Azure Static Web Apps CI/CD
concurrency: azure-${{ github.ref }}  
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

etc...
```

This prevents multiple instances of the workflow from running at the same time on the same PR, so the "close" action will always wait until the previous "deployment" action finishes before it begins, thus preventing this bug.

The downside to this approach is that if you push multiple commits to the same branch, only the last one will get executed and deployed, so if it fails due to an issue you introduced in one of the previous commits, you have no idea which commit caused the issue and have to manually revert each one until you find it.

All the other ones will either show up as cancelled or failed:

![image](https://user-images.githubusercontent.com/750244/149186080-39cb981b-adbb-445b-be08-58485b8f2f00.png)

**Comment by tr3ysmith** [comment]
Hey any word on this issue? Its still a problem a year and a half later...

**Comment by mikeholczer** [comment]
@miwebst can you share any status on this?

**Comment by carlohoanguyen** [comment]
Any update on this? 

We are experiencing that the preview environment isn't really being cleaned up (deleted) with this job. So we manually have to delete them in the portal:

```
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_TOKEN }}
          action: 'close'
          app_location: '/'
```
