### ISSUE TITLE
Unable To Publish SWA

### ISSUE THREAD

**Issue by SZRitter** [Azure/static-web-apps#1621]
All of our deploys are failing currently for an unknown reason. We are using Azure Pipelines to deploy a next.js application. These failures appear to have started about an hour ago.

```
Oryx has determined that the app build artifacts are in the '.next' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend.
Skipping step to build /***-swa-oryx/app/.next/standalone with Oryx
Web App Runtime Information. OS: linux, node version: 20
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
The content server has unexpectedly rejected the request with: InternalServerError
```

Here is the relevant step from the pipeline's YAML file:
```
- task: AzureStaticWebApp@0
          inputs:
            app_location: '/web'
            azure_static_web_apps_api_token: $(brDeploymentToken)
          env:
            NODE_ENV: 'production'
```

## Expected behavior
We expect it to deploy the latest version to the SWA. And, on failure, it should try to give us a more detailed idea of what the issue is, maybe passing back the internal server error.
