### ISSUE TITLE
Bug: Routes tab gone in portal and auth not working

### ISSUE THREAD

**Issue by estruyf** [Azure/static-web-apps#1623]
I have been trying a couple of times now with multiple Azure Static Web Apps. It all works smooth when no authentication is used, but once I add some auth routes, it starts failing. Although, the deployments work fine, but on the Azure portal, the **routes** tab is missing.

This is what I get before I apply any routes:

<img width="272" alt="Image" src="https://github.com/user-attachments/assets/689aec3c-6a15-4adb-9d38-07587078f6fc" />

When apply the following configuration (or any configuration):

```json
{
  "responseOverrides": {
    "404": {
      "rewrite": "/index.html",
      "statusCode": 200
    }
  },
  "navigationFallback": {
    "rewrite": "/index.html"
  },
  "routes": [
    {
      "route": "/success",
      "allowedRoles": ["admin"]
    }
  ]
}
```

In the portal the routes tab is gone:

<img width="211" alt="Image" src="https://github.com/user-attachments/assets/9af25ece-dcf5-48f1-b523-5b770c38e2eb" />

The authentication or routes are not working. I can navigate to `/success`, but still I can reach the page without being logged in.

<img width="527" alt="Image" src="https://github.com/user-attachments/assets/3127e34a-3722-4b0d-a105-6aed68de42ef" />

<img width="452" alt="Image" src="https://github.com/user-attachments/assets/2ae14aca-d437-4e2c-92ff-afba0299d02b" />

**To Reproduce**
1. Create a project with some auth routes (like the above configuration)
2. Deploy with the SWA CLI: `swa deploy -d <token> --env production`
3. Routes are not working after the deployment

```yml
name: Deployment to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd app && npm ci
          cd ..
          cd api && npm ci

      - name: Build
        run: npm run build

      - name: Clean dependencies
        run: cd api && npm ci --omit=dev

      - name: Install swa cli
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy
        run: swa deploy -d ${{ secrets.SWA_API_TOKEN }} --env production

```

**Expected behavior**

I would expect that the `routes` tab would always be visible, even if there is an error, there should be a section on the portal to validate what is wrong with the configuration. Right now, you have no clue why things aren't working as they should be.

**Screenshots**

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/4c16d755-92fc-4e87-a1cc-5efc4fbeae7a" />
