### ISSUE TITLE
deployment_token provided was invalid in bitbucket

### ISSUE THREAD

**Issue by sajidzaman** [Azure/static-web-apps#1629]
Hello, I want to deploy to azure static web app using bitbucket pipeline. I am getting:

**

Verbose logging enabled
deployment_token provided was invalid.
An unknown exception has occurred
Failed to record upload telemtry.

**

I am reopening this issue as I am facing this issue from the last 3 days, new pipe line does not work.

```
pipelines:
branches:
  main:
    - step:
         name: Deploy to production
         deployment: production
         script:
           - pipe: microsoft/azure-static-web-apps-deploy:main
             variables:
                  APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                  OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/.next'
                  API_TOKEN: $deployment_token
```

 I varified the token many times and reset as well but no success.

Thanks
