### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by sebastian-ksk** [Azure/static-web-apps#1632]
## Issue Description
I'm trying to deploy a Next.js 14 application to Azure Static Web Apps using an Azure DevOps pipeline. The pipeline runs successfully through the build phase, but after approximately 10 minutes in deployment, it fails with a timeout error.

The pipeline successfully zips and uploads the artifacts but then stays in "InProgress" status for about 10 minutes before finally failing with:
"Deployment Failure Reason: Web app warm up timed out. Please try again later."

My pipeline configuration:
```yaml
trigger:
 - master

pool:
 name: 'codeway-aws-linux2023'

variables:
 resourceGroup: 'EPRID208863-HP-FACIL-DEV-RG'
 staticWebAppName: 'HPCONNECT-ADMIN-V2'
 azureSubscription: 'Shared Enabled DEV2'

steps:
 - task: UseNode@1
   inputs:
     version: '18.x'
 - script: |
     npm install
     npm run build
   displayName: 'Install dependencies and build the application'
 - task: AzureStaticWebApp@0
   inputs:
     azure_static_web_apps_api_token: $(azureStaticWebAppsToken)
     skip_app_build: true
     app_location: '/'
     api_location: ''
     output_location: '.next'

```
```
Status: Failed. Time: 592.7564822(s)
Deployment Failed :(
Deployment Failure Reason: Web app warm up timed out. Please try again later.
```

I suspect the issue might be related to Next.js 14 output format and its compatibility with Azure Static Web Apps.
Additional Information

![Image](https://github.com/user-attachments/assets/8438c228-885a-4d8c-8bd5-275b2082c522)
