### ISSUE TITLE
Deployment failed without any changes

### ISSUE THREAD

**Issue by eou** [Azure/static-web-apps#1633]
**Describe the bug**

I'm deploying my Hugo app to Azure Static Web Apps. It had been working fine for several months, but about an hour ago, 2025-03-22 09:00AM PST, it started failing. The log shows "An unknown exception has occurred" after "polling on deployment."

<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/e1328aa7-758b-458d-9a76-b376a784902b" />

this is my workflow file on Github:
```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_GROUND_0EFD56E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          HUGO_VERSION: 0.133.1
          GOLANG_VERSION: 1.22.5
          PRE_BUILD_COMMAND: "git config --global --add safe.directory /github/workspace"
```

**Expected behavior**

**Screenshots**

<img width="938" alt="Image" src="https://github.com/user-attachments/assets/1ea51f25-f645-482b-b82e-a49942a7fd21" />
