### ISSUE TITLE
Unknown Exception Occurred During Azure Static Web App Deployment in Azure DevOps Release Pipeline

### ISSUE THREAD

**Issue by chudamanisanju** [Azure/static-web-apps#1634]
**Describe the bug**
I am encountering an unknown exception during the deployment of a Next.js application to Azure Static Web Apps using an Azure DevOps release pipeline. The process fails with the following error message:

2025-04-01T06:51:41.0872512Z ##[error]An unknown exception has occurred 2025-04-01T06:52:01.1119123Z 2025-04-01T06:52:01.1124591Z ##[warning]For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/ 2025-04-01T06:52:01.1125085Z ##[warning]If you believe this behaviour is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/ 2025-04-01T06:52:01.1125373Z ##[warning]Exiting 2025-04-01T06:52:01.1955808Z 2025-04-01T06:52:01.2002411Z ##[error]Error: The process '/usr/bin/bash' failed with exit code 1

**To Reproduce**
1. Create an Azure Static Web App.
2. Set up an Azure DevOps release pipeline with the following configuration:
    ```yaml
    steps:
    - task: AzureStaticWebApp@0
      displayName: 'Static Web App: '
      inputs:
        app_location: 'workspaces/annual-readiness-compliance'
        app_build_command: 'npm run build'
        skip_app_build: false
        skip_api_build: true
        is_static_export: false
        verbose: false
        azure_static_web_apps_api_token: 'YOUR_DEPLOYMENT_TOKEN'
        deployment_environment: 'Production'
        production_branch: 'develop'
        azure_access_token: 'YOUR_AZURE_ACCESS_TOKEN'
    ```
3. Run the release pipeline.

**Expected behavior**
The deployment should complete successfully without any exceptions.

**Screenshots**

**Additional context**
- Azure DevOps release pipeline version: 0.248.1
- The issue persists even after ensuring the deployment token and other configurations are correct.
- No API is being used in this deployment.

For further information, please visit the Azure Static Web Apps documentation and GitHub issues.

**Logs**

2025-04-01T06:51:41.0872512Z ##[error]An unknown exception has occurred 2025-04-01T06:52:01.1119123Z 2025-04-01T06:52:01.1124591Z ##[warning]For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/ 2025-04-01T06:52:01.1125085Z ##[warning]If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/ 2025-04-01T06:52:01.1125373Z ##[warning]Exiting 2025-04-01T06:52:01.1955808Z 2025-04-01T06:52:01.2002411Z ##[error]Error: The process '/usr/bin/bash' failed with exit code 1
