### ISSUE TITLE
benv: maven version 'true' not found.

### ISSUE THREAD

**Issue by Chonli** [Azure/static-web-apps#1641]
**Describe the bug**

The AzureStaticWebApp@0 task issue:

```
Digest: sha256:41473a2ebc45daa6e63c82a7f32a5680b0fe34dac49ab85dd6369c764b191308
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
benv: maven version 'true' not found.
benv: Could not find any versions on disk.
```

**To Reproduce**
Try to deploy a Flutter web application.
My azure devops pipeline looks like this.

```
      - task: AzureStaticWebApp@0
        inputs:
          app_location: 'releases_drop/release_web/build/web'
          output_location: 'releases_drop/release_web/build/web'
          azure_static_web_apps_api_token: $(apiKey)
          skip_app_build: true
          skip_api_build: true
```

How can I fix this issue? 
I don't understand why this task try to search maven path, because don't use it to build or deploy Flutter web App.
The version search is 'true', I think task don't like a environement variable but I don't the name of this variable.

**Comment by Chonli** [comment]
I finally found a solution by adding the Maven path to the task's environment.
```
      - task: AzureStaticWebApp@0
        inputs:
          app_location: 'releases_drop/release_web/build/web'
          output_location: 'releases_drop/release_web/build/web'
          azure_static_web_apps_api_token: $(apiKey)
          skip_app_build: true
          skip_api_build: true
        env:
          maven: /opt/maven/bin
```
