### ISSUE TITLE
Azure Static Web App + Next.js V15 [  Static HTML Export ]

### ISSUE THREAD

**Issue by gffelisberto** [Azure/static-web-apps#1657]
![Image](https://github.com/user-attachments/assets/f509f8e0-2a92-4dc9-ad58-e74742592fc2)

Attempt to build a fully static solution will fail since Oryx attemps to run next build && next export. However, it is important to mention that this was deprecated in favour of setting the property output to ` export ` in next.config.js as per: https://nextjs.org/docs/app/guides/static-exports

Also, the following is quite out-of-date at this point: 
https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs

Thank you.

**Comment by gffelisberto** [comment]
The bellow will work just fine and prevents using the standalone export mode. Would be nice to have the docs updated as well the build process to look for it on next.config.ts or next.config.js or next.config.mjs. 

Will give it a try again soon to see if was something else or a mistake while entering the values on basics [tab](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-static-export?tabs=github-actions#2-create-a-static-app)

Also the [demo](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-static-export?tabs=github-actions#1-set-up-a-nextjs-app) repository is using 12+ while the current version is 15+

```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - development
trigger:
  branches:
    include:
      - development

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: <__YOUR_CUSTOM_VALUE_HERE__>
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: <__YOUR_CUSTOM_VALUE_HERE__>
      app_location: "/out"  # Root of your app
      output_location: "out"  # Where Next.js outputs static files
      skip_app_build: true  # Prevent Oryx from running its own build
      is_static_web_app: true

```
