### ISSUE TITLE
Invalid workflow file (azure jekyll static web site)

### ISSUE THREAD

**Issue by thiagobeier** [Azure/static-web-apps#188]
hi there following the 

link [https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll](url)
I'm getting the following error

Check failure on line 20 in .github/workflows/azure-static-web-apps-nice-rock-0fe853010.yml
GitHub Actions
/ .github/workflows/azure-static-web-apps-nice-rock-0fe853010.yml

Invalid workflow file
You have an error in your yaml syntax on line 20

**workflow file**
[azure-static-web-apps-nice-rock-0fe853010.txt](https://github.com/Azure/static-web-apps/files/5436783/azure-static-web-apps-nice-rock-0fe853010.txt)
**error**
![azrgit1](https://user-images.githubusercontent.com/5958695/97133963-0b3ff580-1722-11eb-8e59-1f2e996b5976.png)
**running locallly**
![azrgit2](https://user-images.githubusercontent.com/5958695/97133966-0b3ff580-1722-11eb-9731-3c43693f3056.png)

**Comment by miwebst** [comment]
I believe this is a problem with your indentation. The 'uses' keyword should be inline with the 'name' keyword. You can see an example of this here: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll#review-and-create

**Comment by anthonychu** [comment]
Looks like the problem here is the instruction:

> 5. After the line `- uses: actions/checkout@v2` add the following configuration block.

The GitHub action now includes the "with submodules: true" lines as shown below, so the instruction needs to be updated to reflect this. I'm not sure the best way to change this, perhaps change the instruction to:

> 5. Before the line `- name: Build And Deploy` add the following configuration block.

But there are 2 lines with the words "Build and Deploy", and the value is a literal so it might change in the future. Also the indentation with the pasted yaml is challenging to get right. @craigshoemaker any thoughts on this?

```yaml
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_WAVE_01C8EE01E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "frontend" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```
