### ISSUE TITLE
No matching static site was found or the api key was invalid.

### ISSUE THREAD

**Issue by theeKatlego** [Azure/static-web-apps#198]
Hi, I get the following error 

`The content server has rejected the request with: BadRequest
Reason: No matching static site was found or the api key was invalid.`

I've changed the structure of the repo by moving the project into a subfolder. I then updated the workflow. I did not make any changes on the static web app on Azure.
[rickvandenbosch](https://www.rickvandenbosch.net/blog/azure-static-web-apps-quirks-gotchas/) says this also happens when changing branch names. Note that I did not change the branch name.

**Workflow file**
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:        
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/
    - name: yarn install and build
      run: |
        cd zoza-communications
        yarn install
        yarn build    
    - name: Deploy
      id: deploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ ***** }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "zoza-communications" # App source code path
        api_location: "api" # Api source code path - optional
        app_artifact_location: "dist/" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ **** }}
          action: "close"
```

repo - https://github.com/theeKatlego/zoza-communications
