### ISSUE TITLE
static-web-apps-deploy test step in github action

### ISSUE THREAD

**Issue by dsurrao** [Azure/static-web-apps#229]
To deploy an Angular app, I would like to add a step 'npm test' or 'ng test'. I tried adding this before the 'Build and Deploy' step in the workflow .yaml file, but the job takes a long time and does not seem to complete. Is there another way to do this? Thanks.

```
- name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install and test
        run: |
          # Build and test the project
          npm install
          npm run test --if-present
      - name: Build And Deploy
        ..
```
