### ISSUE TITLE
Angular build fails with "sh: 1: ngcc: not found"

### ISSUE THREAD

**Issue by jepetko** [Azure/static-web-apps#231]
Angular build fails with "sh: 1: ngcc: not found"

This is because `npm install --unsafe-perm --production` is executed to install the dependencies (no dev dependencies installed, thus `ngcc` (Ivy compiler) is missing).

Log file:

```

Installing production dependencies in '/github/workspace/.oryx_prod_node_modules'...

Running 'npm install --unsafe-perm --production'...


> my-repo@0.0.0 postinstall /github/workspace/.oryx_prod_node_modules
> ngcc

sh: 1: ngcc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! my-repo@0.0.0 postinstall: `ngcc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the my-repo@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

`app_build_command: npm i --unsafe-perm && npm run build` does not help if `ngcc` is configured like this: `"postinstall": "ngcc"`. It fails during the "npm install" phase initiated by the Azure build itself (`Azure/static-web-apps-deploy@v0.0.1-preview`).

A workaround might be to move all `devDependencies` to the `dependencies` section.

What is the recommended solution here?

**Comment by anthonychu** [comment]
@shmool recently ran into the same thing. @shmool @johnpapa @manekinekko any thoughts on best way to resolve this?

**Comment by shmool** [comment]
I moved two dependencies from `devDependencies` to `dependencies`: `typescript` and `@angular/compiler-cli`. 
However, I think the solution should come from Angular. If `ngcc` is needed - we should have it by default in the dependencies, already compiled to JavaScript. I'll reach out to the Angular team.

**Comment by joelcoxokc** [comment]
This is not an issue with ngcc. 
I am unable to get any command to run in a postinstall.

**Comment by joelcoxokc** [comment]
Can you please allow us to have an install command before the build runs?

This way I can install the necessary dependencies manually, or at least prevent postinstall from running.

**Comment by manekinekko** [comment]
Hey @joelcoxokc thank you for reporting this behavior.

You can use the `PRE_BUILD_COMMAND` env var and provide a script that would run before the build is triggered:

```yaml
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_WAVE_04EEA641E }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        app_location: '/'
        api_location: 'api'
        app_artifact_location: 'dist/static'
      env:  
        PRE_BUILD_COMMAND: './scripts/setup-puppeteer.sh'
```

See an example here with a Scully app: https://github.com/manekinekko/scully-swa/blob/master/.github/workflows/azure-static-web-apps-orange-wave-04eea641e.yml#L31

**Comment by oidacra** [comment]
> Angular build fails with "sh: 1: ngcc: not found"
> 
> This is because `npm install --unsafe-perm --production` is executed to install the dependencies (no dev dependencies installed, thus `ngcc` (Ivy compiler) is missing).
> 
> Log file:
> 
> ```
> 
> Installing production dependencies in '/github/workspace/.oryx_prod_node_modules'...
> 
> Running 'npm install --unsafe-perm --production'...
> 
> 
> > my-repo@0.0.0 postinstall /github/workspace/.oryx_prod_node_modules
> > ngcc
> 
> sh: 1: ngcc: not found
> npm ERR! code ELIFECYCLE
> npm ERR! syscall spawn
> npm ERR! file sh
> npm ERR! errno ENOENT
> npm ERR! my-repo@0.0.0 postinstall: `ngcc`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the my-repo@0.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```
> 
> `app_build_command: npm i --unsafe-perm && npm run build` does not help if `ngcc` is configured like this: `"postinstall": "ngcc"`. It fails during the "npm install" phase initiated by the Azure build itself (`Azure/static-web-apps-deploy@v0.0.1-preview`).
> 
> A workaround might be to move all `devDependencies` to the `dependencies` section.
> 
> What is the recommended solution here?

You fix this problem? Im still with the same problem.

**Comment by jepetko** [comment]
@oidacra actually, the only solution was to move devDependencies to dependencies. 

BTW, I also tried to do this (see https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow for more information):

```
          app_build_command: npm i --unsafe-perm && ng build --prod
```

This did not help either as Azure is always prepending the "npm i" phase (containing the `--production` switch).

**Comment by oidacra** [comment]
> @oidacra actually, the only solution was to move devDependencies to dependencies.
> 
> BTW, I also tried to do this (see https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow for more information):
> 
> ```
>           app_build_command: npm i --unsafe-perm && ng build --prod
> ```
> 
> This did not help either as Azure is always prepending the "npm i" phase (containing the `--production` switch).

Thanks... I'll try this option.

**Comment by jepetko** [comment]
It's not nice to have dev dependendencies in the actual (runtime) dependencies but angular will not involve them in the compilation as they are not referenced in the compiled (and packaged) code (no import/require command). Thus, the dev dependencies code is not served by browser anyway.

**Comment by georgyevv** [comment]
I have the same issue:

Running 'npm install --unsafe-perm --production'...


> core-js@3.8.2 postinstall /github/workspace/.oryx_prod_node_modules/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> platform@0.0.0 postinstall /github/workspace/.oryx_prod_node_modules
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && node ./decorate-angular-cli.js

sh: 1: ngcc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! platform@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && node ./decorate-angular-cli.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the platform@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-01-18T00_32_11_942Z-debug.log

Any solution?

**Comment by vazsonyidl** [comment]
Is there any update on this issue? 
Until then, adding typescript and compiler-cli to dependencies is the solution for this? 

Tanks in advance.

**Comment by manekinekko** [comment]
Can you try this config (see the `env` section)?

```yaml
       with:
         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_WAVE_04EEA641E }}
         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
         action: 'upload'
         app_location: '/'
         api_location: 'api'
         app_artifact_location: 'dist/static'
       env:  
         DISABLE_NODEJS_BUILD: true
         CUSTOM_BUILD_COMMAND: 'npm ci' 
         RUN_BUILD_COMMAND: 'npm run build -- --prod'
 ```
