### ISSUE TITLE
My jekyll website isn't building, but Oryx knows it's a ruby project

### ISSUE THREAD

**Issue by krainboltgreene** [Azure/static-web-apps#253]
I've tried a myriad of different things:

  1. The original created workflow didn't work
  2. I tried telling it to look in `_site/` for `output_location`
  3. I've tried putting `_site`, `/_site/`, `/_site` for `app_location`
  4. I've tried setting the `app_build_command` to `"bundle exec jekyll build"`

None of these have solved the issue and there's really not a lot of helpful output.

Here's the latest run: https://github.com/krainboltgreene/hcjustin-unrulybabs-funathon/runs/1638375408?check_suite_focus=true

Here's the workflow: https://github.com/krainboltgreene/hcjustin-unrulybabs-funathon/blob/main/.github/workflows/azure-static-web-apps-lemon-desert-024e84a10.yml

**Comment by anthonychu** [comment]
I think Oryx only knows how to build Rails apps for App Service. Can you try it with an explicit build step outlined in this tutorial? https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll

(Note that there's an instruction that's not quite right `After the line - uses: actions/checkout@v2 add the following configuration block.`, make sure you add that snippet after the `submodules: true` line instead)

@miwebst @arroyc What are our plans to build Jekyll automatically?

**Comment by krainboltgreene** [comment]
Yeah I saw two different documentation pages on Oryx's configuration, both had inconsistencies with what was generated for me (not that I'm surprised, a preview build and all).

I guess I'm confused, you want me to add a step to build jekyll *before* the self-described `Build and Deploy` step? This all seems very strange since all I need oryx to do is actually run the `app_build_command`, when instead it halts complaining there aren't any artifacts to upload *before it's actually tried to build the artifacts*.

**Comment by anthonychu** [comment]
Can you point me to the Oryx docs that you're seeing this?

@miwebst @arroyc will be better able to speak to the issues with Oryx and Jekyll. But yes, the official guidance is to build Jekyll separately for now and only use the Static Web Apps action to deploy.

**Comment by krainboltgreene** [comment]
https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow#build-and-deploy is the one where I was introduced to `app_build_command` and `app_artifact_location` (which I also tried).

**Comment by krainboltgreene** [comment]
Ah, I see what you're telling me to do now. It's a hack, you homebrew the build, then hand ASWA the static stuff pretending it isn't even ruby, clever.

**Comment by krainboltgreene** [comment]
Oof, looks like that ruby install action from the docs has bad stuff: https://github.com/krainboltgreene/hcjustin-unrulybabs-funathon/runs/1641565496?check_suite_focus=true

I think I'm on the right track at least.

**Comment by EntityAdam** [comment]
Came here because https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll wasn't working

I understand from this thread that Jekyll actually isn't supported as advertised.  Bummer.

The work-around wasn't obvious from the conversation. Wut 'following configuration block'?

> (Note that there's an instruction that's not quite right After the line - uses: actions/checkout@v2 add the following configuration block., make sure you add that snippet after the submodules: true line instead)

Luckily I was able to pull it out of @krainboltgreene's repo (Thanks for that) and one additional detail I had to figure out elsewhere. I'll detail it more clearly here:

With the workflow generated by the Azure Static Site, the intent is to build the `app_location`, however as pointed out earlier, it doesn't know how to build Jekyll yet. So the work-around is to build the site first, then let the `Azure/static-web-apps-deploy@v1` task upload the result.

First, to take control of the build process, you'll need to install Ruby, Bundler and then run the command `bundle exec jekyll build`

So from the generated file after the checkout task and before the build and deploy task, insert your own build instructions:

```yaml
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Jekyll build
        run: bundle exec jekyll build
      - name: Build And Deploy
        id: builddeploy
        ...
```
So now that we've taken control of the build process, your `app_location` will be the destination of the `bundle exec jekyll build` output, which is by default `/_site`

```yaml
app_location: "/_site" # App source code path
```

Now for the last fun bit, I had a `package.json` file in my source that came from installing a theme. According to the docs Oryx is still going to run `npm install` and if specified in a `package.json` file, it's going to try and run `npm run build`, and `npm run build:azure` So it found a `package.json` file, but no build commands were in there, so it threw this error:

```
Detecting platforms...
Detected following platforms:
  nodejs: 14.18.3
Version '14.18.3' of platform 'nodejs' is not installed. Generating script to install it...
Error: Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.Could not find tools for building monorepos, no 'lerna.json' or 'lage.config.js' files found.
```

So I finally stumbled on another setting, `skip_app_build`. Once I plugged that into the workflow, it resolved the issue.

```yaml
        uses: Azure/static-web-apps-deploy@v1
        with:
          ...
          action: "upload"
          app_location: "/_site" # App source code path
          api_location: "" # Api source code path - optional
          skip_app_build: true
```

**Comment by dalvaren** [comment]
@EntityAdam , your solution worked very well, the only point I had to add to the build instructions was to also install the Bundler.

```
 steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Jekyll build
        run: bundle exec jekyll build
      - name: Build And Deploy
        id: builddeploy
        ...
```

**Comment by lordcheeto** [comment]
It's kind of wild that this is still broken 3 years later, when ASWS claims to natively support Jekyll with a build preset when you configure a static web app. Current build configuration that works:

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Bundler
        run: gem install bundler
      - name: Jekyll build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_EXAMPLE_EXAMPLE_EXAMPLE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/_site" # App source code path
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_EXAMPLE_EXAMPLE_EXAMPLE }}
          action: "close"
```

Changes: 
* Uses  `ruby/setup-ruby@v1`, since ``actions/setup-ruby@v1` was deprecated.
* Uses `bundler-cache: true`, which will run `bundle install` and caches gems.
* Uses a [.ruby-version](https://github.com/ruby/setup-ruby/blob/master/.ruby-version) file in the repo instead of specifying the version in the action.
* Adds [`JEKYLL_ENV: production`](https://jekyllrb.com/docs/configuration/environments/) to the environment when building.
