### ISSUE TITLE
Error occurs when zipping api artifacts

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [Azure/static-web-apps#273]
I'm getting the following error message when building my app:

```
---End of Oryx build logs---
Function Runtime Information. OS: Linux, Functions Runtime: v3, Node version: 12.X
Finished building function app with Oryx
Validated and moved 'routes.json' from 'assets' to '/' within the build artifacts folder.
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
An error occurred while zipping the api artifacts: Could not find file '/bin/staticsites/ss-oryx/api/node_modules/.bin/prebuild-install'.
This error may be due to a broken symbolic link. Please review the build logs for any warnings or errors

An unknown exception has occurred while uploading
```

This only happened after I started using @azure/identity and @azure/keyvault-secrets packages.

Here's my workflow file that is failing:

```yml
name: Deploy Reference App

on:
  push:
    branches:
      - master
    paths:
      - 'projects/reference-app/**'
      - 'projects/_common/**'
      - 'projects/deskdirector-api/**'
      - 'projects/http/**'
      - 'projects/models/**'
      - '.github/workflows/**'
      - 'api/**'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig/
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          echo "test message, path: $PKG_CONFIG_PATH"
          apt list pkg-config
          apt list libsecret-1-dev
          dpkg -L libsecret-1-dev
      - name: Update package registry
        run: sudo apt-get update -y
      - name: Install pkg-config (for @azure/identity dependency)
        run: sudo apt-get install -y pkg-config
      - name: Install libsecret-1-dev (for @azure/identity dependency)
        run: sudo apt-get install libsecret-1-0 libsecret-1-dev
      - name: Build And Deploy
        id: builddeploy
        env:
          NODE_VERSION: '12'
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_BUSH_0F4937C1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: 'api' # Api source code path - optional
          output_location: 'dist/reference-app' # Built app content directory - optional
          app_build_command: 'npm run build:reference-app'
          ###### End of Repository/Build Configurations ######
```

There are a few other errors that occur when it tries to build the functions that use these packages:

```
Detecting platforms...
Detected following platforms:
  nodejs: 12.19.0


Source directory     : /github/workspace/api
Destination directory: /bin/staticsites/ss-oryx/api


Using Node version:
v12.19.0

Using Npm version:
6.14.8

Installing production dependencies in '/github/workspace/api/.oryx_prod_node_modules'...

Running 'npm install --unsafe-perm --production'...


> keytar@5.6.0 install /github/workspace/api/.oryx_prod_node_modules/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/tmp/oryx/platforms/nodejs/12.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-1032-azure
gyp ERR! command "/tmp/oryx/platforms/nodejs/12.19.0/bin/node" "/tmp/oryx/platforms/nodejs/12.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /github/workspace/api/.oryx_prod_node_modules/node_modules/keytar
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN api@1.0.0 No description
npm WARN api@1.0.0 No repository field.
npm WARN api@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@5.6.0 (node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@5.6.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
added 65 packages from 165 contributors and audited 132 packages in 3.562s
```

It seems to zip the app artifacts without problem, it seems like the api code cannot be zipped.

Let me know if you need more information or anything.

Thanks!
