### ISSUE TITLE
App Directory Location is invalid when using a downloaded artifact

### ISSUE THREAD

**Issue by Valks** [Azure/static-web-apps#277]
I have a problem when running the static-web-apps-deploy task and using a downloaded artifact.

I'm building my project on a windows image, uploading it then using a linux image to publish to static web apps (doesn't support windows agent).

I'm using windows because I have tools which aren't supported on linux (yet).

After building and publishing my project (Blazor) I upload the artifact:

```yaml
      - uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: artifacts/<ProjectName>/**/*
          retention-days: 1
```

then in the next job on the next agent I download the artifact then try to deploy:

``` yaml
  deploy_job:
    needs: build_job
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - name: Download Artifacts
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: build_artifacts

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_MUD_028353000 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ steps.download_artifact.outputs.download-path }} # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'wwwroot' # Built app content directory - optional
          ###### End of Repository/Build Configurations ###### 
```

After looking at the logs and docs I assume it's creating a symlink to ```/github/workspace``` based on ```app_location``` then run it's commands from there. For some reason it doesn't seem to work.

Here is the log from the build agent:
```
/usr/bin/docker run --name e4c5c4aa4bd2adb8de95019d112a_f6e3f6 --label 442333 --workdir /github/workspace --rm -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_OUTPUT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/<ProjectName>/<ProjectName>":"/github/workspace" 442333:1798e4c5c4aa4bd2adb8de95019d112a
DeploymentId: de3fea9e-46c5-4f32-9e91-43f5fc671d95

App Directory Location: '/github/workspace' is invalid. Could not detect this directory. Please verify your workflow reflects your repository structure.
```

Note: <ProjectName> gives the correct value and path as per the artifact download task.

**Comment by miwebst** [comment]
Hey @Valks interesting use case! Is it possible for you to echo out the value of the download-path output? Curious if it is just '/github/wokspace' as the log above suggests. Our logic may be looking for this file in the wrong place as we don't expect an absolute path for our inputs.

**Comment by Valks** [comment]
I guess it's something to do with the path been forced relative to ```/github/workspace``` instead of treating it as an absolute path. ```${{ steps.download_artifact.outputs.download-path }}``` resolves to a folder path: ```/home/runner/work/<ProjectName>/<ProjectName>```

When you list the contents you get the following:
```
Run ls -la /home/runner/work/<ProjectName>/<ProjectName>
  ls -la /home/runner/work/<ProjectName>/<ProjectName>
  shell: /bin/bash -e {0}
total 16
drwxr-xr-x 3 runner docker 4096 Feb  3 03:35 .
drwxr-xr-x 3 runner docker 4096 Feb  3 03:34 ..
-rw-r--r-- 1 runner docker 1705 Feb  3 03:35 web.config
drwxr-xr-x 5 runner docker 4096 Feb  3 03:35 wwwroot
```

I might try running it again with ../../ and see if it finds the folder

**Comment by Valks** [comment]
Well I found a solution.

The download task puts the files in the same location as the git checkout command. This lead me to try setting the app_location to ''.

That worked in that it found the base folder but failed during the final step because it couldn't find the artifacts (output_location was set to 'wwwroot')
```
Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

So I then set the app_location to 'wwwroot' and output_location to '' and it worked.

I'll let you decide what's best but it's worth documenting (I still feel the absolute path felt more correct).

**Comment by the-mikael-johansson** [comment]
I'm using multi-stage pipelines in YAML files and also had this issue. Here is how i solved it:

I had to download the artifact manually by using DownloadPipelineArtifact@2 instead of using the auto-created task that downloads to Pipeline.Workspace (/home/vsts/work/1/). By downloading the artifact to a relative path and use that relative path (relative to the task's execution path) I could re-use my artifact and deploy it without need of re-building it.

Here is my CD stage pipeline (ubuntu):
```
steps:

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop
      path: ./rel-drop
      displayName: "Download artifacts"

  - task: AzureStaticWebApp@0
    displayName: Deploy Web App
    inputs:
      app_location:  './rel-drop/build/'
      skip_app_build: true
      azure_static_web_apps_api_token: $(DeploymentTokenSecret)

```

**Comment by srmagura** [comment]
I am using `AzureStaticWebApp@0` and it works when `app_location` is a relative path, but not when it is an absolute path. This seems like a bug to me.

**Comment by anthonychu** [comment]
> I am using `AzureStaticWebApp@0` and it works when `app_location` is a relative path, but not when it is an absolute path. This seems like a bug to me.

The task expects those locations to be relative to the working directory. This is already mentioned briefly in the docs but I think we can make this more prominent.

**Comment by sandeep-bhaskar** [comment]
I am using the below yaml and i want to build the app. I don't want to push the dist file to my repo and i am getting below error 

```
 
 - task: AzureStaticWebApp@0
    inputs:
      app_location: '/src/myapp'
      app_build_command: 'npm run build'
      api_location: ""
      output_location: "dist" # Built app content directory - optional
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
```
```
Failed to find a default file in the app artifacts folder (dist). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your deployment configuration file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```
