### ISSUE TITLE
Webpack build failed on Action

### ISSUE THREAD

**Issue by timtong1982** [Azure/static-web-apps#279]
The action build failed on pull request trigger:

error:
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'React' in '/github/workspace/src'
    at /github/workspace/node_modules/webpack/lib/Compilation.js:1657:28
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:708:13
    at eval (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:632:24
    at /github/workspace/node_modules/webpack/lib/NormalModuleFactory.js:781:5
    at finishWithoutResolve (/github/workspace/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
resolve 'React' in '/github/workspace/src'

webpack.config.js
```js
      output: {
            path: root('./dist'),
            filename: 'app.bundle.js',
            chunkFilename: '[id].js',
        },
     resolve: {
            modules: ['node_modules', root('./src')],
            extensions: ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.mjsx'],
        },
```

package.json
```json
    "scripts": {
        "dev": "webpack serve --config ./webpack.config.js --env isProd=false --env runDevServer=true --progress --hot --inline",
        "build": "webpack --config ./webpack.config.js --env isProd=true --env runDevServer=false --bail --progress"
    },
    "dependencies": {
        "react": "17.0.1",
        "react-dom": "17.0.1",
        "use-context-selector": "1.3.7"
    },
```

builder yml
```yml
         uses: Azure/static-web-apps-deploy@v0.0.1-preview
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_GLACIER_0A774B30F }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: '/' # App source code path
                  output_location: 'dist' # Built app content directory - optional
                  app_build_command: 'npm run build'
                  ###### End of Repository/Build Configurations ######
```
