### ISSUE TITLE
Yarn 2 error building - The --prefer-offline flag is deprecated

### ISSUE THREAD

**Issue by caitlinwillmot** [Azure/static-web-apps#287]
After upgrading my react-create-app to Yarn 2 the following error occurs in the Build and Deploy job:

![image](https://user-images.githubusercontent.com/74575035/108310061-6b413700-71fe-11eb-8ab2-3441d5a62896.png)

If a project is running Yarn 2 the command that should be used to install packages is 'yarn add --cached'

**Comment by svict4** [comment]
https://github.com/microsoft/Oryx/issues/895 is related

**Comment by anthonychu** [comment]
@arroyc to investigate and provide temporary workaround if there is one.

**Comment by qianz2** [comment]
Here is a temporary workaround that works for the above issue: use CUSTOM_BUILD_COMMAND flag, which can skip running package install command and run the custom build command provided, in this case `yarn add --cached`.

**Comment by chriswoodle** [comment]
Hello, I'm having similar issue,
I'm using `Azure/static-web-apps-deploy@v0.0.1-preview`

I've tried using the CUSTOM_BUILD_COMMAND workaround described by @qianz2 (I've tried setting it to `yarn install` and `yarn add --cached`, with and without the "" quote marks):

![image](https://user-images.githubusercontent.com/11614325/109604680-eacde080-7af1-11eb-923d-fc9a62c58c7f.png)

But it does not seem to effect it.

![image](https://user-images.githubusercontent.com/11614325/109604841-32ed0300-7af2-11eb-8b6b-43e1c45218af.png)

I can see the environment variable being passed in, might there be some reason why it's not making it to Oryx?

![image](https://user-images.githubusercontent.com/11614325/109606416-a5f77900-7af4-11eb-89ba-ad80cb5a7f33.png)

**Comment by chriswoodle** [comment]
I've also tried to bypass the `Installing production dependencies ...` section here: https://github.com/microsoft/Oryx/blob/616edfb98a95927f0c31bc056f94a16fb18dcdcd/src/BuildScriptGenerator/Node/NodeBashBuildSnippet.sh.tpl#L46
by setting `PRUNE_DEV_DEPENDENCIES` but that does not seem to do anything either.

**Comment by Itrel** [comment]
I am also encountering the yarn2 problem @caitlinwillmot  mentioned. My attempts to pass in a CUSTOM_ BUILD_COMMAND is having the same problem @chriswoodle encountered. 

The Oryx version in my build log is

Oryx Version: 0.2.20210225.1, Commit: ac3044e35d3dc78dce05ba4d552bbe144029a673, ReleaseTagName: 20210225.1

It was released 11 days ago (March 24)

Chri's Oryx log shows 0.2.20201112.1 which was released Nov 12, 2020


The latest Oryx release with Yarn 2 fixes is https://github.com/microsoft/Oryx/releases/tag/exp-20210306.4 and was released March 6, 2021.

When will Azure/static-web-apps-deploy@v0.0.1-preview be updated to use Oryx version exp-20210306.4 ?

**Comment by arroyc** [comment]
@Itrel  This is not an official release from Oryx .. as the tag name says it's experimental and intended for internal testing purpose. I would recommend waiting for the official build. It will be there soon.

**Comment by arroyc** [comment]
@Itrel  we have an official release .. hope it will be soon updated in static web sites as well. https://github.com/microsoft/Oryx/releases

**Comment by Itrel** [comment]
Excellent! Thank you very much. 

Which repo/team should I go look at for the static web sites build container 
Azure/static-web-apps-deploy@v0.0.1-preview

I thought this repo team would take care of updating that container image as well as the Oryx functionality.

**Comment by arroyc** [comment]
you are in the right place/repo .... i would just wait for their confirmation on updating their side...  @anthonychu

**Comment by anthonychu** [comment]
For the Static Web Apps action, we integrate upstream changes from Oryx regularly and perform our own testing before releasing it. We don't have an exact ETA on when those changes will be available.

@Itrel For now, you can update your workflow to build your app in a separate step, and use the Static Web Apps GitHub action to deploy the app. To do this, set the `app_location` property of the action to the yarn build output. Also set `skip_app_build` to `true`.

**Comment by miwebst** [comment]
This should be fixed now.

**Comment by bertearazvan** [comment]
I am encountering the same issue. I checked out the implementation from Oryx with yarn 2 and I noticed it checks for the `yarn.lock file` in order to detect its version. With yarn 2 you can define workspaces, and it's not mandatory that there is a lock file in the root of the subfolders but instead in the root of the repo. My folder structure has an "app" and "api" folder, and when I install dependencies the yarn.lock is at the root of the repo, and not in the "api" folder. 

I want to skip the build for the app, and only build the api through this action. Oryx does not detect properly the version of yarn 2. A solution for oryx could be instead instead to look up for the "engines" yarn version from package.json of the respective folder you want to publish.

My current folder structure
```
root
|-- node_modules
|-- .yarnrc.yml
|--  package.json
|-- .yarn/
|-- api
     |-- tsconfig.json
     |-- package.json
     |-- host.json
     |-- route1
     |-- route2
     |-- dist
|-- app 
     |-- staticwebapp.config.json
     |-- package.json
     |-- src   
     |-- dist
```

workflow

```
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          CUSTOM_BUILD_COMMAND: "yarn add --cached"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_FIELD_0D0B73E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "app/dist" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: ""
          skip_app_build: true
          api_build_command: "yarn run build:api"
          ###### End of Repository/Build Configurations ######
```

Where `CUSTOM_BUILD_COMMAND` is completely ignored
