### ISSUE TITLE
Source code for StaticSitesClient ?

### ISSUE THREAD

**Issue by StefH** [Azure/static-web-apps#306]
Is the source-code from the StaticSitesClient (which is used in docker image mcr.microsoft.com/appsvc/staticappsclient:stable) public?

And where to find this?

**Comment by anthonychu** [comment]
@StefH This component is currently not open source.

**Comment by StefH** [comment]
Will it be when it's ready to use in DevOps pipeline?

**Comment by anthonychu** [comment]
The task is rolling out. You'll be able to create a Static Web App in the portal without GitHub sometime in March. It'll depend on the portal deployment schedule.

**Comment by StefH** [comment]
Wil that also mean that Azure Static WebApps itself will be out of preview around that time?

And may I ask why the GitHub action was available earlier?

**Comment by anthonychu** [comment]
We still have more to do before we can GA.

As for why GitHub Actions was supported first, we had to pick one for the public preview and felt that GitHub Actions allows us to reach more people in our target audience (some of whom are not Azure customers) which, in turn, has allowed us to collect the feedback needed to shape our product.

Closing this issue, but keep an eye on #5 for Azure DevOps support.

**Comment by bkarstaedt** [comment]
Instead of using the limited `StaticSitesClient` docker container I went over to use the [SWA CLI](https://azure.github.io/static-web-apps-cli/) to [deploy](https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy#options) an Azure Static Web App, because I can also easily deploy to specific (preview) environments.

**Comment by lanterno** [comment]
@bkarstaedt Thanks for sharing about the "SWA CLI". 

 I had to follow on the same path as I'm using `Bun` instead of NPM which causes all kinds of trouble. 
Here's a snippet of my github action:

```
jobs:
  build_and_deploy_static_site:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.DOMAIN }}
    name: Deploy to Dev Environment
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate static site
        run: bun run generate
      - name: Install Azure Static Web Apps CLI
        run: bun install -g @azure/static-web-apps-cli
      - name: Deploy to Azure Static Web Apps
        run: swa deploy dist --deployment-token ${{ secrets.AZURE_STATIC_SITE_TOKEN }} --env production

```
