### ISSUE TITLE
Option to use Hugo Extended

### ISSUE THREAD

**Issue by chrisreddington** [Azure/static-web-apps#322]
There is functionality in the static-web-apps GitHub Action to select which version of Hugo you would like to use. However, there is not a property to determine whether you would like Hugo or Hugo Extended. 

Hugo Extended is used if you plan to use SASS/SCSS in your Hugo theme. I've made a custom theme for my site, so have this as a requirement (per Hugo Community - https://discourse.gohugo.io/t/should-i-use-hugo-extended-for-a-new-hugo-project/13954/6)

The workaround (thanks @anthonychu), was to build using the steps I'm already using to compile the files for deployment to Azure Storage's Static Sites, but in the static-web-apps GH action set the app_location to the build output from the previous step, and set skip_app_build to true.

Here are some examples of my workflows:

- [Building and Deploying to Azure Storage Static Sites](https://github.com/chrisreddington/cloudwithchris.com/blob/master/.github/workflows/master.yaml)
- [Building and Deploying to Azure Static Web Apps](https://github.com/chrisreddington/cloudwithchris.com/blob/master/.github/workflows/azure-static-web-apps-gray-beach-021c69b03.yml)

**Comment by kolappannathan** [comment]
It would be nice of Azure adds an option for this. I ended up modifying the build script I was using for Firebase. Here is the workflow file if anyone is interested.

It is simpler script and doesn't include previews for PR. If you need that functionality 
refer to @chrisreddington workflow file.

```
name: Azure Static Web Apps CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Installing Hugo 0.91.2
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.91.2_Linux-64bit.deb
          hugo version
      - name: Building site
        run: |
          cd ./src
          hugo --minify
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_FOREST_040213F00 }}
          action: "upload"
          # For more info: https://aka.ms/swaworkflowconfig
          app_location: "/src/public" # output directory after the hugo build
          skip_app_build: true
```
