### ISSUE TITLE
No framework deploy fails on 'Failed to find a default file in the app artifacts folder'

### ISSUE THREAD

**Issue by kaylumah** [Azure/static-web-apps#341]
I have an app without any framework. It generates html, js, css etc in a folder called dist.

Before uploading I used certain npm scripts to optimize the html/css before publishing.
After optimizing I remove "node_modules" from this dist folder since there is no use in uploading or pushing it.

The build then fails on Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
and it does not mention my dist folder at all.

```
DeploymentId: 37d74626-d6b3-4281-95fd-c73c47032ea9

App Directory Location: '/' was found.
[WARNING] Api Directory Location: 'api' could not be found. Azure Functions will not be created.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20210225.1, Commit: ac3044e35d3dc78dce05ba4d552bbe144029a673, ReleaseTagName: 20210225.1

Build Operation ID: |5IUUBSW/nvI=.c0442e14_
Repository Commit : e4d0304368d83e49aca564610966d4283d9654da

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

The generated yaml by Azure is configured like this:

```yaml
 # custom steps to populate the dist folder
  - name: Process
        run: |
          cd dist
          npm i
          npm run build:prod
          rm styles.css
          rm -rf node_modules
          ls
 - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_FIELD_03518B503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/ # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

The result from the `ls` command is

```
2019
2020
2021
404.html
assets
blog.html
compiled.css
feed.xml
index.html
package-lock.json
package.json
postcss.config.js
projects.html
robots.txt
sitemap.xml
tailwind.config.js
```

which clearly contains a index.html

Any help on what I am doing wrong would be appreciated.
