### ISSUE TITLE
AzureStaticWebApp building a Jekyll site fails

### ISSUE THREAD

**Issue by nathankitchen** [Azure/static-web-apps#359]
I've been trying to use the AzureStaticWebApp build step with a Jekyll site. It has been "working" until recently, but only because I could only make it work by building the site myself first. Here's the relevant part of my pipeline:

``` yaml
variables:
   BUNDLE_PATH: ./vendor/bundle

steps:
 - task: UseRubyVersion@0
   inputs:
      versionSpec: '>= 3.0'

 - task: Cache@2
   inputs:
      key: 'bundle | "$(Agent.OS)" | Gemfile'
      restoreKeys: | 
         bundle | "$(Agent.OS)"
         bundle
      path: $(BUNDLE_PATH)
   displayName: Cache gems

 - script: |
      gem install jekyll bundler
      bundle install --retry=3 --jobs=4
   displayName: 'Bundler'
 
 - script: |
      bundle install
      bundle exec jekyll build JEKYLL_ENV=production
   displayName: 'Jekyll'

 - task: AzureStaticWebApp@0
   inputs:
      app_location: "/"
      api_location: "api​"
      output_location: "__www"
   env:
      azure_static_web_apps_api_token: $(deploymentToken)
```

The pipeline works fine but the AzureStaticWebApp step fails on several counts:

 1. It's somehow detecting Java, I have no idea why.
 2. It's installing Ruby 2.7 instead of 3.0, and again I don't know why/what is controlling this.
 3. It detects Jekyll but `jekyll build` fails with "command not found", presumably because it should be running `bundle exec jekyll build`

Thing is, I could quite legitimately be wanting to pass a ton of other overrides to the build command (environment, different _config.yml) but I don't understand how I'm supposed to do that.

My "fix" is to try deleting the source code and just leaving the __www folder (I prefer __www to _site because of folder order) so that Oryx doesn't "detect" stuff and then fail. These kinds of workarounds probably aren't your expected usage so thought I'd flag the problems I've encountered with an issue.

Perhaps I am missing some Oryx docs that specify standardised build scripts, entry points, and dependencies?

**Comment by anthonychu** [comment]
We will attempt to build what's in the `app_location`. We recently added the ability to build Jekyll apps automatically. If you want to just deploy the output in `__www`, try changing the task inputs to the following (sounds like you might have discovered this solution already):

```yaml
 - task: AzureStaticWebApp@0
   inputs:
      app_location: "__www"
      api_location: "api​"
      output_location: ""
   env:
      azure_static_web_apps_api_token: $(deploymentToken)
```

Looks like you've discovered a couple of issues with the built-in Jekyll build script. We'll make the necessary adjustments.
