### ISSUE TITLE
[feedback]Oryx Build Fail,when deploy a H5/JS job to AzureStaticWebApp

### ISSUE THREAD

**Issue by yangyx91** [Azure/static-web-apps#365]
recent days,this "Azure Static Web Apps CI/CD" occur fail,when it do build and deploy job. so i had to leave this feedback,please help check it.

and my github program is a native html5 and javascript static website，"https://github.com/yangyx91/axiangblog"

here is this workflow error information:

 "Jekyll 4.2.0   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. "

if possible, please contact me for more information
![bug1](https://user-images.githubusercontent.com/11272259/114653344-6ab6af80-9d1a-11eb-8a4e-05fe358b3682.jpg)
![bug2](https://user-images.githubusercontent.com/11272259/114653359-74d8ae00-9d1a-11eb-9a7b-7461458c9a8a.jpg)

 .

**Comment by anthonychu** [comment]
We recently added support for building Jekyll apps. Your site contains a `_config.yml` file, which causes our build engine to detect your site as Jekyll and perform the build steps for Jekyll.

If you just want to deploy the site without a build, either remove the `_config.yml` File, or add the `skip_app_build` property to the workflow file like this:

```yml
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      app_artifact_location: ""
      skip_app_build: true
```
