### ISSUE TITLE
Support passing environment variables to Azure DevOps task

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#392]
https://stackoverflow.com/questions/67307614/azure-static-web-app-nodejs-env-variables

**Comment by Perry-Qian** [comment]
The problem is below:

I'm using Azure Static Web App service and Azure DevOps pipeline to deploy a NodeJS app. The pipeline and the build are going well. Now i have to define a URL for the backend using env variables, but without success.

```
trigger:
- develop

jobs:
  - job: JobTest
    pool:
      vmImage: ubuntu-latest

    variables:
    - name: BACKEND_URL
      value: https://<some_url>
    - name: System.Debug
      value: true
    steps:
    - task: AzureStaticWebApp@0
      inputs:
        app_location: "/" 
        api_location: ""
        output_location: "dist"

      env:
        BACKEND_URL: $(BACKEND_URL)
        azure_static_web_apps_api_token: $(deployment_token)
    - bash: echo $(BACKEND_URL)
    - bash: echo $PWD
```

and from the NodeJS code, in the "/app/src/models/config.ts" file i have the this:

> export const BACKEND_URL = process.env.BACKEND_URL

If i change **process.env.BACKEND_URL** with the actual URL it will work.

Also, from the Azure Pipeline this task is using the [https://github.com/microsoft/Oryx](https://github.com/microsoft/Oryx) build system.

The question is how can i use env from the pipeline in the code?

**Comment by bagavan44** [comment]
This was working with GitHub actions but not with the Azure DevOps pipeline

**Comment by bhagavan44** [comment]
Got a workaround for this issue [https://gist.github.com/bhagavan44/ed11fb5199667fd0d4aeddf346a3a870](url)

**Comment by bhagavan44** [comment]
Got a workaround for this issue [https://gist.github.com/bhagavan44/ed11fb5199667fd0d4aeddf346a3a870](https://gist.github.com/bhagavan44/ed11fb5199667fd0d4aeddf346a3a870)

**Comment by dan-eversen** [comment]
Confirmed that the workaround works, thanks bhagavan44. Pretty ridiculous that this is broken, if you ask me. Does anyone know why you have to split this into two stages as Bhagavan did in order to get the env variable to be seen by the build process?

**Comment by anthonychu** [comment]
The Static Web Apps task runs in a container. Variables are not passed into it by default. We’ll work on a fix.

**Comment by dan-eversen** [comment]
> The Static Web Apps task runs in a container. Variables are not passed into it by default. We’ll work on a fix.

Right, I looked at the source code on Oryx and saw that, which led to me considering making a pull request. Oryx simply needs to run a command like `( set -o posix ; set ) | grep '^REACT_APP' > .env` and then load it in. This is basically already happening on line 185 of `NodePreRunCommandOrScriptTest.cs` which has 

```
            var buildScript = new ShellScriptBuilder()
                .AddCommand($"oryx build {appDir} -i /tmp/int -o {appOutputDir} " +
                $"--platform nodejs --platform-version {nodeVersion}")
                // Create a 'build.env' file
                .AddCommand(
                $"echo '{FilePaths.PreRunCommandEnvVarName}=\"echo > {expectedFileInOutputDir}\"' > " +
                $"{appOutputDir}/{BuildScriptGeneratorCli.Constants.BuildEnvironmentFileName}")
               .ToString();
```

where `BuildScriptGeneratorCli.Constants.BuildEnvironmentFileName` is the .env file. When I have some free time I'm going to get Oryx running locally and I'll try cat'ing the react app env vars. So (without testing, this might be wrong), the fix would look something like

```
            var buildScript = new ShellScriptBuilder()
                .AddCommand($"oryx build {appDir} -i /tmp/int -o {appOutputDir} " +
                $"--platform nodejs --platform-version {nodeVersion}")
                // Create a 'build.env' file
                .AddCommand(
                $"echo '{FilePaths.PreRunCommandEnvVarName}=\"echo > {expectedFileInOutputDir}\"' > " +
                $"{appOutputDir}/{BuildScriptGeneratorCli.Constants.BuildEnvironmentFileName}")
                .AddCommand(
                $"echo ( set -o posix ; set ) | grep '^REACT_APP' > " +
                $"{appOutputDir}/{BuildScriptGeneratorCli.Constants.BuildEnvironmentFileName}")
               .ToString();
```

**Comment by anthonychu** [comment]
@dan-eversen Thanks for offering to help with this. The issue is actually in the Azure Pipelines task. It could be fixed by updating this [script](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureStaticWebAppV0/launch-docker.sh) to pass all variables that exist in the runner to `docker`. It should use a deny list to block certain variables like `PATH`. If you are interested in making a PR, please coordinate with @miwebst on details. @smurawski might be able to assist here too.

**Comment by dan-eversen** [comment]
@anthonychu Thanks for pointing me in the right direction! It looks like that script could be simplified a bit by taking out those specified Static Web App env variables (i.e., `[[ ! -z "$SWA_APP_LOCATION" ]] && params+=(-e "INPUT_APP_LOCATION=$SWA_APP_LOCATION")` and simply grabbing all of the variables while utilizing an exclusion list, as you suggested. Something like this:

```
workspace="/working_dir"

params=()

results=$(( set -o posix ; set ) | grep -E -v '^(PATH|USER|LOGNAME|HOME|SHELL|VSCODE|SSH|BASH|NVM|HOSTNAME|GIT|NODE|PWD|TMPDIR)')

for value in $results
do
    if [[ "$value" == *"="* ]]; then
        params+=(-e $value)
    fi
done

docker run \
    -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN="$SWA_API_TOKEN" \
    -e GITHUB_WORKSPACE=$workspace \
    -e DEPLOYMENT_PROVIDER=DevOps \
    -e REPOSITORY_URL="$BUILD_REPOSITORY_URI" \
    -e IS_PULL_REQUEST=false \
    -e BASE_BRANCH="$BUILD_SOURCEBRANCHNAME" \
    "${params[@]}" \
    -v "$BUILD_SOURCESDIRECTORY:$workspace" \
    "$SWA_DEPLOYMENT_CLIENT" \
```

@miwebst @smurawski How does this look to you? I'm assuming I'm missing a few variables in the exclusion list, but other than that this code should work. The alternative is to do the work in the `index.ts` file and pass it in to the `launch-docker.sh` script with `execFile`, but that seems needlessly complicated.

**Comment by anthonychu** [comment]
@dan-eversen Thanks for your suggestion and @yoursweater thanks for submitting the PR https://github.com/microsoft/azure-pipelines-tasks/pull/14968. We'll discuss the change there and see if this is something we can merge in.

**Comment by Dorian30** [comment]
@dan-eversen I tried the workaround but it didn't work. Perhaps am I missing something ? I'm facing the exact same issue. I copy the task for the gist to split the process into two separate parts and populate the build with the env variables but they are still not showing up.

**Comment by yoursweater** [comment]
@Dorian30 Can you copy and paste your yaml?

**Comment by Dorian30** [comment]
Sure @yoursweater. That's my yaml file. I basically just added the bash task to make the build. Any thoughts? 

```yaml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |        
        npm install 
        npm run build
    env:
      REACT_APP_API_URL: $(api_url)
      
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: 'build'
      azure_static_web_apps_api_token: $(deployment_token)
```

**Comment by anthonychu** [comment]
@Dorian30 I think you're close. The problem is that the `AzureStaticWebApp` task is rebuilding the app without the environment variables. You can disable this behavior by specifying `skip_app_build`, which will cause the task to deploy only.

```yml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |        
        npm install 
        npm run build
    env:
      REACT_APP_API_URL: $(api_url)
      
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'build'
      api_location: 'api'
      output_location: ''
      skip_app_build: false
      azure_static_web_apps_api_token: $(deployment_token)
```
