### ISSUE TITLE
Question for 

### ISSUE THREAD

**Issue by jennyxchengsea** [Azure/static-web-apps#410]
I've tried to deploy the static web app via github, and I received this error. 

App Directory Location: '/app' is invalid. Could not detect this directory. Please verify your workflow reflects your repository structure.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

I believe it has something to do with setting on repositoryToken and appLocation

How do I find these info via my github repository?

**Comment by riverar** [comment]
Hi @jennyxchengsea, after binding your GitHub repository to Static Web Apps, you should have a GitHub Actions workflow defined at `.github/workflows/xxxxx.yaml`.

Within the file, `app_location` points to your web app sources live and `api_location` points to where your web app api sources live. If your `app_location` points to a folder with some static html/css, and no special build steps are needed, you can skip the build step completely (by adding `skip_app_build: true` right below that line).

More details [can be found in the documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow?WT.mc_id=WD-MVP-5002756).

**Comment by JoCa96** [comment]
I had the same issue when using the Azure DevOps Task `AzureStaticWebApp@0`.
If you have this issue there to you can fix it by using the `cwd` input parameter:
```yaml
- task: AzureStaticWebApp@0
     inputs:
       cwd: $(Pipeline.Workspace)/${{parameters.artifact}}
       app_location: ${{parameters.distDirectory}}
       azure_static_web_apps_api_token: ${{parameters.azureStaticWebAppsApiToken}}
```
