### ISSUE TITLE
Failed to find default file despite successful build

### ISSUE THREAD

**Issue by ffMathy** [Azure/static-web-apps#434]
Here's the build logs: https://github.com/sponsorkit/sponsorkit.io/runs/2650083030?check_suite_focus=true

And here's my project: https://github.com/sponsorkit/sponsorkit.io

**Comment by anthonychu** [comment]
That workflow is for the `feature/signup-flow` branch, and there's no `index.js` in [`src/frontend/src/pages`](https://github.com/sponsorkit/sponsorkit.io/tree/feature/signup-flow/src/frontend/src/pages), so no `index.html` is generated in the build.

In the workflow run you linked to, you have both `output_location` and `app_artifact_location`. The latter is now deprecated. This should the the correct configuration for your app, once you've added the index page:

```yml
app_location: "/src/frontend"
api_location: "/src/api"
output_location: "public"
```
