### ISSUE TITLE
DocFX Build and Deploy Action

### ISSUE THREAD

**Issue by GeorgeAdamon** [Azure/static-web-apps#470]
Hello, 
I'm having trouble publishing a documentation website generated by DocFX to Azure Static Web Apps, following the step-by-step wizard.

**Problem**
Attempting to build and deploy a static DocFX web site using the step-by-step guide in Azure Portal currently fails at the github workflow "Build And Deploy" step, using `Azure/static-web-apps-deploy@v1`. 

At the same time, for other doc generators like Jekyll, the documentation implies that the above workflow should work right out of the box. https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll

Building the documentation manually (and pushing the build folder to the repo) and linking the above action to it, results in a succesful workflow run, and the website is hosted succesfully.

**Request**
DocFX projects should be publishable using the `static-web-apps-deploy@v1` action, without extra build steps from the user.

**Alternative**
An example of the extra build steps needed to be added to the workflow would be helpful.

Thank you!

**Comment by liprec** [comment]
Hi @GeorgeAdamon, 

You can take a look at my GitHub action script: the build output of DocFx is in the `_site` folder and AFAIK DocFx 'needs' a Windows agent and the SWA task needs a Linux host, hence the reason of the upload and download of the artifact.

```
name: Build

on:
  push:
    branches: [live]
  pull_request:
    branches: [live]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: choco install docfx
        run: |
          choco install docfx -y
        env:
          CI: true
      - name: build documentation
        run: |
          docfx build
      - name: publish results
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "_site" 
```
