### ISSUE TITLE
Azure DevOps release pipeline artifact issue

### ISSUE THREAD

**Issue by Phhansen** [Azure/static-web-apps#472]
If you would like to file an issue for the Static Web Apps CLI, please do so here: https://github.com/Azure/static-web-apps-cli/issues

**Describe the bug**
Using the Deploy Azure Static Web App task in the release pipeline does not work with an artifact.

The error we're seeing in the docker part of the task is:
```bash
Error response from daemon: OCI runtime create failed: invalid mount {Destination::/working_dir Type:bind Source:/var/lib/docker/volumes/7a6ef3357e212a9036c6cfc1f2cd492a04a51e3f3115f44178f585783eb30162/_data Options:[rbind]}: mount destination :/working_dir not absolute: unknown.
```

**To Reproduce**
the output of our yml task: (omitting customer name and token of course)
```yml
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: Customer App'
  inputs:
    app_location: '_customer-landing/BuildArtifact/dist/apps/customer-landing-page'
    skip_app_build: true
    azure_static_web_apps_api_token: 'snip'
```

**Expected behavior**
That the task uses the app location as specified. Or that the error makes a little more sense.

**Screenshots**

**Device info (if applicable):**

**Additional context**
Not sure if I'm just not experienced enough with devOps. But I cannot really grasp in what format I need the path to be.
