### ISSUE TITLE
Azure Pipelines Task - volume mount other directories into container

### ISSUE THREAD

**Issue by RossMurr4y** [Azure/static-web-apps#485]
**Is your feature request related to a problem? Please describe.**
After publishing a package of my SWA in a build pipeline, a second job downloads and attempts to deploy that package.

The default download location for artifacts in a deployment job is `Agent.BuildDirectory` or `/home/vsts/work/1`

However the container that the task runs in only volume mounts the sources directory (`$(Pipeline.Workspace)/s` or `/home/vsts/work/1/s`) , even if the you've opted to skip the app build. 

The artifact in its default staging location will never be available to this container.

This can be seen in the temp file created to run docker for the task:

```bash
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/493fb7f3-fb40-4805-99c8-080bcbda716a.sh
workspace="/working_dir"

params=()

[[ ! -z "$SWA_APP_LOCATION" ]] && params+=(-e "INPUT_APP_LOCATION=$SWA_APP_LOCATION")
[[ ! -z "$SWA_APP_BUILD_COMMAND" ]] && params+=(-e "INPUT_APP_BUILD_COMMAND=$SWA_APP_BUILD_COMMAND")
[[ ! -z "$SWA_OUTPUT_LOCATION" ]] && params+=(-e "INPUT_OUTPUT_LOCATION=$SWA_OUTPUT_LOCATION")
[[ ! -z "$SWA_API_LOCATION" ]] && params+=(-e "INPUT_API_LOCATION=$SWA_API_LOCATION")
[[ ! -z "$SWA_API_BUILD_COMMAND" ]] && params+=(-e "INPUT_API_BUILD_COMMAND=$SWA_API_BUILD_COMMAND")
[[ ! -z "$SWA_ROUTES_LOCATION" ]] && params+=(-e "INPUT_ROUTES_LOCATION=$SWA_ROUTES_LOCATION")

params+=(-e "INPUT_SKIP_APP_BUILD=$SWA_SKIP_APP_BUILD")

docker run \
    -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN="$SWA_API_TOKEN" \
    -e GITHUB_WORKSPACE=$workspace \
    -e DEPLOYMENT_PROVIDER=DevOps \
    -e REPOSITORY_URL="$BUILD_REPOSITORY_URI" \
    -e IS_PULL_REQUEST=false \
    -e BASE_BRANCH="$BUILD_SOURCEBRANCHNAME" \
    "${params[@]}" \
    -v "$BUILD_SOURCESDIRECTORY:$workspace" \
    "$SWA_DEPLOYMENT_CLIENT"
```

**Describe the solution you'd like**

The task should either provide an input parameter to control which directory is mounted into the container, or otherwise factor in some additional logic if `skip_app_build: true` is set.

**Additional context**

Relevant parts of the pipeline:

```yaml
variables:
  artifact_name: 'test'
  build_output_dir: build
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: ci_cd
    displayName: Cont. Integration Test and Package

    jobs:
      - job: ci
        displayName: Cont. Int.
        steps:
          - task: NodeTool@0 
            displayName: Set Node Version
            inputs:
              versionSpec: '10.x'

          - script: yarn install
            displayName: Install Deps

          - script: yarn validate
            displayName: Run linting and testing

          - script: yarn build
            displayName: Create build

          - script: cp staticwebapp.config.json build/staticwebapp.config.json
            displayName: Add SWA Config to Build

          - publish: ${{ variables['build_output_dir'] }}
            displayName: Publish Artifact
            artifact: ${{ variables['artifact_name'] }}

      - deployment: cd
        dependsOn: ci
        condition: succeeded()
        displayName: Cont. Deploy to Integration
        environment: integration_${{ variables['artifact_name'] }}
        strategy:
          runOnce:
            deploy:
              steps:

                - task: AzureStaticWebApp@0
                  displayName: Publish SWA
                  inputs:
                    app_location: /${{ variables['artifact_name'] }}
                    skip_app_build: true
                  env:
                    azure_static_web_apps_api_token: $(my_deployment_token_secret)
```
