### ISSUE TITLE
Gatsby doesn't read enviroment variables at build

### ISSUE THREAD

**Issue by notaduck** [Azure/static-web-apps#488]
Hi there.
I have a gatsby site where I use enviroment variables in the `gatsby-configuration.js` file:

```js
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
  GATSBY_STRAPI_ENDPOINT: `.env.${process.env.STRAPI_ENDPOINT}`,
})
....
....
  plugins: [
    {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `${process.env.GATSBY_STRAPI_ENDPOINT}`,
        queryLimit: 1000, // Default to 100
        collectionTypes: [
          {
            name: 'landingpage',
            api: { qs: { _locale: `all` } }
          },
          {
            name: 'products',
            api: { qs: { _locale: `all` } }
          }
        ],
      },
    },
...
...
```

Locally everything works just fine and the env vars are read from `.env.development` but as soon as I try to build the project through github actions it fails hard and cannot read the env vars. I have tried to add them as a GitHub secret in the repository and set them through the action itself

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env: 
      GATSBY_STRAPI_ENDPOINT: ${{ secrets.GATSBY_STRAPI_ENDPOINT }}
    steps:
      - uses: actions/checkout@v2
```

Unfortunately without any luck, I also tried to set it as an application setting in the configuration of the static web app without any success. So I am not too sure how to proceed on this one, and if it is a bug or a lack of knowledge from my site.

![Screenshot 2021-06-21 at 09 19 55](https://user-images.githubusercontent.com/9454064/122722834-7a9ac480-d272-11eb-8479-81acd3d481c8.png)
