### ISSUE TITLE
Add custom nuget source

### ISSUE THREAD

**Issue by verplanckeo** [Azure/static-web-apps#493]
**Describe the bug**

We have our own github nuget package source we add for building our project. We're using the new static web app CI/CD feature which integrates automatically with your github repo. We are unable to add our own nuget source using this task.
The app (UI) is written using the React framework. The api (backend functions) is written using .NET Core 3.1
[static_web_app.txt](https://github.com/Azure/static-web-apps/files/6710607/static_web_app.txt)

**To Reproduce**
0. Set up the static web app CI/CD flow (according to documentation)
1. Add an app to be built & deployed
2. Add an api to be built & deployed
3. Add steps to add custom nuget source (for which you need a token to authorize access to)
4. Trigger build
5. Check logs (see screenshots below)

**Expected behavior**
How can we add a custom nuget source as part of this workflow?
Or is there another preferred way to go about this?
The idea is to have the functions (which act as a gateway) & the react app to be deployed together.

**Screenshots**
![image](https://user-images.githubusercontent.com/23524832/123294958-4d088200-d4e3-11eb-860e-8a74ba761781.png)
![image](https://user-images.githubusercontent.com/23524832/123293475-049c9480-d4e2-11eb-8bf4-4d4586d6c2a9.png)
![image](https://user-images.githubusercontent.com/23524832/123293551-14b47400-d4e2-11eb-8459-a16aafd47af6.png)

**Additional context**
Also tried adding the nuget source using a separate step followed by the task to build the static web app. But it also did not work:
![image](https://user-images.githubusercontent.com/23524832/123295168-73c6b880-d4e3-11eb-8123-9280f2b44a1d.png)

Any feedback is welcome at this point. For now we just deploy the functions using a separate repo and workflow.
The react app is, for now, the only one being deployed in the static web app resource.

**Comment by anthonychu** [comment]
@arroyc do you have any guidance for using private NuGet/npm feeds in Oryx?

**Comment by svrooij** [comment]
Or maybe do a **NuGet** restore before calling `AzureStaticWebApp` and then adding the `--no-restore` build parameter. Would that work @arroyc or @anthonychu

**Comment by Admiralfeb** [comment]
I'm running into this issue as well.

I ran `dotnet nuget add source` and added my github nuget repo to sources then attempted to run a `dotnet restore` beforehand and it still failed as it ran its own restore. 
I'd rather not publish these nuget packages to nuget.org

**Comment by svrooij** [comment]
In this issue they are telling us the skip API build parameter is coming in the next week or so (3 weeks, 18 days ago). https://github.com/Azure/static-web-apps/issues/343#issuecomment-1048455822

Maybe you just have to wait a little, and then build the API yourself and only publish using the task.

**Comment by Admiralfeb** [comment]
If I end up with a private nuget in the client, then that's not enough. I'd prefer to have a `no-restore` option to solve the entire project build.

**Comment by svrooij** [comment]
> If I end up with a private nuget in the client, then that's not enough. I'd prefer to have a `no-restore` option to solve the entire project build.

What do you mean?

The `skip_api_build` you can restore and build the API yourself. You then publish it to a folder and that folder will be deployed? Why wouldn't that be enough?

**Comment by rfabro** [comment]
> > If I end up with a private nuget in the client, then that's not enough. I'd prefer to have a `no-restore` option to solve the entire project build.
> 
> What do you mean?
> 
> The `skip_api_build` you can restore and build the API yourself. You then publish it to a folder and that folder will be deployed? Why wouldn't that be enough?

I believe he's talking about the client and not the API. I have the same problem with my Blazor WebAssembly project as it references a private NuGet from Github.

**Comment by Admiralfeb** [comment]
Exactly. I have a library I built to share between different projects that I put into github's nuget registry and I can't use it.

I'd like the ability to perform a manual restore and just tell the system to not try to restore when it goes to build just like the `dotnet build --no-restore` works.

**Comment by svrooij** [comment]
@adam-bentley yes.... just build it yourself including all the external sources and only use it to upload the app. So you skip building by the static web app action.

**Comment by pingu2k4** [comment]
I recently switched to what @svrooij mentions, but before that I have a nuget.config file in the root of my repo, which references the custom nuget login credentials as environment variables which I set.

So, first I did this. Add a nuget.config something like:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="telerik" value="https://nuget.telerik.com/v3/index.json" />
	</packageSources>
	<packageSourceCredentials>
		<telerik>
			<add key="Username" value="%TELERIK_USERNAME%" />
			<add key="ClearTextPassword" value="%TELERIK_PASSWORD%" />
		</telerik>
	</packageSourceCredentials>
</configuration>
```
Of course, modify as needed.

Then specify the environment variables as part of the job or the step.
```
    env:
      TELERIK_PASSWORD: ${{ secrets.TELERIK_PASSWORD }}
      TELERIK_USERNAME: ${{ secrets.TELERIK_USERNAME }}
```

For other reasons, more recently, this was also not working for me. I recently added NPM dependencies into my project, and building through oryx was failing where I have a prebuild step in .csproj to `npm install` and `npm run build`. So... I have more recently done what is mentioned in the comment above. 

Before the static-web-apps-deploy step, I build:
```
      - name: Publish
        run: dotnet publish -c Release --output "$GITHUB_WORKSPACE/.publish"
        working-directory: 'my/directoy/to/my/blazorwasm'
```
and finally, as part of the `static-web-apps-deploy` step I  specify the app_location as such:
`app_location: "${{ github.workspace }}/.publish/wwwroot"`

So, 2 options depending on your preferences / needs there. :)

**Comment by adam-bentley** [comment]
@pingu2k4 I think Ive followed the correct steps, but Im getting an error
> Cannot deploy to the function app because Function language info isn't provided.

Is this something you've come across?

```
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add private nuget source
        run: dotnet nuget add source ${{ env.nuget_feed_source }} --name ${{ env.nuget_feed_name }} --username az --password ${{ secrets.PRIVATE_NUGET_SOURCE_KEY }} --store-password-in-clear-text
      - name: Restore API
        run: dotnet restore "${{ env.solution_file }}"
      - name: Build API
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --no-restore
      - name: Publish API
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_0DB847103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          skip_api_build: true
          ###### End of Repository/Build Configurations ######
```

**Comment by pingu2k4** [comment]
@adam-bentley Are you trying to build it outside of oryx?
If so, then what I have to do that job is the following:

```
      - name: Publish
        run: dotnet publish -c Release --output "$GITHUB_WORKSPACE/.publish"
        working-directory: 'path/to/blazorWasm'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_OCEAN_08A9BA303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          #app_location: "path/to/blazorWasm" # App source code path
          app_location: "${{ github.workspace }}/.publish/wwwroot"
          api_location: "" # Api source code path - optional
          #output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

So,  no output location needed, and app_location specifies the output directory of the publish command I previously used. Change paths to point to your own stuff etc of course. But this is pretty much exactly what I have right now. (I am publishing the API seperately myself, to sit outside of the static web app)
