### ISSUE TITLE
AzureStaticWebApp step fails immediately

### ISSUE THREAD

**Issue by kevinprescottwong-Dev** [Azure/static-web-apps#501]
For the life of me, I can't get this AzureStaticWebApp pipeline step to succeed. 
 
I have a react app that I created through the standard create-react-app npx command. I tried following a bunch of official and unofficial tutorials, but nothing I've tried has worked. I've seen many tutorials get you to use the GitHub Actions flow, but I want to get an Azure DevOps CI/CD pipeline setup for this react project.

The one thing that I suspect might be causing some issues is that I am using a self-hosted Agent (vsts-agent-win-x64-2.188.3) to run the pipelines, since I dont have access to the hosted parallelism 

**To Reproduce**
1. I run my pipeline
2. AzureStaticWebApp step fails immediately

- GitHub Actions or Azure Pipelines workflow YAML file

```
trigger:
  - main

pool:
  name: Default

steps:
  - checkout: self
    submodules: true

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: build

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/build'
      azure_static_web_apps_api_token: '$(deployment_token)'
```

- Output of AzureStaticWebApp step
```
2021-07-01T04:36:39.8899695Z ##[section]Starting: AzureStaticWebApp
2021-07-01T04:36:39.9036032Z ==============================================================================
2021-07-01T04:36:39.9036303Z Task         : Deploy Azure Static Web App
2021-07-01T04:36:39.9036657Z Description  : [PREVIEW] Build and deploy an Azure Static Web App
2021-07-01T04:36:39.9036859Z Version      : 0.187.1
2021-07-01T04:36:39.9037027Z Author       : Microsoft Corporation
2021-07-01T04:36:39.9037214Z Help         : https://aka.ms/swadocs
2021-07-01T04:36:39.9037436Z ==============================================================================
2021-07-01T04:36:40.1961223Z ##[section]Finishing: AzureStaticWebApp
```

- staticwebapp.config.json file
```
{
  "navigationFallback": {
    "rewrite": "/index.html"
  }
}

```

**Expected behavior**
The AzureStaticWebApps step completes and deploys my react project to my Azure Static Web App

**Screenshots**
Here is what my entire pipeline looks like
![image](https://user-images.githubusercontent.com/45706095/124075112-3b4e3f80-d9f9-11eb-9eee-bce1488d43fa.png)

Any help would be greatly appreciated! Thanks

**Comment by miwebst** [comment]
Is the VM running the pipeline a Windows machine? We've seen this in the past if the VM is not capable of running the task startup script.

**Comment by kevinprescottwong-Dev** [comment]
Hi miwebst,

I am running the Agent on my own local machine, which is Windows 10. 
Did the issue that you are referring to get resolved? If so, how did they resolve it?

Thanks

**Comment by kevinprescottwong-Dev** [comment]
I FINALLY FIXED MY ISSUE!!!!

When you mentioned that it might be a Windows problem, I used my Ubuntu VM:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Then I had to install npm and docker.io:
sudo apt install npm
sudo apt-get install docker.io

Then I had to setup docker for my user on the machine:
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket

After that I was able to run my pipeline with the following YAML:
```
trigger:
  - main

pool:
  name: Default

steps:
  - checkout: self
    submodules: true
    
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'build' 
      azure_static_web_apps_api_token: '$(deployment_token)'
```

I hope this helps some people out :)

---
I would have to double check, but I think installing docker would fix my Windows issue. I will reply with my results
