### ISSUE TITLE
Release pipeline task failing - image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by moh-altimimi** [Azure/static-web-apps#514]
Hi

I have a release pipeline set up a basic Static Web App job:

```yml 
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: ubiquity-staging-frontend'
  inputs:
    app_location: /
    output_location: out
    skip_app_build: false
    azure_static_web_apps_api_token: '6cd2a527301fecf07921968af6251acec69b8b0b9fbe6dcb0134ec5359eaec500-dc8bb66b-c669-4231-9e41-7b2b4d60accf01025014'
```

Which is run off the back of the below build pipeline:

```yml
trigger:
- release/*

pool:
  vmImage: ubuntu-latest

steps:
- task: npmAuthenticate@0
  displayName: 'npm Authenticate .npmrc'
  inputs:
    workingFile: .npmrc

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
```

The release pipeline job however is failing with the below output:

```console
2021-07-20T04:44:51.7893187Z ##[section]Starting: Static Web App
2021-07-20T04:44:51.8597403Z ==============================================================================
2021-07-20T04:44:51.8598141Z Task         : Deploy Azure Static Web App
2021-07-20T04:44:51.8598535Z Description  : [PREVIEW] Build and deploy an Azure Static Web App
2021-07-20T04:44:51.8598745Z Version      : 0.187.1
2021-07-20T04:44:51.8599064Z Author       : Microsoft Corporation
2021-07-20T04:44:51.8599401Z Help         : https://aka.ms/swadocs
2021-07-20T04:44:51.8599630Z ==============================================================================
2021-07-20T04:44:52.7304585Z [command]"C:\Program Files\Git\bin\bash.exe" D:\a\_tasks\AzureStaticWebApp_18aad896-e191-4720-88d6-8ced4806941a\0.187.1\launch-docker.sh
2021-07-20T04:44:57.8321177Z Unable to find image 'mcr.microsoft.com/appsvc/staticappsclient:stable' locally
2021-07-20T04:44:59.8826652Z stable: Pulling from appsvc/staticappsclient
2021-07-20T04:45:00.2900328Z docker: image operating system "linux" cannot be used on this platform.
2021-07-20T04:45:00.2901890Z See 'docker run --help'.
2021-07-20T04:45:00.3001796Z 
2021-07-20T04:45:00.3128973Z ##[section]Finishing: Static Web App```
