### ISSUE TITLE
The number of files in the app content folder exceeds the limit of 15000.

### ISSUE THREAD

**Issue by kkankala** [Azure/static-web-apps#520]
I'm using Next JS app for front end and Azure devops to deploy to SWA. 

I have azure devops task as below.
`- task: AzureStaticWebApp@0
            inputs:
              app_location: 'NextJS/sample-app'
              api_location: 'NextJS/api'
              output_location: 'out'
            env:
              azure_static_web_apps_api_token: $(deployment_token)`

**Pipeline Error**
 `Determining projects to restore...
  Restored /working_dir/NextJS/api/SampleApi/SampleApi.csproj (in 2.83 sec).

Publishing to directory /ss-oryx/api...

Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ResearchApi -> /working_dir/NextJS/api/SampleApi/bin/Release/netcoreapp3.1/SampleApi.dll
  ResearchApi -> /ss-oryx/api/
Preparing output...

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 16 sec(s).

---End of Oryx build logs---
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The number of files in the app content folder exceeds the limit of 15000.`

I have tried to reduce the output of number of files then I received below error
`
---End of Oryx build logs---
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this Static Web App is 262144000 bytes.
`

We are at a stage to productionalize our application but this is a deal breaker. We have around more than 25k files now and  that is only going to grow (significantly) larger over time.

I can't share repository details.

**Comment by kkankala** [comment]
Any update on this issue please?

**Comment by kkankala** [comment]
@anthonychu

**Comment by wsaada19** [comment]
We are running into the same issue, would be great if the file limit could be increased. When can we expect a resolution?

**Comment by lawrenceong001** [comment]
hello, i'm also bumping into this issue -- we have a site that hosts around 25k files, largely statically generated content. can someone please provide guidance on timelines, etc? tks.

**Comment by markblue777** [comment]
Also receiving this error, any known workarounds for it?

**Comment by SuperOfficeDevNet** [comment]
This seems true even for the Standard Plan, regardless that all files combined are only ~320MB.

@MaximRouiller Any thoughts?

**Comment by NoPodi** [comment]
Found a dirty workaround https://github.com/Azure/static-web-apps/issues/782#issuecomment-1186322614

**Comment by hornta** [comment]
This is still a problem. We might have to look into other solutions if this can't be resolved very soon.

**Comment by ytodorov** [comment]
Please fix this issue as soon as possible. It is so easy to increase the limit to 1 000 000. Why are you limiting us to only 15 000?

**Comment by hornta** [comment]
@ytodorov We solved it by building the app in Github Actions and just uploading the built artifacts.

```
name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Remove 'node_modules'
        run: rm -rf node_modules/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "/build"
```
