### ISSUE TITLE
npm 7 guidance, static-web-apps-deploy

### ISSUE THREAD

**Issue by mlynam** [Azure/static-web-apps#533]
Hello team--

I am wondering if there is any guidance on using npm 7 with static-web-apps-deploy. My build action includes the following steps to setup the versions I want to use during the build.

```
  - name: Use Node.js ${{ env.NODE_VERSION }}
    uses: actions/setup-node@v1
    with:
      node-version: ${{ env.NODE_VERSION }}
  - name: Update npm
    run: npm i npm -g
```

I run these before the build step but the build still uses an `npm 6.x` version.

Thanks,
Matt
