### ISSUE TITLE
[Bug] Uncaught TypeError: Object(...) is not a function when deploying with Azure Pipelines

### ISSUE THREAD

**Issue by AverageCakeSlice** [Azure/static-web-apps#545]
**Description**
I am writing an app using Vue 3 for the SPA and .NET Core 3.1 for the API.

As of yesterday evening, Azure Pipelines seems to be breaking my releases to US Central. It reports that my builds ran successfully, but when I attempt to access the site the app fails to load, with a console error being thrown stating "Uncaught TypeError: Object(...) is not a function" that points to a seemingly arbitrary div element in my code.

This seems to be affecting all of my apps. I have two separate static web apps for dev and test, that track the dev and test branches in my Azure Repo. I have pipelines setup for both that deploy when changes are pushed to their respective branches. I first noticed the issue on Dev, and attempted reverting the changes in git, but the issue persisted. I then made a single comment in test and pushed, which resulted in the same issue, despite the fact that test had none of the changes in dev. Reverting to the previous commit and pushing the changes does not resolve the issue.

This has completely halted development, I don't want to push to our production repository as I'm afraid the issue will cascade down to that application as well.

** Azure Pipelines YAML**
```yml
trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: 'dist'
      azure_static_web_apps_api_token: $(deployment_token)
```
```yml
trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: 'dist'
      azure_static_web_apps_api_token: $(deployment_token)
```

**Expected behavior**
I expect the build pipeline to deploy and operate identically to how it runs locally with the Azure SWA CLI, barring auth and environment variable differences.

**Screenshots**
**Screenshot of the console error**
![image](https://user-images.githubusercontent.com/37710170/128877473-6635c253-f6a2-421c-84d8-d0da85f33c8d.png)

**Screenshot of the error source**
![image](https://user-images.githubusercontent.com/37710170/128877538-961f8ee7-16af-4295-beab-3a1b17d462f4.png)

**Device info (if applicable):**
 - OS: MacOS 11.5
 - Browser Chrome, Safari

**Additional context**
I am able to run the application locally from my machine using the static web apps CLI (`swa start http://localhost:8080 --api http://localhost:7071`) with `npm run serve` and `func start` for my webapp and API, respectively. I receive no console errors or warnings, and the application launches normally.
