### ISSUE TITLE
Devops problems communicating with our content server

### ISSUE THREAD

**Issue by jakeuj** [Azure/static-web-apps#560]
Devops pipelines uploading build artifacts fail.
(We are currently experiencing problems communicating with our content server. 
Please try again later or file an issue if this behavior continues.)

**To Reproduce**
1. Go to 'Devops'
2. Click on 'set up build'
3. Run

```
---End of Oryx build logs---
Finished building app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Uploading build artifacts.
We are currently experiencing problems communicating with our content server. Please try again later or file an issue if this behavior continues.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

Finishing: AzureStaticWebApp
```

Azure Pipelines workflow YAML

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'dist'
      azure_static_web_apps_api_token: $(deployment_token)
```

**Expected behavior**
Depoly success.

**Screenshots**
![2021-08-25_16-13-48](https://user-images.githubusercontent.com/834156/130753698-32588158-7831-4071-b6d4-696a72d534a4.png)

**Device info (if applicable):**
 - OS: Win 10
 - Browser chrome
 - Version 62

**Additional context**
