### ISSUE TITLE
Intermittent 'Failed to upload build artifacts' errors from Azure Dev Ops Deployment Task

### ISSUE THREAD

**Issue by jmbrunskill** [Azure/static-web-apps#570]
**Describe the bug**

Frequent Static Web Pages Deployment failures from Azure Dev Ops Pipeline.
Using continuous integration on commits to a target branch to trigger this workflow.
The website content is generated via a custom static page generation tool, so doesn't use a Static Generation Framework.

**To Reproduce**
Create a Azure Dev Ops pipeline to deploy to static web apps (We are deploying every 15minutes)
Observe intermittent pipeline failures 

![image](https://user-images.githubusercontent.com/8287373/131956081-645202b7-cc3b-4175-8972-4032cf3c5b18.png)
![image](https://user-images.githubusercontent.com/8287373/131956234-62929bb1-5938-4ebb-8de7-26da38a2ebc5.png)

Pipeline yaml is about as simple as it gets
```
trigger:
  - ms-tanks-static-pages-deploy 
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        app_location: ''
        api_location: ''
        output_location: ''
      env:
        azure_static_web_apps_api_token: $(tanks_deployment_token)
```

**Expected behavior**
Deployment failures should be very rare .

**Additional context**
Deployment from Azure Dev Ops Pipeline
