### ISSUE TITLE
Azure Pipelines - App Directory Location is invalid

### ISSUE THREAD

**Issue by josip8** [Azure/static-web-apps#579]
I keep getting error when trying to deploy to azure static web app:
 `App Directory Location: 'HSG.Popal/HSG.Popal.GameContainer/ClientApp/dist' is invalid. Could not detect this directory. Please verify your deployment configuration file reflects your repository structure.`

This is my yaml file:
```
- script: |
    cd HSG.Popal/HSG.Popal.GameContainer/ClientApp
    npm ci
    npm run azure-build
    cd dist
    echo $(ls)
  displayName: 'Install&Build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'HSG.Popal/HSG.Popal.GameContainer/ClientApp/dist'
    skip_app_build: true
    azure_static_web_apps_api_token: $(deployment-token)
  displayName: 'Deploy'
```
Result of my echo command is `css favicon.ico img index.html js web.config`

**Comment by anthonychu** [comment]
This looks like it should work. Can you change `echo $(ls)` to `echo $(pwd)` to confirm the directory location?

**Comment by josip8** [comment]
echo $(pwd) prints out `/azp/agent/_work/2/s/HSG.Popal/HSG.Popal.GameContainer/ClientApp/dist`

So I tried to change `app_location` to that value but still the same error

**Comment by anthonychu** [comment]
Interesting. Can you share the entire pipeline file?

We added an input named `cwd` to the Azure Pipelines task. Can you see what happens if you add it and set its value to `/azp/agent/_work/2/s`, and leave the other inputs like you have above?

**Comment by anthonychu** [comment]
The task uses `$SYSTEM_DEFAULTWORKINGDIRECTORY` by default as the repo root. Curious to see what is printed if you echo that.

**Comment by josip8** [comment]
This is the entire pipeline file:
```
trigger:
- master

pool:
  name: m-shared

variables:
- group: Stage-PSK

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.6'
  displayName: 'Node version 14.17.6'

- task: replacetokens@4
  inputs:
    targetFiles: '**/*.env.azure'
    encoding: 'auto'
    tokenPattern: 'octopus'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: false
    verbosity: detailed
  displayName: 'Replace Tokens'

- script: |
    cd HSG.Popal/HSG.Popal.GameContainer/ClientApp
    npm ci
    npm run azure-build
    cd dist
    echo $(ls)
    echo $(pwd)
    echo $SYSTEM_DEFAULTWORKINGDIRECTORY
  displayName: 'Install&Build'

- task: AzureStaticWebApp@0
  inputs:
    cwd: /azp/agent/_work/2/s
    app_location: 'HSG.Popal/HSG.Popal.GameContainer/ClientApp/dist'
    skip_app_build: true
    azure_static_web_apps_api_token: $(deployment-token)
  displayName: 'Deploy'
```

Adding `cwd` input still produces the same error.

echo `$SYSTEM_DEFAULTWORKINGDIRECTORY` prints out `/azp/agent/_work/2/s`
