### ISSUE TITLE
Next.js public export

### ISSUE THREAD

**Issue by johnkors** [Azure/static-web-apps#6]
Hi, I attempted to deploy a next.js app. Getting this error:

> The app build failed to produce artifact folder: '/web/out'. Please ensure this property is configured correctly in your workflow file."

The `/web/out` folder is the default folder for next export. What does the error mean? It's not clear to me. I assume `app_artifact_location` should be the output of the `next export` - is this correct?

My next.js app is in the `/web` folder.

```
  - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.MYTOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} 
        action: 'upload'
        app_location: '/web' 
        api_location: 'api' 
        app_artifact_location: '/web/out' 
```
