### ISSUE TITLE
[Infomation] Config ORYX Image via Azure DEV Ops Environment Variables (build function in net 6)

### ISSUE THREAD

**Issue by DieselMeister** [Azure/static-web-apps#643]
I had the problem, that my azure funcction app won't build and the skip option end up to not recognize that I acutally used a dotnet function, and it switched to node:

here are the configs:
https://github.com/microsoft/Oryx/blob/main/doc/configuration.md

i used for example to build an azure net6 function:
```
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/Client/publish/app-fe'
    #api_location: '/API/publish_output'
    api_location: '/API'
    skip_app_build: false
  env:
    azure_static_web_apps_api_token: $(deployment_token)
    DOTNET_VERSION: "6.0.100"
```

(the last under env: made it possible to use .net 6 inside the orxy build image! before that it tried to build with net core 3.1!
