### ISSUE TITLE
AzureStaticWebApp deploys to wrong enviroment

### ISSUE THREAD

**Issue by fhatrifork** [Azure/static-web-apps#660]
I am unable to update my azure static web app. I use a devops task to deploy my static site.  But it does not work, when I visit the url I only see old content. I have tried rerunning the task and creating a new commit and deploying again but it does not work.

The pipeline runs without errors.

I see that the version of AzureStaticWebApp@0 changed overnight from 0.187.2 to 0.194.2. This might be causing the issue. Since the version that is live on the webpage is the last to run with version 0.187.2. Did anything change in this version?

My pipeline:
```
trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dev_deploy
    jobs:
      - deployment: devdeploy
        environment: dev
        variables:
        - group: "dev variable group"
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: CmdLine@2
                inputs:
                  script: 'mv frontend/staticwebapp.config.dev.json frontend/staticwebapp.config.json'
              - task: AzureStaticWebApp@0
                inputs:
                  app_location: 'frontend/'
                  output_location: 'dist/frontend'
                  app_build_command: 'npm run builddev'
                  api_location: 'NOT_USED'
                  skip_app_build: false
                  azure_static_web_apps_api_token: '$(frontend_deployment_token)'
```
staticwebapp.config.dev.json:
```
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/assets/*", "*.js", "*.css"]
  },
  "globalHeaders": {
    "X-Frame-Options": "DENY"
  }
}
```

**Expected behavior**
I want the azure static site to be updated with the latest version.

**Comment by fhatrifork** [comment]
Is there anywhere I can see the release notes for AzureStaticWebApp task version 0.194.2? Is there a way to force version 0.187.2?

**Comment by fhatrifork** [comment]
The problems seems to be that my site is now deployed to:
https://xxx.westeurope.azurestaticapps.net/
and the old version is still hosted at:
https://xxx.azurestaticapps.net/

Azure portal still says my site lives at https://xxx.azurestaticapps.net/

What does this maen?

**Comment by fhatrifork** [comment]
My theory is that this made it create a new environment, which was not the old behavior:
```
      - deployment: devdeploy
        environment: dev
```

**Comment by fhatrifork** [comment]
After some more testing I am now pretty sure the AzureStaticWebApp uses the environment defined in YAML to determine the environment to use for the static web app. If I set the environment to 'default' then it will deploy to the production environment.

I am pretty sure this was not the behavior two days ago.

This solves my problem for now, but I would still like an official response. :)

Where can I see release notes for AzureStaticWebApp?

**Comment by senneclaeskens** [comment]
Same issue here. The deploy creates a new URL with the name of the environment.

**Comment by vany0114** [comment]
+1

**Comment by rumurillo** [comment]
Exact same issue here.

The previous successful deployment to our development environment (2021.12.09) deployed to https://...-03cf69b1e.azurestaticapps.net. Since yesterday, all deployments are now getting deployed to https://...-03cf69b1e-development.westus2.azurestaticapps.net - notice the .development.westus2. keyword.

Here's my azure-pipeline.yml file:

````
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: Infrastructure # The name used to reference this repository in the checkout step
    type: github
    endpoint: DrivingThru
    name: DrivingThru/Curbit-Infrastructure
    ref: develop
    
trigger:
  batch: true
  branches:
    include:
      - develop
      - master
  paths:
    include:
      - src/web/.well-known/*
      - src/web/components/*
      - src/web/handlers/*
      - src/web/lib/*
      - src/web/pages/*
      - src/web/public/*
      - src/web/repositories/*
      - src/web/services/*
      - src/web/styles/*
      - src/web/utils/*
      - src/web/package.json
      - src/web/eventHub/*
      - src/web/redux/*
      - src/web/hooks/*
      - ./build-nextjs-webapp-stage.yml

variables:
  - template: build/azure-devops/templates/variables/infrastructure.yml@infrastructure

stages:
  - template: ./build-nextjs-webapp-stage.yml
  
  - stage: Dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Deploy to Dev'
    dependsOn: Build
    jobs:
      - deployment: DeployWebapp
        displayName: Deploying to Development
        environment: development
        strategy: 
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Artifacts
                  inputs:
                    artifact: webapp
                    path: $(Build.SourcesDirectory)/webapp

                - task: AzureStaticWebApp@0
                  displayName: Deploy to Azure Static WebApp
                  inputs:
                    app_location: '/webapp'
                    skip_app_build: true
                  env:
                    azure_static_web_apps_api_token: $(deployment_token)

  - stage: Prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Deploy to Prod'
    dependsOn: Build
    jobs:
      - deployment: DeployWebapp
        displayName: Deploying to Production
        environment: production
        strategy: 
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Artifacts
                  inputs:
                    artifact: webapp
                    path: $(Build.SourcesDirectory)/webapp

                - task: AzureStaticWebApp@0
                  displayName: Deploy to Azure Static WebApp
                  inputs:
                    app_location: '/webapp'
                    skip_app_build: true
                  env:
                    azure_static_web_apps_api_token: $(deployment_token)

````

cc @anthonychu

**Comment by javier-romera** [comment]
Same here. Since 2 days not updating. I had in the deploy task "environment: Test", now changed to "environment: Production" and created the environment on Azure DevOps Pipelines. I granted permission for the environment but it does not work.

**Comment by javier-romera** [comment]
Solved creating an environment called "default" and assigning to the deploy pipeline task.

**Comment by anthonychu** [comment]
> Solved creating an environment called "default" and assigning to the deploy pipeline task.

This is currently the workaround. We're working on a fix. Sorry for the inconvenience.

**Comment by rumurillo** [comment]
> Solved creating an environment called "d

Hey, @javier-romera -- when you say you created an environment called "default", what do you mean? Would you mind elaborating a bit more on how you work around this issue?

Thanks!

**Comment by fhatrifork** [comment]
> Hey, @javier-romera -- when you say you created an environment called "default", what do you mean? Would you mind elaborating a bit more on how you work around this issue?
> 
> Thanks!

Here is an example. Notice the "environment: default"

For this to work you have to create en environment called default: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops

```
  - stage: uat_deploy
    jobs:
      - deployment: uatdeploy
        environment: default
        variables:
        - group: "uat variable group"
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: AzureStaticWebApp@0
                inputs:
                  app_location: 'frontend/'
                  output_location: 'dist/frontend'
                  app_build_command: 'npm run builduat'
                  api_location: 'NOT_USED'
                  skip_app_build: false
                  azure_static_web_apps_api_token: '$(frontend_deployment_token)'
```
