### ISSUE TITLE
AzureStaticWebApp environment name errors

### ISSUE THREAD

**Issue by daniel-woodhead** [Azure/static-web-apps#664]
The AzureStaticWebApp task has been failing since the version changed from 0.187.2 to 0.194.2. We're using it in a few pipelines, one of which errors with `The environment name provided has invalid character(s). Valid characters are 0-9, a-z, and A-Z` whereas the others error with `The environment name provided exceeds the character limit of 16.`

Reading #660 suggests this is the environment name specified in the deployment job in the pipeline, in which case our environment names do break these rules (e.g. InformationLeaflets_dev) but they are valid as far as ADO is concerned. Any advice would be appreciated.

Extract from one of the pipelines:
```
- stage: Deploy_${{ variables.env }}
  pool: ${{ variables.agentPool }}
  jobs:
  - deployment: deploy
    displayName: Deploy_${{ variables.env }}
    environment: InformationLeaflets_${{ variables.env }}
    strategy:
      runOnce:
        deploy:
          steps:
	  // ...
          - task: AzureStaticWebApp@0
            displayName: Build and deploy app
            inputs:
              app_location: 'output'
              skip_app_build: true
              azure_static_web_apps_api_token: $(deployment_token)
```

Task output:
```
Starting: Build and deploy app
==============================================================================
Task         : Deploy Azure Static Web App
Description  : [PREVIEW] Build and deploy an Azure Static Web App
Version      : 0.194.2
Author       : Microsoft Corporation
Help         : https://aka.ms/swadocs
==============================================================================
##[warning]Environment variable BUILD_SOURCEVERSIONMESSAGE is a multiline string and cannot be added to the build environment.
/usr/bin/bash /ado-agent/2.181.2/_work/_tasks/AzureStaticWebApp_18aad896-e191-4720-88d6-8ced4806941a/0.194.2/launch-docker.sh
DeploymentId: 80cfb68e-3d00-4152-b1bf-9b35891a66e3

App Directory Location: 'output' was found.
No Api directory specified. Azure Functions will not be created.
The environment name provided exceeds the character limit of 16.
```

**Comment by simonaco** [comment]
@daniel-woodhead the fix for #660 should help with the issues related to env length & characters as well, I just tested a deployment using a very long env name and it succeeded. Would you mind manually triggering a new run for the ones that failed?

**Comment by daniel-woodhead** [comment]
Hi @simonaco thank you for looking into this, unfortunately it still failed with the same error.

**Comment by anthonychu** [comment]
@daniel-woodhead Are you running on a Microsoft-hosted agent or a self-hosted one? The fix was made in the underlying Docker image, and it's possible that it's still using an older cached version on the agent.

**Comment by daniel-woodhead** [comment]
@anthonychu It's a self-hosted agent. How can I make it use the latest version?

**Comment by anthonychu** [comment]
Added a bug to track this: https://github.com/microsoft/azure-pipelines-tasks/issues/15629

For now, try adding a step to pull the image before running the `AzureStaticWebApp` task:

```yaml
- stage: Deploy_${{ variables.env }}
  pool: ${{ variables.agentPool }}
  jobs:
  - deployment: deploy
    displayName: Deploy_${{ variables.env }}
    environment: InformationLeaflets_${{ variables.env }}
    strategy:
      runOnce:
        deploy:
          steps:
          - script: docker pull mcr.microsoft.com/appsvc/staticappsclient:stable
          - task: AzureStaticWebApp@0
            displayName: Build and deploy app
            inputs:
              app_location: 'output'
              skip_app_build: true
              azure_static_web_apps_api_token: $(deployment_token)
```

Thanks for identifying the issue and sorry for the inconvenience.
