### ISSUE TITLE
Add ability to set app-settings-json similar to github action azure/appservice-settings@v1

### ISSUE THREAD

**Issue by staplJason** [Azure/static-web-apps#677]
Managing application settings from CLI or Portal is time consuming.
I would like to be able to set app settings using a github secret something like:
```yaml
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
...
          app-settings-json: '${{ secrets.AZURE_APP_SETTINGS }}' 
``` 
Same as it is done in the github action: azure/appservice-settings@v1
```yaml
- uses: azure/appservice-settings@v1
      with:
        app-name: 'my-app'
        slot-name: 'staging'  # Optional and needed only if the settings have to be configured on the specific deployment slot
        app-settings-json: '${{ secrets.APP_SETTINGS }}' 
        connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}'
        general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}' #'General configuration settings as Key Value pairs'
      id: settings
```
