### ISSUE TITLE
skip_deploy_on_missing_secrets is not supported

### ISSUE THREAD

**Issue by brianharwell** [Azure/static-web-apps#679]
**Describe the bug**

**To Reproduce**
1. Set up a build task and do not include the `` parameter

```
steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'MyApp'
    app_build_command: 'dotnet build'
    output_location: 'wwwroot'
    skip_deploy_on_missing_secrets: true
    # azure_static_web_apps_api_token: $(api_token)
```

Here is the error
```
Verbose logging enabled
deployment_token was not provided.
The deployment_token is required for deploying content. If you'd like to continue the run without deployment, add the configuration skip_deploy_on_missing_secrets set to true in your deployment configuration file
An unknown exception has occurred
Failed to record upload telemtry.
```

**Comment by miwebst** [comment]
Hey @brianharwell we need to make this logging message more concrete. We are expecting this to be an environment variable not an input. If you specify it as an env var this should work.

**Comment by kareldeman** [comment]
I have the same problem and although I have added "skip_deploy_on_missing_secrets" as an environment variable (I just added it in the variables configuration), I still get the error "_The deployment_token is required for deploying content. If you'd like to continue the run without deployment, add the configuration skip_deploy_on_missing_secrets set to true in your deployment configuration file_". All I want is the single page application we have to only build in the build pipeline and then in the release pipeline to not build it, but deploy it - in the same way we do it with our Azure Function Apps. I get this behavior either when I use a YAML or use the "deploy azure static web app [preview]" task...

**Comment by brianharwell** [comment]
>All I want is the single page application we have to only build in the build pipeline and then in the release pipeline to not build it, but deploy it - in the same way we do it with our Azure Function Apps.

That's exactly what I am trying to do

**Comment by miwebst** [comment]
@kareldeman can you share your workflow file? Also what source control provider are you using?

**Comment by kareldeman** [comment]
Here is the YAML for the Static Web App (which is in preview) task I added:

```
steps:
- task: AzureStaticWebApp@0
  displayName: 'Static Web App: '
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/_FE_Client'
    app_location: /MVP
    app_build_command: 'npm run build -- web'
    output_location: dist/apps/web
    skip_app_build: false
    verbose: false
```

Notice I did not provide the $(deployment_token) as I don't want the above to deploy. I added the "skip_deploy_on_missing_secrets" to the Pipeline variables and set it to true:

![image](https://user-images.githubusercontent.com/17554220/152141785-9f077e04-ba78-43a3-ac99-37ad92b9142a.png)

In the Initialize Job I can see the "skip_deploy_on_missing_secrets" in the "environment variables available are below" section:

![image](https://user-images.githubusercontent.com/17554220/152142015-3fcaac10-2693-453c-a358-bd035a35e0bc.png)

With the above, I still get the following error:

![image](https://user-images.githubusercontent.com/17554220/152142249-59d92d17-48d7-40d4-8043-15ef81bfd157.png)
