### ISSUE TITLE
deployment_token provided was invalid. on 2 workflow files for same repo.

### ISSUE THREAD

**Issue by jose-vazquez2** [Azure/static-web-apps#718]
**Describe the bug**

Have 2 environments mapped to 2 branches prod and dev, i deployed 1 static web app for prod and that worked great, but when i added a new workflow file for dev linked to an entire new static web app wit its own workflow  file and secret locked to develop branch the build and deploy step fails with "deployment_token provided was invalid."  i did double check the deployment_token was correct for each workflow file, ( i know about the staging env feature but that doesnt work well with our auth so we going the 2 static web apps route)

**To Reproduce**
create 2 static web apps, linked to the same repository but different branch.
Push to main branch deploys goes fine.
Push to develop branch  deploy fails with "deployment_token provided was invalid"

the workflow file is the auto-generated for github actions on https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions
with the branch modified 

```
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

```

**Expected behavior**
Each branch should deploy to each static web app without any issues.

**Comment by miwebst** [comment]
Hi @jose-vazquez2, we will need more information to investigate this. If you are comfortable, can you post your complete workflow files, the default hostname of your 2 SWA's, and any relevant logs from the GitHub Actions output? If you are not comfortable posting that, I'd recommend going through support in the Azure Portal.

Another thing you can do is reset the deployment token in the Azure Portal for the SWA that is not working and update the secret in your GitHub repo. You should not see this from a fresh deployment token.

**Comment by jose-vazquez2** [comment]
Hi @miwebst, i did try refreshing the deployment token multiple times on both apps, still same behaviour, also tried creating an entire new static web app for dev and got same result

the workflow file is exactly the same as the one auto-generated by their wizard in both just swap the branch name and the secret.key  for each env (i renamed the secret key name for convenience, but the exact same behavior was with the autogenerated AZURE_STATIC_WEB_APPS_API_TOKEN_SOME_RANOM_ID)

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: self-hosted
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: self-hosted
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV}}
          action: "close"
```
