### ISSUE TITLE
AzureStaticWebApp deployment task does not recognize artifact location

### ISSUE THREAD

**Issue by AmbachtIT** [Azure/static-web-apps#722]
I am trying to deploy an Azure Static Web App using an Azure DevOps yaml pipeline. The provided example template builds the app and deploys the static web app immediately:
![image](https://user-images.githubusercontent.com/34813625/153388103-688adeae-7b3a-491d-b3e9-f808dff1c7ed.png)

I'd like to separate these two steps in two stages:

1. Stage 1: Build and package the application and publish it to an artifact
2. Stage 2: Deploy the packaged application from the artifact to an azure static web app instance.

These are the deploy tasks I've implemented:

![image](https://user-images.githubusercontent.com/34813625/153388743-57d87665-21bd-4044-a281-439339e0e4d7.png)

The approach works fine for an Azure Functions app. But the Azure Static Web App task is unable to find the location:

![image](https://user-images.githubusercontent.com/34813625/153389988-9ef58768-f020-4e49-b3dc-7ff45234e4ca.png)

The artifact does contain the required files:

![image](https://user-images.githubusercontent.com/34813625/153389655-001aa855-b9bd-43a8-9750-bdea1e0fe537.png)

This is the full `yaml ` build, for reference:
```
# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  # You NEED to configure these variables
  azureSubscription: '__REDACTED__'
  prefix: 'Ambacht.Common'
  functionAppName: 'amb-fun-common'
  
  # These are probably fine
  framework: 'net6.0'
  configuration: 'Release'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Solution
      inputs:
        command: 'build'
        projects: '$(prefix).sln'
        arguments: --configuration $(configuration)

    - task: ArchiveFiles@2
      displayName: 'Archive Functions App Files'
      inputs:
        rootFolderOrFile: 'src/$(prefix).Functions.App/bin/$(configuration)/$(framework)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/Functions.$(Build.BuildId).zip
        replaceExistingArchive: true
        
    - task: CopyFiles@2
      displayName: 'Copy Blazor App Files'
      inputs:
        sourceFolder: 'src/$(prefix).Blazor.App/bin/$(configuration)/$(framework)'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)/Blazor.$(Build.BuildId)'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy Functions App'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/Functions.$(Build.BuildId).zip'

          - task: AzureStaticWebApp@0
            displayName: 'Deploy Blazor App'
            inputs:
              app_location: '$(Pipeline.Workspace)/drop/Blazor.$(Build.BuildId)'
              skip_app_build: true
              output_location: 'wwwroot'
            env:
              azure_static_web_apps_api_token: $(deployment_token)
```

**Comment by anthonychu** [comment]
The AzureStaticWebApp task’s app location is relative to the current directory, which you have to set if it differs from the default. Try:

```yml 
app_location: /
output_location: “”
skip_app_build: true
cwd: $(Pipeline.Workspace)/drop /Blazor.$(Build.BuildId)/wwwroot
```

See documentation for more details: https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration
