### ISSUE TITLE
The content server has rejected the request with: InternalServerError

### ISSUE THREAD

**Issue by FreshP0325** [Azure/static-web-apps#725]
Hi there,

Following the official help docs to build a Next.js project on Azure Static Apps, but the GitHub Actions returned error that stopped the project to go further.

The repo I used to deploy is [GitHub.com/unix/unix.bio](https://GitHub.com/Unix/Unix.bio)

The related GitHub Actions workflow configuration is here

```yml

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_RIVER_039A62700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_RIVER_039A62700 }}
          action: "close"
```

The error,

```
2022-02-12T02:35:08.7480143Z [31mThe content server has rejected the request with: InternalServerError[0m
2022-02-12T02:35:08.7480786Z [31mReason: An unexpected error has occurred. Please try again later.[0m
2022-02-12T02:35:08.9209777Z [37m[0m
2022-02-12T02:35:08.9210637Z [33mFor further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/[0m
2022-02-12T02:35:08.9211512Z [33mIf you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/[0m
2022-02-12T02:35:08.9212027Z [33mExiting[0m
2022-02-12T02:35:09.0651960Z Post job cleanup.
```

![11E0CC52-F2CB-474B-A5E4-4DCEFD1A2FEA](https://user-images.githubusercontent.com/54257356/153694095-5345382c-3c7b-4a25-8add-7ce92e9baa94.jpeg)
