### ISSUE TITLE
Closing of PR does not delete staging environment

### ISSUE THREAD

**Issue by burhan** [Azure/static-web-apps#726]
**Describe the bug**

I'm using the [static-web-apps-deploy](https://github.com/Azure/static-web-apps-deploy) github action. The staging environments are created, but when the PR is merged, they are not deleted and `No matching Static Web App environment was found.` error is shown in the logs.

For now, we are having to manually delete the staging environments as the other builds will fail as it quickly reaches the 10 environment limit.

There is only one action that both deploys (creates the staging environment) and should delete it. The delete part is not working:

```
name: dev-push (app-revamp-v2)

on:
  push:
    branches:
      - app-revamp-v2
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - app-revamp-v2

jobs:
 sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=tfo
          -Dsonar.projectKey=client-desktop
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
        
 build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
           CI: false
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REDACTED }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

 close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REDACTED }}
          action: "close"
```
The _warning_ in the output is:

```
Looking for event info
No matching Static Web App environment was found.
Thanks for using Azure Static Web Apps!
Exiting
```
