### ISSUE TITLE
Allow passing of environment variables from Azure/static-web-apps-deploy@v1 to static web app functions

### ISSUE THREAD

**Issue by boy-incerta** [Azure/static-web-apps#728]
Just as a disclaimer, I'm only starting out with Azure and the azure/static-web-apps-deploy@v1 action, but I'll try to give enough information. We have an app build and deployed via Github actions. It uses the Azure/static-web-apps-deploy@v1 action to push to Azure static web app. I would like to pass environment variables with the mentioned action so I can use them in my static web app function as such:
```
name: Build And Deploy
id: builddeploy
uses: Azure/static-web-apps-deploy@v1
with:
  azure_static_web_apps_api_token: xxxxxx
  repo_token: xxxxxxxx
  action: 'upload'
  env:
     TEST_ENTRY: 'test'
```

My static web app function currently grabs some settings from the App settings of the static web app config, via process.env, and I would like to extend those with the environment variables mentioned above (TEST_ENTRY)

Ideally I would be able to pass these environment variables with the Github action and use them in my Function together with the ones coming from app settings.

I've tried doing this like the example above, but TEST_ENTRY is not in the function response, meaning it doesn't exist.

Additional extra information, I would like to pass the Git commit sha of the code from the action workflow to my static web app function so I can use it in my code.
