### ISSUE TITLE
Internal Server Error on pipeline run

### ISSUE THREAD

**Issue by POeticPotatoes** [Azure/static-web-apps#746]
Hi, I'm trying to deploy my Angular static webapp through azure devops as a pipeline. The project works and builds with no issues locally but I'm encountering an Internal Server Error when I try to deploy it on Azure. This is the error message I get:

<img width="1034" alt="Screenshot 2022-03-04 at 11 37 10 AM" src="https://user-images.githubusercontent.com/91976287/156694968-432c8d0b-a3b7-4d3e-a6e8-b174bc902aee.png">

my pipeline (the default node.js pipeline except node version is changed to 14): 
```
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
```

I would like to provide more information but there isn't anything else stated with the error.
