### ISSUE TITLE
Max app size seems different than reported by Oryx

### ISSUE THREAD

**Issue by standup75** [Azure/static-web-apps#769]
**Describe the bug**

I got a standard tier for my swa:
![image](https://user-images.githubusercontent.com/302860/159803203-882d95f7-b2e9-4fb2-9e5f-2161b4b4f536.png)

Nevertheless deployment fails with the message that my app is over 100MB:
```
---End of Oryx build logs---
Function Runtime Information. OS: linux, Functions Runtime: ~3, node version: 12
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.
```

Any reason why this 2 values are different (100MB vs 500MB)?

**Comment by miwebst** [comment]
That is very odd...can you share any details about the name of your app (resource or default hostname) so we can investigate?

**Comment by miwebst** [comment]
Oh sorry, this is saying the Function content is above 100 MB. The limit above is about the size of the static content for the Static Web App. I believe 100 MB is currently the limit for the Function content.

**Comment by standup75** [comment]
Is there a way to have a higher limit for the function app? @prisma/client package alone is over 150MB

**Comment by a-haan** [comment]
I get this error when trying to deploy a nextjs app, no way is my api folder above 100mb

**Comment by mvn-ngoctran2-dn** [comment]
@a-haan ,  I have this error too. It happened around 5 days ago.

**Comment by microbecode** [comment]
I have the same issue. I don't fully understand which parts are uploaded to a Function and which are the static parts. I emptied my 'api' folder completely but that didn't help. My project really isn't anything complicated, but I guess some packages take a bit of space.

I would really like to see the limit raised.

**Comment by ngoctp27** [comment]
@a-haan , @microbecode. I have another solution for this case. Use Azure Devops (Pipelines) instead. It worked.

**Comment by valstu** [comment]
@ngoctp27 any change you could share your azure-pipelines.yml? I seem to get same error in Pipelines 🤔

**Comment by ngoctp27** [comment]
@valstu I use `nextjs` framework, I think it is temporary work with Azure Devops (Pipelines). Because it restricts by the official document [Bring your own functions to Azure Static Web Apps](https://learn.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own#:~:text=Set%20api_location%20value%20to%20an%20empty%20string%20(%22%22)%20in%20the%20workflow%20configuration%20file.) .
Maybe they don't maintain this Action anymore and it uses the container image latest version, closed source code.
I will move to another web hosting service for safety. 🥲
```
- task: AzureStaticWebApp@0
    inputs:
      app_location: '/' # App source code path relative to cwd
      app_build_command: 'yarn install; yarn run build; yarn run export'
      api_location: 'api' # Api source code path relative to cwd
      output_location: 'out' # Built app content directory relative to app_location - optional
      cwd: '$(System.DefaultWorkingDirectory)' # Working directory - optional
      azure_static_web_apps_api_token: $(deployment_token)
      is_static_export: true
```
