### ISSUE TITLE
DevOps Pipeline Fails With Error: The process '/usr/bin/bash' failed with exit code 1

### ISSUE THREAD

**Issue by superhappychris** [Azure/static-web-apps#776]
**Describe the bug**
My DevOps pipeline just started failing today (last successful build was last night). The project is a react front end with javascript function endpoints. The build fails after uploading to the app service. From what I can tell, it times out when polling to see if the upload finished (see screenshot). The code still gets deployed though.

**To Reproduce**
1. Check in a code change.
2. Push to DevOps repo
3. Kick off build pipeline

**Azure Pipelines YAML File** 
```
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'build'
      api_location: 'api'
      verbose: true
      azure_static_web_apps_api_token: '$(deployment_token)'
```

**Expected behavior**
Build succeeds without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/4143889/161869424-a2699b1f-6123-4cbf-abf4-f14d4eabd9af.png)
