### ISSUE TITLE
Help! Deploying pre-built API

### ISSUE THREAD

**Issue by egeyer** [Azure/static-web-apps#795]
I have been struggling to get a static web app deployed that needs a private github repo while building the API.  
I'm using a dotnet 6.0 stack -- blazor front end and functions dotnet:6.0 backend.  

After a lot of internet searching, I finally stumbled upon someone suggesting that I use separate code to build the pieces and then use the skip flags.  

However, I must be missing something...because when it gets to the api piece in the static-web-apps-deploy action, I get a message that Oryx "Cannot deploy to the function app because Function Language info isn't provided".  

I read in the documentation here (https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-the-api) that I should set the platform language in the web apps config file,
So, I added 
```
"platform": {
        "apiRuntime": "dotnet:6.0"
    }
```
to the staticwebapp.config.json file in my clientapp (which I'm also pre-building because of confusion with an existing package.json file).  

Can someone please help me figure out what I'm missing?

Here's the gist of my action yml file.
```
name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/<repo>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_PAT }}
      - name: .NET restore Api
        run:  |
          dotnet restore <ApiApp>
          dotnet restore <ClientApp>
      - name: .NET publish client
        run: dotnet publish --no-restore <ClientApp> -c Release -o blazor
      - name: .Net build API
        run: dotnet build --no-restore <ApiApp> -c Release
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_ISLAND_0295B050F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "blazor/wwwroot" # App source code path
          api_location: "<ApiApp-RootFolder>" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_api_build: true
          skip_app_build: true
```

I don't know what else to try.  Can someone please share some insight as to what I'm missing?  
Is it not finding the static web app config file?  All of this started from the "simple" complication of trying to build using a private github nuget repo, so if there's another solution for that, I'm open also! 

As an addendum: If I put a location for `api_location` that doesn't exist, it does deploy the frontend of my app, but no functions are deployed...but it at least lets me know that my UI deploys successfully.  So, the root of my question appears to be how to get a pre-built API code to successfully deploy with the static web apps deploy action step.

Thanks for any help.

**Comment by anthonychu** [comment]
Is your repo public? I don’t think there’s enough info here to troubleshoot.

**Comment by egeyer** [comment]
No, sorry, it's not a public repo.  It's one that's internal to my company.  I can do my best to provide whatever might be helpful, though.  I have tried so many things!  This morning, I realized that maybe because I was building the frontend myself, it wasn't properly seeing the `staticwebapp.config.json` file. When it deployed the frontend without the backend, I did notice that my rewrite for Login didn't seem to be working.  So I added that file to the output directory on build.  However that doesn't really change anything.  

I still wonder if it's not properly locating my config because when it's deployed without any functions, my redirect to login (for .auth/login/aad) doesn't work.  And since it is complaining about not knowing the language for deploying the API -- which is also in that config file -- maybe it can't find it. ?? 

So if I build the frontend myself, is there anything special I need to do to make sure the swa deployment action knows where my staticwebapp.config.json file is?

**Comment by tkamesh** [comment]
Azure Swa scans for `staticwebapp.config.json` under the directory of `app_location`. In this case `blazor/wwwroot` didn't contain required config, so it failed. Also, `api_location` should be full path like - `Api/bin/Release/net6.0`.

**Comment by egeyer** [comment]
@tkamesh  Thank you!  I had actually tried to do both of those things.  But as things go, I had a bug/typo in my MSBuild step that copied the config file to the published directory.  And when changing the location of the Api didn't do anything, I may have changed it back while attempting to find the magic combination, so I guess I didn't have both changes going at the same time.  

I think the only thing I would suggest coming out of this escapade is that the documentation  here (https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-front-end-app) should mention adding the step to make sure the config file is copied to the output directory.  I don't know about other platforms, but I know the github template for the blazor app doesn't have that.

But the rest of this was a bit of user error and this issue can be closed if it the documentation request isn't in the right spot.

Thanks for helping me out!

**Comment by Reshmi-Sriram** [comment]
@egeyer Thank you for the callout! We're glad you could resolve your issue, and will work soon on updating the doc! :)

**Comment by GearTheWorld** [comment]
I actually have an Angular 14.x and here's the yaml.  I get the exact same error.  Any idea what to do to fix that ?
### **Cannot deploy to the function app because Function Language info isn't provided**

```
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master
pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script:
    npm install -g @angular/cli
    npm cache clean
    npm install --loglevel=error
    ng build
  displayName: 'npm install and build'
- task: AzureStaticWebApp@0
  inputs:
      app_location: "/"
      api_location: "api"
      output_location: "dist/cubiShippingDashboard"
      skip_api_build: true
      
      # Documentation
      # ----------------------------------
      # app_location is the root location of the source code to be deployed. This setting will typically be / or the location of the JavaScript and HTML for your project.
      # output_location is the name of the folder created by any build process from a bundler such as webpack. This folder both needs to be created by the build process, and a subdirectory under the app_location
      #
      # https://learn.microsoft.com/en-us/answers/questions/667159/deploying-nextjs-app-to-azure-static-web-app-fails.html
      # https://learn.microsoft.com/en-us/azure/static-web-apps/faq
      # https://learn.microsoft.com/en-us/azure/static-web-apps/troubleshooting
      # https://learn.microsoft.com/en-us/azure/static-web-apps/local-development (Emulator in VS Code)
      # https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy/ (Pas essayé mais c'est tentant)
      # https://github.com/Azure/static-web-apps/issues/73
      # https://github.com/microsoft/Oryx/issues/1703 (Magie, une nouvelle étape de franchie)
      # https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-front-end-app
  env:
      continueOnError: true
      CUSTOM_BUILD_COMMAND: "npm install --unsafe-perm --loglevel=error"
      azure_static_web_apps_api_token: $(deployment_token)

```
