### ISSUE TITLE
401: Unauthorized during yarn install

### ISSUE THREAD

**Issue by michaelscodingspot** [Azure/static-web-apps#805]
I'm trying to build a CI/CD from Azure DevOps to deploy to a Static Web App. I'm using the task `AzureStaticWebApp@0`. 

During `yarn install`, I get the error 401 Unauthorized error: 
```
error An unexpected error occurred: "https://office.pkgs.visualstudio.com/_packaging/Office/npm/registry/@fluentui/react/-/react-8.49.7.tgz: Request failed \"401 Unauthorized\"".
```

Locally it works.
I tried removing `yarn.lock` and changing local `.npmrc` without success.

My yaml file:
```
pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master
jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-lively-sea-09764e70f-variable-group
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      cwd: "$(System.DefaultWorkingDirectory)/secure-brs-web"
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_SEA_09764E70F)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "build" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

My package.json:
```
{
  "name": "secure-brs-web",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fluentui/react": "^8.49.7",
    "@fluentui/react-components": "^9.0.0-alpha.124",
    "@fluentui/svg-icons": "^1.1.144",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "dauthservice-new": "^1.1.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.17.5",
    "react-router-dom": "^5.3.0",
    "react-scripts": "4.0.3",
    "react-select": "^5.1.0",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1",
    "xml-formatter": "^2.5.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react-router-dom": "^5.3.1"
  }
}
```

Thanks in advance.
