### ISSUE TITLE
Production deploy failing during content distribution

### ISSUE THREAD

**Issue by tanepiper** [Azure/static-web-apps#811]
**Description:**

I have two GitHub Action pipelines set up - one for Pull Request, and one for Merge to Main.  Both pipelines do a custom build: We use PNPM as a package manager, and build a [Astro](https://astro.build) website - then use `Azure/static-web-apps-deploy@v1` as the final step to do the 'upload' action. In the PR file, there is also a job to call the 'close' action.

In the PR file, everything works fine and deploys.  When the PR is merged the 'close' action works fine, but the merge pipeline 'upload' fails after about 15 seconds with the following message:

```
Verbose logging enabled
Build timeout not specified, defaulting to 15 minutes
App Directory Location: 'dist/apps/hub' was found.
No Api directory specified. Azure Functions will not be created.
Looking for event info
Event info parsed from GitHub event json.
Skipping step to build /github/workspace/dist/apps/hub with Oryx
Didn't find Oryx manifest file under location: /bin/staticsites/ss-oryx/app-manifest/oryx-manifest.toml
Could not find staticwebapp.config.json file.
Determined default file to be: index.html
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Zipping App Artifacts
App Zip will be created from directory: /github/workspace/dist/apps/hub
Done Zipping App Artifacts
Uploading build artifacts.
Skipping function upload as functions are identical to last successful deployment.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.2689137(s)
Status: Failed. Time: 15.5947[25](https://github.com<redacted>/runs/6554379448?check_suite_focus=true#step:9:26)4(s)
Deployment Failed :(
Deployment Failure Reason: Failure during content distribution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

I have enabled `VERBOSE: true` in the environment variables, but there are no further logs.

We are using both GH and Azure Enterprise.  The YAML files used are as follows, almost identical except for no `if` or `'close'` block in the merge file.

**ci-pr.yaml**
```yaml
name: Pull Request

on:
  pull_request:
    branches:
      - '**'
    types: [opened, reopened, synchronize, closed]

jobs:
  pull_request:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: 'Deploy: Development'
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout Code from Repo
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: 'Checkout'
        run: git fetch --no-tags --prune --depth=5 origin main
      - name: 'Setup: CI Environment (NodeJS: ${{ matrix.node-version }}, ubuntu-latest)'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        # Install Machine-Level Dependencies
      - name: 'Setup: Machine Dependencies'
        run: |
          .github/scripts/env-clean minor
          .github/scripts/env-setup
      # Check for cached dependencies
      - name: 'Setup: Cached Dependencies'
        id: cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
      # Run NPM Install if no cached dependencies
      - name: 'Setup: Install Dependencies'
        run: pnpm install
      - name: 'Run Build'
        run: 'pnpm build hub'
      - name: 'Build And Deploy'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC }}
          repo_token: ${{ secrets.GH_PAT }}
          action: upload
          app_location: 'dist/apps/hub'
          output_location: ''
          skip_app_build: true
        env:
          VERBOSE: true

  close:
    name: 'Close: Development'
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC }}
          action: 'close'
        env:
          VERBOSE: true
```

**ci-merge.yaml**
```yaml
name: Deploy to Staging Environment

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
  pull_request:
    name: 'Deploy: Development'
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Checkout Code from Repo
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: 'Checkout'
        run: git fetch --no-tags --prune --depth=5 origin main
      - name: 'Setup: CI Environment (NodeJS: ${{ matrix.node-version }}, ubuntu-latest)'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        # Install Machine-Level Dependencies
      - name: 'Setup: Machine Dependencies'
        run: |
          .github/scripts/env-clean minor
          .github/scripts/env-setup
      # Run NPM Install if no cached dependencies
      - name: 'Setup: Install Dependencies'
        run: pnpm install
      - name: 'Run Build'
        run: 'pnpm build hub'
      - name: 'Build And Deploy'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC }}
          repo_token: ${{ secrets.GH_PAT }}
          action: upload
          app_location: 'dist/apps/hub'
          output_location: ''
          skip_app_build: true
        env:
          VERBOSE: true
```

**Expected Behaviour:**

That the **ci-merge.yaml** deploy job succeeds.

** Environment **

GitHub Action - `ubuntu-latest`
Azure Static Web App - Azure Enterprise
PNPM 7.1.0
Astro Static Site Builder

**Comment by joslinmicrosoft** [comment]
Hi @tanepiper are you able to give us some more information about this site/deployments? Some information that would be helpful:
* Rough timeframe when these deployments were failing
* Default generated hostname (if you're willing to share)
* Deployment Id of the failing deployments (these should appear at the top of your pipeline logs and look something like "DeploymentId: 00000000-0000-0000-0000-000000000000")

**Comment by tanepiper** [comment]
@joslinmicrosoft About 19 hours ago from when I posted this. https://ashy-bay-0afd96f03.1.azurestaticapps.net/

Deployment IDs:
ca458df5-caed-4284-9e6e-1f657de9b37e
52a79bbb-c6fa-40f8-a399-77b82f226169

**Comment by joslinmicrosoft** [comment]
Hi @tanepiper, thanks for the follow-up. So when you say you re-ran `ci-stage.yaml` is this the same as the `ci-merge.yaml` you have above? And this yaml is in the `main` branch but I assume also in your PR branch right?

One additional thing I'm curious about: in the GitHub Actions tab, for this failing workflow run, is the branch listed as `main` or as the PR branch?

**Comment by tanepiper** [comment]
@joslinmicrosoft Yes sorry, that's correct it's what we call staging as we then have another task to deploy to our internal production (different to the static website production as the above image) 

In the failing ones it's main

```
Run actions/checkout@v2
with:
  ref: main
```

**Comment by mishapos** [comment]
Hi @tanepiper could you please elaborate on what you would like the expected behavior to be with regards to these 2 pipelines? Specifically, which pipeline would you like to deploy to which environment?

By default, when the `Azure/static-web-apps-deploy@v1` task is run in a pull request trigger, it will deploy to a [temporary pull request environment](https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests) that will also get deleted when the pull request closes. My theory is that your deployments are failing because it's trying to upload to the same pull request environment as it's being deleted. 

We now support the concept of [named preview environments](https://docs.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=github-actions) so perhaps you would like your `ci-merge.yml` to deploy to there? Or would it be directly to your production environment (if you are using 2 different Static Web Apps for staging vs production)? Thanks!

**Comment by joslinmicrosoft** [comment]
Hi @tanepiper, the reason we're asking for additional details is that your custom workflow files are different from our standard workflow, and therefore the deployment behavior is unexpected. As @mishapos mentioned, triggering the ci-merge.yml workflow based on a pull request event leads to our service running through the logic to create a temporary pull request environment--hence why it is not deploying to your production environment.

Instead of triggering on pull request close, would it work if you triggered on _push_ to the main branch (more like the default workflow)? This would trigger just the same whenever a PR to main is merged. Namely, in ci-merge.yml:

```yaml
on:
  push:
    branches:
      - main
```

Please also let us know if there's contradictory/confusing instructions anywhere from the MS documentation, we'll make sure to clear that up.
