### ISSUE TITLE
Having an Empty Array in allowedIpRanges Denies All Access to App

### ISSUE THREAD

**Issue by zekink** [Azure/static-web-apps#814]
Not sure if this is a bug or a feature request, but in my mind this should work differently than it currently does.

I have three instances of a Static Web App - test, staging and production. These have different IP whitelist rules to limit access accordingly:
- test is only allowed from a couple of VPN IP's that the developers use
- staging is allowed from those same IP's, plus a couple of other ones that testers/security auditors use
- production should be open to everyone

Since Static Web Apps don't (yet?) allow for having different `staticwebapp.config.json` files for different instances, I generate the file inside the deployment pipeline using a shell script, something like this:

```
generate_config() {
  cat > $CONFIG_FILE <<EOF
{
  "networking": {
    "allowedIpRanges": $WHITELIST_IP_RANGE
  },
  "routes": [
    {
      ...
    }
  ]
  }
}
EOF
}
```

The shell script then inputs the IP's accordingly. This works fine for test and staging where I have a list of IP's I want to allow, but for production, I now have to have a different function with identical configurations, except without the networking block - otherwise the site will be completely inaccessible:

```
generate_prod_config() {
  cat > $CONFIG_FILE <<EOF
{
  "routes": [
    {
      ... otherwise identical contents as above
    }
  ]
  }
}
EOF
}
```

**Expected behavior**
To me the expected way it would work is if the `allowedIpRanges` array was empty, it would effectively mean to allow all, instead of deny all. This seems to be how it is for e.g. App Service (at least with Terraform, have not tried with Bicep or Arm templates).

**To Reproduce**
1. Have a `staticwebapp.config.json` file with `"allowedIpRanges": []`
2. Deploy
3. Try accessing your site, get a 403 error

**Additional context**
Another issue we ran into while debugging this issue, is that if you have a `staticwebapp.config.json` file in version control (we had the one for test in version control, and overwrote that in the staging and production pipelines with the shell script), the one in version control will **always** be checked out and used by the `AzureStaticWebApp@0` task - even if you remove the existing one during the pipeline and pass a new, different `staticwebapp.config.json` file as an artifact to the deploy stage. We were getting confused why the IP restrictions seemed to always be the same we had for the test environment, no matter how we tried to change them. So we had to remove the `staticwebapp.config.json` file from version control for this to work in the first place.

**Comment by mishapos** [comment]
Hi @zekink, thank you for using Static Web Apps! You are absolutely correct that having a _non-null_ empty array in `allowedIpRanges` blocks all incoming traffic. This is interpreted as "there are exactly zero IP ranges that you want to allow". 

We wanted to provide a quick and simple way for users to allow a range of IP addresses and block all others. Since this would be a breaking security change, our plan is to keep the current behavior.

However, all is not lost! If you want a simpler script, you can allow-list the CIDR range `0.0.0.0/0` in your production configuration. This CIDR range will allow *all* IP addresses to view your Static Web App, though I still recommend you go with your current solution since it is clearer in the configuration that there are no IP address restrictions and there will be one less runtime check. 😄

**Comment by mishapos** [comment]
@zekink Could you elaborate a little more on your situation with the `staticwebapp.config.json` file? What do your staging and production pipelines look like? 

The default workflow file created by Static Web Apps include the `checkout` action which will copy over all your source files to the Action runner. It may be over-writing your configuration file. Can you try adding your configuration file customization script between the `actions/checkout@v2` step and the `Azure/static-web-apps-deploy@v1` step? Thanks! 😃

**Comment by mishapos** [comment]
Also, have you seen the latest announcements regarding named and branch preview environments? https://docs.microsoft.com/en-us/azure/static-web-apps/preview-environments

Would these be useful to your workflow in testing in a staging environment before pushing to production?

**Comment by zekink** [comment]
> However, all is not lost! If you want a simpler script, you can allow-list the CIDR range `0.0.0.0/0` in your production configuration. This CIDR range will allow _all_ IP addresses to view your Static Web App, though I still recommend you go with your current solution since it is clearer in the configuration that there are no IP address restrictions and there will be one less runtime check. 😄

That's good to know about `0.0.0.0/0`! Unfortunately I wasn't able to find it in the documentation when looking for answers, so I didn't realize I could have used that. But yeah, the current solution works, while it's not perhaps the most beautiful looking shell script I've written.

> @zekink Could you elaborate a little more on your situation with the `staticwebapp.config.json` file? What do your staging and production pipelines look like?
> 
> The default workflow file created by Static Web Apps include the `checkout` action which will copy over all your source files to the Action runner. It may be over-writing your configuration file. Can you try adding your configuration file customization script between the `actions/checkout@v2` step and the `Azure/static-web-apps-deploy@v1` step? Thanks! 😃

Sure! This is what the relevant part of the production pipeline looks like (with unnecessary/client specific stuff removed or obfuscated):

```
pool:
  vmImage: "ubuntu-20.04"
  demands: npm

stages:
  - stage: "deploy_prod"
    displayName: "Deployment: prod"
    jobs:
      - job: generate_swa_config
        displayName: Generate SWA config file
        dependsOn: []
        steps:
          - bash: ./generate-swa-config.sh $(environmentName)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/staticwebapp.config.json"
              artifact: staticwebapp.config.json

      - deployment: deploy_frontend
        displayName: Deploy Frontend SPA
        variables:
          - group: PROJECT_prod
        dependsOn:
          - "generate_swa_config"
        pool:
          vmImage: "ubuntu-20.04"
          demands: npm
        environment: $(environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./pipeline/deploy-spa.yml
                  parameters:
                    environment: $(Environment.Name)
                    build_command: "npm run build:$(environmentName)"
```

And the template file:

```
parameters:
  - name: environment
    type: string
  - name: build_command
    type: string

steps:
  - checkout: self

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: staticwebapp.config.json
      path: $(Build.SourcesDirectory)/

  - bash: cat staticwebapp.config.json # debug, todo: remove

  - task: NodeTool@0
    displayName: "Use Node 16"
    inputs:
      versionSpec: "16.x"

  # authenticate to private npm registry
  - task: npmAuthenticate@0
    displayName: "Authenticate to npm private registry"
    inputs:
      workingFile: ".npmrc"

  - task: npm@1
    displayName: "Install dependencies"
    inputs:
      command: custom
      customCommand: "ci"
      workingDir: "$(Build.SourcesDirectory)"

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      output_location: "/build"
      app_build_command: "${{ parameters.build_command }}"
    env:
      azure_static_web_apps_api_token: $(deployment_token)
      INLINE_RUNTIME_CHUNK: false
```

So with that `cat staticwebapp.config.json` step I was able to see that the config did get passed to the deploy stage/template correctly, but when the `AzureStaticWebApp@0` task ran, it would then overwrite it with the wrong version of the file from version control that was only supposed to be used in the test environment, which I could see from the IP whitelist rule being applied when it wasn't intended to.

I'm not sure if the named & preview environments feature entirely fits our current needs, as all three of these environments/Static Web Apps have a different custom domain attached. Otherwise though the changes are mostly in code, so without that main requirement this could perhaps work. I guess you would still have to work around having different IP whitelist rules per environment by generating an environment specific `staticwebapp.config.json` file in the pipeline?
