### ISSUE TITLE
`unknown flag: --pull` when using `deployment_environment` in Azure Devops

### ISSUE THREAD

**Issue by jpzwarte** [Azure/static-web-apps#826]
I'm getting the following error:

```
Starting: Publish preview docs
==============================================================================
Task         : Deploy Azure Static Web App
Description  : [PREVIEW] Build and deploy an Azure Static Web App
Version      : 0.203.0
Author       : Microsoft Corporation
Help         : https://aka.ms/swadocs
==============================================================================
/bin/bash /tfs/_work/_tasks/AzureStaticWebApp_18aad896-e191-4720-88d6-8ced4806941a/0.203.0/launch-docker.sh
unknown flag: --pull
See 'docker run --help'.
##[error]Error: The process '/bin/bash' failed with exit code 125
Finishing: Publish preview docs
```

The config for this step is:

```yaml
  - task: AzureStaticWebApp@0
    displayName: 'Publish preview docs'
    inputs:
      app_location: '/'
      api_location: 'tools/api'
      deployment_environment: 'pullrequest'
      skip_api_build: true
      skip_app_build: true
      output_location: 'dist'
    env:
      azure_static_web_apps_api_token: $(deployment_token)
    condition: and(succeeded(), ne(variables.isMain, true))
```
