### ISSUE TITLE
Unable to correctly use APP_BUILD_COMMAND or RUN_BUILD_COMMAND in Gitlab CI/CD

### ISSUE THREAD

**Issue by PaulIvanov** [Azure/static-web-apps#866]
**Describe the bug**
Im currently attempting to run a custom build command for an angular 14 app using Gitlab's CI/CD pipeline and neither the `APP_BUILD_COMMAND` nor the `RUN_BUILD_COMMAND` work as expected

**To Reproduce**
1. Open gitlab CI/CD project with basic angular project
2. paste in the gitlab-ci.yml file
3. run pipeline
4. See error (image attached below)

gitlab-ci.yml
```
variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR'
  OUTPUT_PATH: '$CI_PROJECT_DIR/dist/'
  APP_BUILD_COMMAND: 'npm run build-prod'

stages:     
  - deploy

deploy_job:      # This job runs in the deploy stage.
  stage: deploy
  only:
    - main
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
 
```

**Expected behavior**
I would expect the script to pick up the environment variable and run the custom command

**Screenshots**

Error image
![AFA98C51-D5CD-4527-A6DC-1AADC7E29D60](https://user-images.githubusercontent.com/13825788/181392187-b32041cc-14d7-41b1-b106-ea9a9847c627.jpeg)

**Additional context**
