### ISSUE TITLE
Unexpected: The content server has unexpectedly rejected the request with: LengthRequired when using Dependabot

### ISSUE THREAD

**Issue by boy-incerta** [Azure/static-web-apps#869]
**Describe the bug**
We are using Dependabot to keep our dependencies updated. This runs scheduled on every monday morning at 7am. Pull requests created in our repository, automatically trigger a workflow that will create a staging site to see the changes in the pull request. 

One of the steps in the workflow is the Azure/static-web-apps-deploy@v1 action. For every pull request created by Dependabot the workflow will fail at the Azure/static-web-apps-deploy@v1 step with the following error: 

<img width="646" alt="Schermafbeelding 2022-08-02 om 09 49 41" src="https://user-images.githubusercontent.com/97019812/182321414-a1c659e1-597a-468f-9c0c-dba5068678ad.png">

Now the strange thing is, if I restart this workflow, it *does* work. Until yesterday :) I have restarted multiple times now but it keeps failing with the same error.

Other pull requests created directly by developers work fine and are correctly deployed to a staging environment.

I have searched online, but I couldn't find a lot about this specific error (LengthRequired)

I'm unable to share the full workflow YAML file, but here is the excerpt for the specific step (runs on ubuntu-latest):
```
- name: Build API & Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.VERY_SECRET_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # We follow the procedure where we control the build ourselves: https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-front-end-app)
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_app_build: true # Skip app build - optional
          app_location: 'dist' # App source code path
          api_location: 'api' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

The contents of the staticwebapp.config.json file are the following:
```
{
  "navigationFallback": {
    "rewrite": "index.html"
  },
  "platform": {
    "apiRuntime": "node:14"
  }
}

```

**Expected behavior**
I expect automatically created pull requests to build successfully as well. Also if it does fail, I would expect a more descriptive message to give me some hints where I should look.

**Device info (if applicable):**
The workflow runs on `ubuntu-latest` and the action is at V1. The workflows are run from Github.

Thanks in advance!
