### ISSUE TITLE
Updating globalHeaders in staticwebapp.config.json does not apply if etag is unchanged

### ISSUE THREAD

**Issue by Strepto** [Azure/static-web-apps#905]
**Describe the bug**

This is maybe wrong, but it seems right after some testing.

Steps to reproduce: 

Setup a staticwebapp.config.json with some global headers and some static html
```json
 "globalHeaders": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, OPTIONS",
}
```
deploy to a staging environment using Static Web App Cli Deploy
```sh
swa deploy -a "./build" -n swa-echo3dweb-temp --swa-config-location "." --env headertesting
```

check that the headers are correct by inspecting in chrome dev tools

Change the globalHeaders, for instance add POST to Methods
```json
 "globalHeaders": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
}
```
deploy again, with no content changes otherwise.

Observe that the headers for the index.html file does not change. It will still show  "Access-Control-Allow-Methods": "GET, OPTIONS", (no POST)

Change anyting in the index.html file.
Redeploy and see that the headers are updated.

THEN: Revert the changes in index.html and see that the headers are reverted to the original!

All this is tested in chrome with the dev-tools open and `disable-cache` checked ✅.

Deleting and re-creating the temporary environment does not matter.

**Expected behavior**

Updates to globalHeaders force a response change even if there is no content change / same etag in the deployed content.

**Device info (if applicable):**
 - OS: Windows
 - Browser Chrome
 - Version 104

**Additional context**

These changes were deployed with Static Web App Cli `1.0.2`

**Comment by ryanbuening** [comment]
I'm seeing a similar issue. I am not seeing my `Content-Security-Policy-Report-Only` header in my static app after deploying. My build and deploy steps are separate with `skip_app_build: true`. I'm assuming this wouldn't affect the staticwebapp.config.json from getting picked up correctly?

```
{
    "navigationFallback": {
        "rewrite": "/index.html"
    },
    "globalHeaders": {
        "Content-Security-Policy-Report-Only": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'report-sample'"
    }
}

```

```
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: npm install and run build
        run: npm install && npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: app

      - name: Deploy to Azure
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_STONE_0BAB0F910 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "" # App source code path relative to repository root
          api_location: "" # Api source code path relative to repository root - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
```
