### ISSUE TITLE
Does not honor `deployment_environment`

### ISSUE THREAD

**Issue by johnkors** [Azure/static-web-apps#910]
**Describe the bug**
Setting `deployment_environment: Production` does not deploy to `Production` in a PR context (PR towards  master/main).

**To Reproduce**
Run this step in a PR from non-main towards main.

```yml
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/' 
        output_location: 'dist/'
        app_build_command: 'npm run build-test'
        deployment_environment: Production  #
```

**Expected behavior**
A deployment to the Production environment.

**Actual behavior**
No deployment to Production, but a deployment towards another environment happens (more specifically a environment coupled to the branch the PR originates from).
