### ISSUE TITLE
SWA function API isn't showing SWA configuration variables when spinning up new SWA preview environments

### ISSUE THREAD

**Issue by rdpolarity** [Azure/static-web-apps#914]
**Describe the bug**
Configuration variables don't appear in the preview environment's function build using the pipeline AzureStaticWebApp@0 task

**To Reproduce**
(before any of this configure some variables in Production in the SWA configuration section on Azure)
1. Create a function app that serves up and uses environment variables from the SWA configuration
```typescript

const httpTrigger: AzureFunction = async function(
  context: Context,
): Promise<void> {
  context.res = {
    status: 200,
    body: {
      foo: process.env.BAR
      // ... other variables from azure SWA config
    },
  };
};

export default httpTrigger;
```
2. In the pipeline, build the website, and pass files into the AzureStaticWebApp@0 task parameters:
```yml
- task: AzureStaticWebApp@0
displayName: Deploy Preview SWA
inputs:
 workingDirectory: '$(Pipeline.Workspace)'
 app_location: '/web'
 api_location: '/api'
 deployment_environment: $(System.PullRequest.PullRequestId)
 skip_app_build: true
 azure_static_web_apps_api_token: $(deploymentToken)
```
3. Go to preview environment url (mines under `www.foo.bar/api/config`) showing the following:
![image](https://user-images.githubusercontent.com/17543653/189038143-d84e937e-8912-4255-a41f-f1c7106500bf.png)

**Expected behavior**
Config variables should show up at `api/config`.

**Additional context**
To be clear this can be fixed by updating a single variable once in the respective environment. My theory is that the production variables aren't being copied over to the preview environment variables before the function is built and launched.
