### ISSUE TITLE
App Directory Location is invalid. Could not detect this directory

### ISSUE THREAD

**Issue by Lamerchun** [Azure/static-web-apps#938]
I am using a yml like this

```
  - download: current
    displayName: Download dist artifact
    artifact: dist

  - task: AzureStaticWebApp@0
    displayName: Deploy to Static App
    inputs:
      azure_static_web_apps_api_token: $(XXX)
      skip_app_build: true
      app_location: './dist'

```

i am sure index.html lies in dist, but getting error

```
App Directory Location: './dist' is invalid. Could not detect this directory
```

**Comment by Lamerchun** [comment]
Solved by using cwd first

```
  - task: AzureStaticWebApp@0
    displayName: Deploy to Static App
    inputs:
      cwd: '/home/vsts/work/1/dist'
      azure_static_web_apps_api_token: $(XXX)
      skip_app_build: true
      app_location: '/'
```
