### ISSUE TITLE
Failing to deploy due to content size

### ISSUE THREAD

**Issue by jwo** [Azure/static-web-apps#95]
I'm building out a Gatsby site; it's been working well but recent PRs aren't deploying.

When I build the site locally, the public directory is 27mb.

```

Copy '/bin/staticsites/ss-oryx/app-int/node_modules' with all dependencies to '/bin/staticsites/ss-oryx/app-int/__oryx_all_node_modules'...

Copying production dependencies from '/bin/staticsites/ss-oryx/app-int/__oryx_prod_node_modules/node_modules' to '/bin/staticsites/ss-oryx/app-int/node_modules'...

Copying files to destination directory '/bin/staticsites/ss-oryx/app'...
Done in 23 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 169 sec(s).


---End of Oryx build logs---
Finished building app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this static site is 100000000 bytes.
Exiting
```

## My theory

It appears to be copying the node_modules along with the site. It's a static site; I'm not sure why it's copying the node_modules up. Those are 400mb.

## Question

1. Can I disable the uploading of node_modules ? 
2. Can I get the limit increased?

**Comment by m-sterspace** [comment]
I have no idea if this is at all related to your issue, but fyi, github actions has been in a degraded / partial outage for most of the day so far: https://githubstatus.com

**Comment by jwo** [comment]
@m-sterspace definitely could be; I didn't see the problem before. I'll check again when github action stabalizes,

**Comment by miwebst** [comment]
Hi @jwo, can you share your workflow file and the expected output folder after build? Node modules should not be copied up and most likely this could be an issue with not selecting the app artifacts correctly.

**Comment by jwo** [comment]
@miwebst absolutely. It's pretty vanilla, created from azure's wizard

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_WATER_0CD9B9E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_WATER_0CD9B9E10 }}
          action: "close"
```
