### ISSUE TITLE
Azure/static-web-apps-deploy@v1 generates deprecation warning regarding set-output

### ISSUE THREAD

**Issue by boy-incerta** [Azure/static-web-apps#952]
**Describe the bug**
I noticed a warning in our GitHub action that Node v14 was going to be deprecated. I therefor upgraded all actions that still used that version to Node v16 as well as the settings of the staticwebapp.config.json. After a successful build, this warning disappeared but a new one arose at the Azure/static-web-apps-deploy@v1 step. This states: 

`Warning: The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Is this something known and planned to be fixed?

**To Reproduce**
1. Run any actions file that contains the Azure/static-web-apps-deploy
2. After successful run, scroll to the bottom of the summary
3. You can find the warning there as well as in the logs of the specific step that contains the SWA action

staticwebapp.config.json:
```
{
  "navigationFallback": {
    "rewrite": "index.html"
  },
  "platform": {
    "apiRuntime": "node:16"
  }
}
```
@Azure/static-web-apps-deploy@v1 config:
```
 - name: Build API & Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA }}
          repo_token: ${{ secrets.GH }}
          action: 'upload'
          skip_app_build: true
          app_location: 'output'
          api_location: 'data'
          output_location: '' 
        env:
          FA_TOKEN: ${{ secrets.FA_TOKEN }}
```
Engines field of package.json as well as the package.json for the api function
![Schermafbeelding 2022-10-14 om 09 16 00](https://user-images.githubusercontent.com/97019812/195785711-8d8c1fc2-1c90-4856-96ce-12339ed59921.png)

**Expected behavior**
No warnings to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/97019812/195780253-e44b18f2-cded-4c02-b3ab-0c292901caf0.png)
![Schermafbeelding 2022-10-14 om 09 01 46](https://user-images.githubusercontent.com/97019812/195783197-fe5580de-6a94-4a24-9bb8-569ac92286de.png)

**Additional context**
Workflow file runs on ubuntu-latest

**Comment by arynaq** [comment]
Thank you for opening this, we see the same issue.

**Comment by carmenkolohe** [comment]
I am receiving the same issues in GitHub actions from using the autogenerated yaml generated by App Services. I have tried updating to the latest version of azure/webapp-deploy from @v2 (created by app services) to @v2.2.3. Does not fix. Is there a fix for this?

https://github.com/Azure/webapps-deploy/releases

```
 deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.3
        with:
          app-name: "name_of_app"
          slot-name: "name"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_ID }}
          package: release.zip

```
![Screen Shot 2022-10-18 at 2 24 36 PM](https://user-images.githubusercontent.com/69023218/196548366-9d02a1a0-287d-4c56-b6ee-c4a751152294.png)

![Screen Shot 2022-10-18 at 2 25 21 PM](https://user-images.githubusercontent.com/69023218/196548420-934f142b-90b7-49cb-8cb3-b5dd7fe7c224.png)
