### ISSUE TITLE
Initial deploy fails - GitHub Actions w/ Angular 14 - fatal: unable to connect to github.com:

### ISSUE THREAD

**Issue by laurence-splendr** [Azure/static-web-apps#968]
**Describe the bug**

My first deploy of an Angular 14 static web app is failing using GitHub actions (Auto-generated from configuration of the static-web-app from Azure).

When in the build step, in Oryx I get the following error (While monitoring from GitHub actions) when it execute:

`Running 'npm install --unsafe-perm'`

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/timaschew/cogent.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 140.[82](https://github.com/REMOVED/actions/runs/REMOVED/jobs/REMOVED#step:4:83).113.4]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-10-27T20_02_53_303Z-debug.log

```
Debug logs do not shed any further light.

I've created a new Static Web App, using a new auto-generated GitHub action and receive the same result.

**To Reproduce**
1. Go to Azure, configure a new static web app, use basic settings, configure for Angular. Make sure GitHub actions are created in GitHub
2. Wait for GitHub to run initial build/deploy
3. It will fail, bring up failure

GitHub Actions YAML file: 

azure-static-web-apps....yml

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REMOVED }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/REMOVED" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_REMOVED }}
          action: "close"

```
No staticwebapp.config.json file

**Expected behavior**
Expected that build will success and code deployed
