### ISSUE TITLE
Node version error creating Azure Static Web Apps

### ISSUE THREAD

**Issue by gabrielizalo** [Azure/static-web-apps#973]
**Describe the bug**

I used the Azure wizard to publish a Next JS App in GitHub to a new Static Web App.
The Azure Wizard uses this `yaml` file: `azure-static-web-apps-brave-mud-030f7e20f.yml`

My problem: Appears this error in the `Build and deploy job`:

**Summary**:

````
[Build and Deploy Job](https://github.com/Axioma-X/RespuestasLaborales.DashBoard/actions/runs/3372604436/jobs/5596228247)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
````

Also in the details appears this error:

````
error selenium-webdriver@4.5.0: The engine "node" is incompatible with this module. Expected version ">= 14.20.0". Got "14.19.1"
````

**To Reproduce**
Just use the Portal Azure Wizard to publish a Next JS App.

- GitHub Actions or Azure Pipelines workflow YAML file:

````
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_MUD_030F7E20F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_MUD_030F7E20F }}
          action: "close"
````

**Expected behavior**
Build and deploy should work without errors.

**Additional context**
How can I fix the `yaml` file? In the one I have, that Azure provided, I can't setup Node version.
