### ISSUE TITLE
Is there documentation on how to use a Build Artifact? Or is there any alternate approach to 'check out once'?

### ISSUE THREAD

**Issue by mcupito** [Azure/static-web-apps#990]
**Is your feature request related to a problem? Please describe.**
I'm attempting to "check out once," build (and apply environment-specific variables)  and deploy to separate environments. Originally, I was thinking I could re-use this action for all of my deploys (dev, staging, production, for example) but I am struggling a little with how to make sure I only check out the code from the repository once and use that same "snapshot" of the code to avoid checking out in every workflow step. 

**Describe the solution you'd like**
I was searching how others have accomplished this, but I haven't found much. It would be nice to leverage an artifact or some other mechanism for only checking out once from the repo, but still applying `env` variables during each build and deploy.

**Describe alternatives you've considered**
I tried leveraging a built artifact this way: `app_location: '/dist/apps/<myAppName>'` and `skip_app_build: true` .. I also tried `app_location: '/'` but am starting to wonder if I needed to also unzip the build artifact or taken a different approach.

**Additional context**
This action has surpassed my expectations so far -- there is likely just a misunderstanding or a missed reference that does what I am requesting.

**Comment by aaronpowell** [comment]
I haven't tried this specific scenario, but I have written a blog post on how to create a very custom CI/CD pipeline with SWA - https://www.aaron-powell.com/posts/2022-07-20-taking-a-swa-devops-pipeline-to-the-next-level/

That might offer a starting point for what you're trying to accomplish.

**Comment by Zhaph** [comment]
Not sure whether you're using GitHub Actions or Azure DevOps pipelines for your deployments, but I've been doing a very similar process to Aaron in DevOps.

Here's a very basic pipeline:

```yaml
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
          npm ci
      workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
      displayName: "npm install"

    - script: |
        npm run build
      workingDirectory: $(System.DefaultWorkingDirectory)/frontend/
      displayName: "npm run build"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/frontend/build/
        includeRootFolder: false
        archiveType: "zip"
        archiveFile: $(build.artifactStagingDirectory)/drop/site.zip
        replaceExistingArchive: true
      displayName: "Package site output"

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: "site"
        pathToPublish: $(build.artifactStagingDirectory)/drop/site.zip
      displayName: "Publish site deployment artifacts"

- stage: DevDeploy
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - deployment: Dev
    environment: "Dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            displayName: "Download the site"
            inputs:
              source: current
              artifact: site

          - task: ExtractFiles@1
            displayName: "Extract files"
            inputs:
              archiveFilePatterns: "$(Pipeline.Workspace)/**/site.zip"
              cleanDestinationFolder: true
              destinationFolder: "$(System.DefaultWorkingDirectory)/site/deploy/"

          - task: FileTransform@2
            displayName: 'Apply JSON Transforms'
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/site/deploy/'
              fileType: 'json'
              jsonTargetFiles: '**\staticwebapp.config.json'
              xmlTransformationRules: '' # disabled

          - task: AzureStaticWebApp@0
            displayName: "Deploy Static App"
            inputs:
              cwd: $(System.DefaultWorkingDirectory)/site
              app_location: "deploy" # App source code path relative to cwd
              api_location: "deploy-function"
              skip_app_build: true
              skip_api_build: true
              output_location: "" # Built app content directory relative to app_location - optional
              azure_static_web_apps_api_token: $(deploymentToken)
```

You're right that you need to unzip the artifact during the deployment step so that the files can be deployed into the container, this also allows you to run the FileTransform task over the `staticwebapp.config.json` and perform variable replacement based on variables in your library.
