### ISSUE TITLE
Oryx consistently detects v12 of node, when engine is set to v16

### ISSUE THREAD

**Issue by Sealjay** [Azure/static-web-apps#995]
**Describe the bug**
When building API for an Azure Function app compiling from typescript to js, oryx detects node v12.
```
Detecting platforms...
Detected following platforms:
  nodejs: 12.22.11
Version '12.22.11' of platform 'nodejs' is not installed. Generating script to install it...
Detected the following frameworks: Typescript
```

**Expected behavior**

Expect node v16 to be detected

**Additional context**

_staticwebapp.config.json_:
```
  "platform": {
    "apiRuntime": "node:16"
  },
```

_/api/package.json_:
```
  "engines": {
    "node": "16.18.0"
  }
```

_/api/host.json_:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "watchDirectories": ["prisma"],
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  }
}

```

_.github/workflows/xyz.yml_:
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API}}
          action: "close"

```
